### ISSUE TITLE
Update form on home page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#1]
Pallavi wants the form on the [home page](https://www.cncf.io/) updated to https://cloud.email.thelinuxfoundation.org/CNCFNewsletterSubscribe

> please replace where you see this link https://www2.thelinuxfoundation.org/l/6342/2018-02-05/3ysc35
> to https://cloud.email.thelinuxfoundation.org/CNCFNewsletterSubscribe
> let me know once done I can test it or you can submit the form and let me know if you see that submission in salesforce

**Comment by cjyabraham** [comment]
Waiting on Alex or Pallavi for html to insert.

**Comment by cjyabraham** [comment]
@dankohn are you aware of them wanting to insert [this form](https://cloud.email.thelinuxfoundation.org/CNCFNewsletterSubscribe) with the boxes stacked vertically like that in place of the current horizontal newsletter form?  I'm not sure who has approved this but it seems a suboptimal design. Additionally the form error messages don't look so good...

**Comment by dankohn** [comment]
Is it possible for us to style?

**Comment by cjyabraham** [comment]
I suppose so, if we integrate their html/css/js into our site, but it's a beast.  Currently they are recommending using an iframe, in which case we wouldn't be able to change the look at all.  I think Craig has been part of this conversation so I wonder what his thoughts are and what he has done on other instances on LF sites...

**Comment by dankohn** [comment]
@ccraigross Could you please comment?

**Comment by ccraigross** [comment]
@cjyabraham @dankohn - The digital marketing team is replacing all of our existing forms with forms built directly in Salesforce Marketing Cloud. It is the next step from Pardot > Gravity Forms > Marketing Cloud. My expectation (need to 100% confirm) is that we will be able to provide the digital marketing team with CSS or a link to a CSS file that would be leveraged so that these can be styled as needed.

If it ends up not working as expected, I would be inclined to suggest that we continue to leverage Gravity Forms on sites with extensive customization (i.e. CNCF) where we have highly refined branding/visuals already in place.

**Comment by cjyabraham** [comment]
I've integrated what they've sent us into the [dev site](https://dev-cncf.pantheonsite.io/) via iframe.  I see a few problems:

1. form validations don't appear
2. the Sign Up button jumps when you click it and can go below the iframe border
3. I think a horizontal layout of the buttons would work better in this location
4. the contents of the iframe require 13 requests, 135KB transferred 

It sounds like 1-3 could be solved with a custom CSS file loaded into the iframe.  I think, however, I prefer the Gravity Forms idea since we already have the plugin running on CNCF so the performance hit would be lower in addition to having more design flexibility.

Any thoughts?

**Comment by dankohn** [comment]
I'm fine either way.

**Comment by cjyabraham** [comment]
@ccraigross do you have any preference which way we go given the above points?

**Comment by ccraigross** [comment]
@dankohn @cjyabraham - just closing the loop on this, let's migrate from Pardot to Gravity Forms and then revisit in the near future. The ability to track users across all channels is the primary benefit for Cloud Forms, but we will need to balance that against any performance concerns, etc.

**Comment by cjyabraham** [comment]
@ccraigross sounds good.  So for next steps, should I just duplicate the current form using Gravity Forms?  And would you be able to take care of the Salesforce linkup?

**Comment by ccraigross** [comment]
@cjyabraham - Correct. We will need to make sure that the SF connector is active and functioning as expected. I have reached out to Marijana and Pallavi in the Slack thread we've had with them.

**Comment by cjyabraham** [comment]
This form has been tested and approved on the dev site.  I will deploy it live first thing tomorrow as it takes quite a bit of configuration to get it to look right.  Then we can test again.

**Comment by cjyabraham** [comment]
This has been deployed live and tested by Marijana Brown.
