### ISSUE TITLE
Add certifications to Speakers Bureau 

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#10]
Allow speakers to list whether they are certified as CKA, CKAD, and Ambassador.

**Comment by KimMcMahon** [comment]
Identify what information, in addition to certifications, we want Speakers to update.

**Comment by KimMcMahon** [comment]
The person would update their profile to check a box for each certification or as an ambassador.

CKA, CKAD, Ambassador symbol can appear in the box with their picture, perhaps to the left of their picture.

**Comment by KimMcMahon** [comment]
See [Speaker's Bureau document](https://docs.google.com/document/d/1IUA1O4Zr73cdtBSJQB9mcEdO0lisxWagNEaofICdty0/edit?usp=sharing).

For this task:
Allow speakers to add CKA, CKAD, KCSP, and Ambassador to their profile via a checkbox.

Use the logo / badge icon on the Speaker’s profile.

Place the logo / badge somewhere in the profile. Perhaps on the left and move the Twitter and LinkedIn icon to the right.

This is needed for the faceted search functionality.

Due date: August 13.

**Comment by cjyabraham** [comment]
Where in the profile would you like these checkboxes to go and it what order?  And am I correct in assuming we want a checkbox for each of the four designations?

**Comment by KimMcMahon** [comment]
Check boxes: On the registration page, directly below Bio.

On the profile One suggestion is adding the icon(s) on the same line as Twitter and LinkedIn icon. If that is not possible, the icon(s) can go elsewhere in the speaker card.

Agree - tackle the re-write as you do the faceted search.

**Comment by cjyabraham** [comment]
Ok, I've added them on both the registration page and profile page.  See screenshots:

This is the edit screen on the profile:
<img width="870" alt="Screen Shot 2019-08-10 at 11 59 09 AM" src="https://user-images.githubusercontent.com/463160/62817812-cd7b9f00-bb66-11e9-97fa-ca0f5f8e6de0.png">

This is how they will look when entered on the profile:
<img width="782" alt="Screen Shot 2019-08-10 at 12 00 57 PM" src="https://user-images.githubusercontent.com/463160/62817816-d9fff780-bb66-11e9-999f-774094d0a635.png">

And the registration form:
<img width="835" alt="Screen Shot 2019-08-10 at 12 01 41 PM" src="https://user-images.githubusercontent.com/463160/62817818-e4ba8c80-bb66-11e9-8fd1-4047235a6aaf.png">

**Comment by cjyabraham** [comment]
Could you incorporate the rewriting of the search tiles into #9 and create a separate issue for rewriting the profile to include the icons, if that's something you want to prioritize?  Then we can close out this issue?

**Comment by dankohn** [comment]
Certifications are CKA and CKAD. KCSP is something a company gets.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by KimMcMahon** [comment]
@cjyabraham My fault for not sufficiently researching how a company gets a KCSP. I knew it was xx number of people with a certification - and it's the CKA. Updating the document and removing this.

**Comment by KimMcMahon** [comment]
@cjyabraham The new certifications section, it was unclear to me (when I did a test signup) of what to put in there. Can it be made check boxes? Or with the "?" can you list the three options?

"Ambassador, CKA, CKAD"

**Comment by KimMcMahon** [comment]
On the field "Area of expertise", these are the specific items the user needs to select. This will need to be a drop down where multiple items can be checked or check boxes.

**Comment by dankohn** [comment]
Kim, please write up some bullet points about how we’ll give current speakers 2-3 weeks to update their profiles and deactivate them if they don’t. 

We probably want to do a quarterly Check-in to ensure that people are still reachable at that email and still interested in speaking.

**Comment by cjyabraham** [comment]
@dankohn I've removed KCSP.

@KimMcMahon regarding both the "Certifications" and "Area of expertise", these *are* multi-select controls where you can only select values that are provided in the drop-down.  To see the drop-down, click into the field. Alternatively, I could change it to a set of radio buttons, however, I don't think that would work well for "Area of expertise" since there are so many values.

**Comment by dankohn** [comment]
What is the dev URL where I can try this, please?

**Comment by dankohn** [comment]
Please change "Click here to learn more about this program." to "Learn more about this program." with Learn as the link. We want to avoid all uses of "Click here" https://www.smashingmagazine.com/2012/06/links-should-never-say-click-here/.

**Comment by dankohn** [comment]
Could we try a design refresh where we show "City, Country" and Areas of Expertise to the right of the picture and make every speaker box the same size? I don't see any reason to highlight Twitter and LinkedIn links from the scrolling page. Instead, it would allow a much denser list of speakers which would be faster to scroll through.

**Comment by cjyabraham** [comment]
@dankohn I've made the link change you asked for.  For your last comment, I've copied it to [the faceted search issue](https://github.com/cncf/wordpress-site/issues/9#issuecomment-520223484) so we can close out this issue without losing it.

**Comment by KimMcMahon** [comment]
@cjyabraham Requirements written up. 
Issue 27 created for the design

@dankohn Documented in the [Speaker Google doc](https://docs.google.com/document/d/1IUA1O4Zr73cdtBSJQB9mcEdO0lisxWagNEaofICdty0/edit?usp=sharing).

**Comment by cjyabraham** [comment]
I think the initial intent of this issue is now complete.

**Comment by cjyabraham** [comment]
Change certifications to checkboxes

**Comment by cjyabraham** [comment]
Done.
