### ISSUE TITLE
Fix too many redirects error

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#100]
https://www.cncf.io/webinars/attachment/cncf-slide-template-spinnaker-webinar/

**Comment by deigolocco** [comment]
fixed @dankohn 
The redirections rules were affecting this url, the original url is https://www.cncf.io/community/webinars/attachment/cncf-slide-template-spinnaker-webinar/ and is working fine now

**Comment by dankohn** [comment]
👍
