### ISSUE TITLE
Replace "Sign up for Newsletter" form with one from Salesforce

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#101]
LF are moving their forms to be hosted from Salesforce.  As a first one for CNCF, we'd like to replace the ["Sign up for Newsletter" form](https://www.cncf.io).  They have provided us the following code to power the form.  Would you please try embedding it in a test instance so we can see if it works?

```
   <meta charset="utf-8">
       <script src="http://code.jquery.com/jquery-1.9.1.js"></script>
       <div id="message"></div>
        <form id="myform" action="https://cloud.email.thelinuxfoundation.org/NoRedirectSubmission">
         <label for="FirstName" required="">First Name*
      <input type="text" name="FirstName">
    </label><br><br>
    <label for="LastName" required="">Last Name*
      <input type="text" name="LastName">
    </label><br><br>
    <label for="EmailAddress" required="">Email*
      <input type="text" name="EmailAddress">
    </label>
     <input style="background-color: #36B0C9" type="submit" value="Submit" id="loginbtn">
   
         
         
        </form>
        <div id="response"></div>

        <script>
            $(function() {
                $("#myform").on("submit", function(e) {
                    e.preventDefault();
                    $.ajax({
                        url: $(this).attr("action"),
                        type: 'POST',
                        data: $(this).serialize(),
                        beforeSend: function() {
                            $("#message").html("sending...");
                        },
                        success: function(data) {
                            $("#message").hide();
                            $("#response").html(data);
                        }
                    });
                });
            });
        </script>
   

<script>
  $("#loginbtn").click(function(){
   $("#myform").toggle();  // toggle will show hidden element and vice versa
});
</script>
```

**Comment by deigolocco** [comment]
@cjyabraham I implemented it [here](https://fz-101-cncf.pantheonsite.io/)
I adjusted the appearance to be even to the old one.
But I couldn't validate, because of a CORS permission
<img width="574" alt="Captura de Tela 2019-09-19 às 16 48 34" src="https://user-images.githubusercontent.com/5631313/65283203-0109fb80-db0d-11e9-8072-0c574f0508e7.png">
Could you add permission for the domains https://fz-101-cncf.pantheonsite.io/ and http://cncf.fuerza(my local one) and/or share the access to Salesforce platform?

**Comment by cjyabraham** [comment]
Ok.  I've CC'd you on an email thread with Marijana, who is the LF contact who is coordinating these new forms.  Hopefully she can help us out with this.  Feel free to work directly with her if I'm not around to push this forward.

**Comment by cjyabraham** [comment]
I just emailed Marijana again for suggestions on this.  We're currently blocked by CORS issues on the form they provided.

**Comment by cjyabraham** [comment]
Marijana delivered a new form which fixes CORS issues but does not have field validation, the CSS is poorly written etc.  I have provided feedback to her on Oct 24 and have been waiting for a reply since then.

**Comment by dankohn** [comment]
Please email Marijana again and cc me and Katelin Wussow.

**Comment by cjyabraham** [comment]
Tracking this now in [this issue](https://github.com/cncf/cncf.io/issues/20).

**Comment by cjyabraham** [comment]
hi @deigolocco , Marijana has provided [this code](https://docs.google.com/document/d/1cyA0IXJ5dvPsA1uX0f5PXe6i2g1Amv8CwMKogMSc_i8/edit?ts=5def1829).  Would you please see if you can replace the newsletter on the cncf.io homepage with it?  

As for the code, the only thing that is important is the names of the fields and the submit action url.  You should rewrite all the css and js to improve them and make them work for us.

**Comment by deigolocco** [comment]
working @cjyabraham https://fz-101-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
thanks.  deployed.
