### ISSUE TITLE
Graphics for Events web page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#102]
Rectangle size and square size

Serverless Practitioners Summit: Please pull the image from this page.
https://linuxfoundation.smapply.io/prog/serverless_practitioners_summit_north_america_2019_-_hosted_by_cncf_and_cloud_foundry_foundation/

Django Girls
Perhaps there is something on their website
https://djangogirls.org/nbari/

OpenInfraDays
Here is their website for a possible image
https://openinfranordics.com/

Cloud Native Revolution
https://www.comcastlabsconnect.com/events/cloud-native-revolution-2019

MIT leadership summit
http://forms.technologyreview.com/leadership-summit/

O'Reilly Software Architecture
https://conferences.oreilly.com/software-architecture/sa-eu

**Comment by pablodelarocha** [comment]
![djangogirls_square](https://user-images.githubusercontent.com/54405572/65277511-728f7d00-db00-11e9-881a-14b5a10ef5a4.jpg)
![djangogirls](https://user-images.githubusercontent.com/54405572/65277512-728f7d00-db00-11e9-81d3-7da965a8ee25.jpg)
![nordics_square](https://user-images.githubusercontent.com/54405572/65277513-728f7d00-db00-11e9-9620-e4817e3b4b04.jpg)
![nordics](https://user-images.githubusercontent.com/54405572/65277514-728f7d00-db00-11e9-9938-88f10fe3ebc4.jpg)
![serverless_square](https://user-images.githubusercontent.com/54405572/65277515-73281380-db00-11e9-8f2e-e7e50c58a2e6.jpg)
![serverless](https://user-images.githubusercontent.com/54405572/65277516-73281380-db00-11e9-8169-8031895e4dff.jpg)
![MIT_square](https://user-images.githubusercontent.com/54405572/65277517-73281380-db00-11e9-871f-bb1b1d25b1f3.jpg)
![MIT](https://user-images.githubusercontent.com/54405572/65277519-73281380-db00-11e9-8b2c-a990fb772422.jpg)
![Oreilly_square](https://user-images.githubusercontent.com/54405572/65277520-73c0aa00-db00-11e9-8262-814af751d613.jpg)
![Oreilly](https://user-images.githubusercontent.com/54405572/65277521-73c0aa00-db00-11e9-83ca-3d42cf531f76.jpg)
![CNRevolution_square](https://user-images.githubusercontent.com/54405572/65277522-73c0aa00-db00-11e9-85b6-0811bf048fd9.jpg)
![CNRevolution](https://user-images.githubusercontent.com/54405572/65277523-73c0aa00-db00-11e9-9d8c-0200ff0f9376.jpg)
@KimMcMahon here's all 6 banners on both sizes! Please let me know if these are all good to go.

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha
