### ISSUE TITLE
Graphic for Event page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#103]
https://events.linuxfoundation.org/events/cloud-native-security-day-2019/

Thanks!

**Comment by pablodelarocha** [comment]
![sig](https://user-images.githubusercontent.com/54405572/65339941-8344ff00-dba3-11e9-9a7a-fb84e610ec16.jpg)
![sig_square](https://user-images.githubusercontent.com/54405572/65339943-8344ff00-dba3-11e9-91b4-23a55e182a40.jpg)
Sure @KimMcMahon here's both banners as requested.
