### ISSUE TITLE
Graphic for Event page when there is no image

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#104]
Can you design something to use for the 'Events we'll be at' page when an event does not have an image?

**Comment by pablodelarocha** [comment]
Hi @KimMcMahon so far, whenever i don't find the event's logo or images related to it, i've been doing this model, which consists of a sky background and the event's name written over it. 
Example below:
![open-networking-summit](https://user-images.githubusercontent.com/54405572/65348775-52bb9000-dbb8-11e9-9107-07d00f4ef532.jpg)
![LF_energy_summit](https://user-images.githubusercontent.com/54405572/65348703-2c95f000-dbb8-11e9-8371-74600d955e07.jpg)
Would you like me to do more variations?

**Comment by KimMcMahon** [comment]
@pablodelarocha How about - so it looks different than a logo, use a gradient color background with no images.

Will this automatically be added to events that have no image? Or do I need to take the image, put the name of the event in the graphic, and upload to the event page?

Thanks!

**Comment by pablodelarocha** [comment]
Hi @KimMcMahon i'm sending below some suggestions of gradient color backgrounds based on the colors i could find on the website. 
As it is today, we're writing the name of the event on the banner image, but it can be done in a way that you just have to pick the gradient the event's name goes automatically placed over it, but it will need to be programmed to work that way. Just need your authorization to start developing it :)
![01 darkblue_square](https://user-images.githubusercontent.com/54405572/65887001-b5a8e600-e373-11e9-849b-0e39b65ed68d.jpg)
![02 -Purple+blue_square](https://user-images.githubusercontent.com/54405572/65887002-b5a8e600-e373-11e9-8d06-fa9f2906ff73.jpg)
![01 darkblue](https://user-images.githubusercontent.com/54405572/65887005-b5a8e600-e373-11e9-915f-150b466c4940.jpg)
![02 -Purple+blue](https://user-images.githubusercontent.com/54405572/65887007-b6417c80-e373-11e9-99a7-a1813c8d0315.jpg)
![03 -Pink+Yellow_Square](https://user-images.githubusercontent.com/54405572/65887009-b6417c80-e373-11e9-8bee-369396df624e.jpg)
![03 -Pink+Yellow](https://user-images.githubusercontent.com/54405572/65887011-b6417c80-e373-11e9-8ce7-cd171b540841.jpg)
![04 Blue_square](https://user-images.githubusercontent.com/54405572/65887013-b6da1300-e373-11e9-8f33-94c520dfbaf6.jpg)
![04 Blue](https://user-images.githubusercontent.com/54405572/65887015-b6da1300-e373-11e9-94a9-59726d9c66e0.jpg)
![05 Light-Purple+blue_square](https://user-images.githubusercontent.com/54405572/65887018-b6da1300-e373-11e9-8a15-23313cd54fdd.jpg)
![05 Light-Purple+blue](https://user-images.githubusercontent.com/54405572/65887019-b6da1300-e373-11e9-84b4-180a4909be00.jpg)

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha. Let's go with this one:
![image](https://user-images.githubusercontent.com/29307455/65894437-05cd7b80-e367-11e9-88c8-cbd569d30ea7.png)
Please develop!  

Thanks!

**Comment by pablodelarocha** [comment]
@KimMcMahon Ok! I will ask @deigolocco to start the development. 
As for the gradients, we can make all of these available for you to pick. Would you like that?

**Comment by KimMcMahon** [comment]
@pablodelarocha Sure - I didn't know I had choices! Thanks!

**Comment by deigolocco** [comment]
@KimMcMahon, please take at look:
https://fz-104-cncf.pantheonsite.io/
https://fz-104-cncf.pantheonsite.io/events-well-be-at/
https://fz-104-cncf.pantheonsite.io/events-well-be-at/grace-hopper-celebration-2019/

Now you have the checkbox
![Captura de Tela 2019-10-01 às 16 10 44](https://user-images.githubusercontent.com/5631313/65992760-3a742c80-e466-11e9-9234-36cfeaeab611.png)

Checking **Doesn't have logo**  the options will apear
![Captura de Tela 2019-10-01 às 16 10 34](https://user-images.githubusercontent.com/5631313/65992843-698a9e00-e466-11e9-8ad7-0552032a49b2.png)
Ex: https://fz-104-cncf.pantheonsite.io/wp-admin/post.php?post=43001&action=edit
You can choose a different background and custom copy if necessary

**Comment by KimMcMahon** [comment]
Looks great @deigolocco! Please deploy!

**Comment by deigolocco** [comment]
Thank you @KimMcMahon !

@cjyabraham please deploy when you have a chance

**Comment by cjyabraham** [comment]
@deigolocco There's a render issue for long titles at certain browser widths.  See below:
<img width="914" alt="Screen Shot 2019-10-02 at 2 21 10 PM" src="https://user-images.githubusercontent.com/463160/66025207-137a3100-e520-11e9-9f01-a46d5d670095.png">

**Comment by rodmeurer** [comment]
@cjyabraham fixed!

**Comment by cjyabraham** [comment]
deployed
