### ISSUE TITLE
Change how time zone is displayed on the Webinar page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#106]
https://www.cncf.io/webinars/

For upcoming webinars, display the time zone as:
10:00 - 11:00 am PT (UTC-7)

**Comment by cjyabraham** [comment]
@KimMcMahon PT is either UTC-7 or UTC-8 depending on the time of year.  Are you expecting this "(UTC-7)" to adapt to daylight savings time?

**Comment by KimMcMahon** [comment]
@cjyabraham Yes - adapt to daylight savings time.

**Comment by rodmeurer** [comment]
@KimMcMahon @cjyabraham done in these 3 locals where the time is displayed for upcoming webinars **(Branch: fz-106)**

https://fuerza-cncf.pantheonsite.io
https://fuerza-cncf.pantheonsite.io/webinars
https://fuerza-cncf.pantheonsite.io/webinars/cncf-webinar-series-container-native-development-tools-compared-draft-skaffold-and-tilt/

**Comment by cjyabraham** [comment]
Thanks @rodmeurer 

@KimMcMahon should we use the more specific PST and PDT and not use PT according to [these rules](https://english.stackexchange.com/questions/88485/proper-timezone-acronym-usage-pt-vs-pdt-or-pst/133704#133704)?

**Comment by KimMcMahon** [comment]
@cjyabraham I prefer to use PT instead of PST or PDT.

@rodmeurer It looks great. Although, I believe PT - UTC is currently -7.  It goes to -8 on November 3, 1am PT. The time zones shown on the test server are not correct.

**Comment by deigolocco** [comment]
@KimMcMahon is adjusted

**Comment by KimMcMahon** [comment]
@deigolocco The October 30 webinar still has PDT. Please fix, then let's deploy.

**Comment by deigolocco** [comment]
@KimMcMahon this part is editable
<img width="296" alt="Captura de Tela 2019-09-30 às 14 20 43" src="https://user-images.githubusercontent.com/5631313/65900974-91f29980-e38d-11e9-9eee-118e9072b973.png">
It's adjusted https://fuerza-cncf.pantheonsite.io/webinars/

**Comment by KimMcMahon** [comment]
Thank you @deigolocco! Deploy!

**Comment by cjyabraham** [comment]
deployed
