### ISSUE TITLE
Image for an event

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#107]
Hi Pablo!
Can you create a banner for this event?
https://www.mwclosangeles.com/

**Comment by KimMcMahon** [comment]
One more!

https://www.cloudexpoasiahk.com/

**Comment by pablodelarocha** [comment]
Sure @KimMcMahon here they are:
![cloud_expo_asia_Square](https://user-images.githubusercontent.com/54405572/65544722-3e460300-deea-11e9-8ba8-8cdd0239943a.jpg)
![cloud_expo_asia](https://user-images.githubusercontent.com/54405572/65544723-3ede9980-deea-11e9-9e5e-48a4842137bd.jpg)
![MWC_LA_Square](https://user-images.githubusercontent.com/54405572/65544724-3ede9980-deea-11e9-87d9-87ef83fde16e.jpg)
![MWC_LA](https://user-images.githubusercontent.com/54405572/65544725-3ede9980-deea-11e9-8082-2cded164aa7d.jpg)

**Comment by KimMcMahon** [comment]
One more please @pablodelarocha 
https://events.linuxfoundation.org/events/cloud-native-security-day-2019/

**Comment by pablodelarocha** [comment]
@KimMcMahon ok!
![squared_sig](https://user-images.githubusercontent.com/54405572/65555539-51b19800-df03-11e9-9f31-a111e7c99064.jpg)
![sig](https://user-images.githubusercontent.com/54405572/65555540-51b19800-df03-11e9-85eb-c1f6461f2133.jpg)

**Comment by KimMcMahon** [comment]
Thanks @pablodelarocha
