### ISSUE TITLE
Graphic for LF Energy Summit on 'events we'll be at' page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#108]
Please create something from this website
https://events.linuxfoundation.org/events/lfenergysummit2019/

**Comment by pablodelarocha** [comment]
@KimMcMahon sure! Here's the banner on both versions.
![lfenergy_square](https://user-images.githubusercontent.com/54405572/65883732-00bffa80-e36e-11e9-899d-b4d2fccf9377.jpg)
![lf_energy](https://user-images.githubusercontent.com/54405572/65883733-00bffa80-e36e-11e9-9d92-2bd455814b38.jpg)

**Comment by KimMcMahon** [comment]
Thanks!
