### ISSUE TITLE
Graphic for Kong Summit

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#109]
Create something from this?
https://konghq.com/kong-summit

**Comment by pablodelarocha** [comment]
@KimMcMahon here's the images as requested:
![kong_summit](https://user-images.githubusercontent.com/54405572/65901444-9ec3bd00-e38e-11e9-873b-b8ced5b23370.jpg)
![kong_summit_square](https://user-images.githubusercontent.com/54405572/65901445-9ec3bd00-e38e-11e9-80f1-d290ee7fc8af.jpg)

**Comment by KimMcMahon** [comment]
Thanks @pablodelarocha !
