### ISSUE TITLE
Speakers Bureau group emails

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#11]
This allows CNCF Members to authenticate (log in).  Then they could use the speakers filter to select a subset of speakers and they would have access to a special button, say, that allows them to email all of the filtered speakers in the list.

**Comment by cjyabraham** [comment]
Next step is for Kim to write up a more formal requirements doc.

**Comment by KimMcMahon** [comment]
Requirements outlined in the [Speakers Bureau Google doc](https://docs.google.com/document/d/1IUA1O4Zr73cdtBSJQB9mcEdO0lisxWagNEaofICdty0/edit?usp=sharing).

**Comment by KimMcMahon** [comment]
@dankohn to review, update, and approve "Rules for Members to contact speakers bureau members".

Once approved, Chris can start working on functionality.

Due date for functionality: August 30.

**Comment by KimMcMahon** [comment]
@cjyabraham Dan approved the Rules for Members to contact speakers bureau when he approved the document. Please proceed with the next steps.

**Comment by cjyabraham** [comment]
This may be the simplest and quickest user story that achieves this functionality:

1. Member filters the list of speakers
2. If the resulting set of speakers is less than, say, 50, we expose a link/button: "Email selected speakers"
3. If the member clicks that button, it pops open their email client with an email addressed to speakers in the set 
4. The member fills in the subject and body of the email and presses send

We could have some informational text explaining to members how they can access this link/button: "as a service to our members, when you are logged in and filter speakers to less than 50..." and also the spirit of this functionality: "to help you contact people interested in speaking at an event...".

Any thoughts?  If we go forward with this, are we fine allowing members to discover the emails of other members?  Or is there a reason we'd want to obfuscate them?

**Comment by dankohn** [comment]
I love simple, but unfortunately, this proposal encourages abuse. With 500 members, someone will decide to fetch all of the email addresses (50 at a time) in order to create a list of influencers.

Instead, we need to have a form that allows logged in users to send a message to a subset of users, and have that actually send email, not use a private messaging service.

**Comment by cjyabraham** [comment]
Ok, so how about this?

1. Member filters the list of speakers
2. If the resulting set of speakers is less than, say, 50, we expose a link/button: "Email selected speakers"
3. If the member clicks that button, it goes to a form where they fill in subject and message.  The form will likely be a Gravity form with validation, spam control, etc.
4. On send, the form takes the filter parameters and generates a list of email addresses from the resulting speakers and sends email to them.  It also notifies an admin that email has been sent.

We could leverage the Gravity Forms infrastructure for much of this and would need to capture the form submission action to send the actual email.

**Comment by dankohn** [comment]
Sounds good. If you select more than 50, it should add a note saying that
you can only email 50 or less. All emails send should cc a private mailing
list that we can monitor to look for bad behavior.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
Ok, I'll write up a new issue for Diego that looks like below.  Let me know if ok.  Separately, @KimMcMahon @dankohn @cjyabraham will need to work on messaging around this so members are aware they can do this.  One question: is it clear to members how to login to the site?  Here's the issue for Diego's team:

**Members can email filtered search results of speakers**

Add a button to [the Speaker's Directory](https://www.cncf.io/speakers/) below the filters that says "Email Matching Speakers".  This button only shows when someone is logged in.  It is visible but greyed out unless 50 or fewer speakers are being displayed.  When it is greyed out there's a tooltip that shows on hover: "Bulk email only available for sets of 50 or fewer speakers".

When a member does click on the button, it takes them to a new page with a gravity form with these fields:
- Name (pre-populated with the member WordPress name)
- Email (pre-populated with the member WordPress email)
- Subject (required)
- Message (required)
- CAPTCHA

The form should be a regular gravity form with AJAX field validation etc.  When the member submits the form, an action is implemented to send an email to all the speakers that meet the filter parameters on the previous page.  The entry will also be stored in Gravity forms archives and send notifications to admins etc.  At no time should the emails of the speakers be discoverable by the member.

**Comment by cjyabraham** [comment]
Ok.  Clean issue created for Diego at #138.  Closing this one now.
