### ISSUE TITLE
Add the Language filter for Speakers' page

### ISSUE THREAD

**Issue by deigolocco** [cncf/wordpress-site#111]

**Comment by rodmeurer** [comment]
@cjyabraham added language filtering:
https://fz-111-cncf.pantheonsite.io/speakers/

**Comment by KimMcMahon** [comment]
I did some testing - works great.

This page is looking really good!

**Comment by cjyabraham** [comment]
@rodmeurer how will this look when the "Self-Identification" filter appears and what are the rules governing when that filter appears?

**Comment by rodmeurer** [comment]
@cjyabraham We haven't worked on it yet, but it will be minor adjustments to fit the fifth filter. Would you like us to test and tweak this before you deploy with the language filter or can we go back to this later after issue # 110 which is a priority for the week?

The rules when the filter appears follow the same pattern as the other filters, the quantities will be displayed according to the options that are selected in the other filters. It is hidden because there is no data for it yet.

**Comment by cjyabraham** [comment]
@rodmeurer cool.  No, no need to worry about the "Self-Identification" filter for now.  I was just concerned that it might appear automatically once people start filling out that field.  If not, then we can leave it for now.

I have deployed this branch.

**Comment by rodmeurer** [comment]
@cjyabraham I asked to Danilo to test it locally and the filter automatically appears if you fill the self-identification field.  So, we'll have to work on this to see how it fit in different displays and devices and adjust it.

![image](https://user-images.githubusercontent.com/54405402/66128892-2abf2a00-e5c5-11e9-9f76-73373ff75144.png)

**Comment by cjyabraham** [comment]
Ah.  Can we get a fix for that quickly then so that we're not surprised with it appearing and make sure it looks good?  Or, for now, we can just deactivate it?

**Comment by cjyabraham** [comment]
Thinking about it, I think it would be best to just deactivate it for now until we get a critical amount of data to make it useful to people.  Can you do that @rodmeurer ?

**Comment by rodmeurer** [comment]
Yes @cjyabraham , already asked to Danilo to deactivate it for now. I'll let you know when it's ready to deploy again.

**Comment by rodmeurer** [comment]
@cjyabraham done, the filter will not be displayed. It's done in this same branch.

https://fz-111-cncf.pantheonsite.io/speakers/

**Comment by cjyabraham** [comment]
deployed
