### ISSUE TITLE
Require a photo to be listed in the speakers directory

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#112]
In order to be listed in the [speakers bureau directory](https://www.cncf.io/speakers/), a speaker must have a photo.  This can either be a photo they upload or a gravatar (having both options may not be technically feasible but please check).

If it's not possible to check for a gravatar to meet this requirement, then we could turn off gravatars entirely for the speakers bureau.  There's an option for this in the [plugin settings](https://www.cncf.io/wp-admin/admin.php?page=um_options&section=users).

**Comment by deigolocco** [comment]
It's done @cjyabraham https://fz-112-cncf.pantheonsite.io/speakers/

Unfortunately is not possible to check the gravatar, because always return an image. So we disabled the plugin's option as you suggested.

**Comment by cjyabraham** [comment]
This is deployed.  And I have turned off gravatars.
