### ISSUE TITLE
Update displaying message

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#114]
https://www.cncf.io/speakers/ says "Displaying 94 speakers". Please change to "Displaying 27 speakers out of 94 matching".

**Comment by rodmeurer** [comment]
@dankohn adjusted as you asked.

https://fz-114-cncf.pantheonsite.io/speakers/

**Comment by dankohn** [comment]
But on https://fz-114-cncf.pantheonsite.io/speakers/?cncf_expertise=CNI&_lc=cncf_expertise it should say "3 out of 3 matching".

**Comment by rodmeurer** [comment]
Right @dankohn, just see it also. We'll fix that.

**Comment by rodmeurer** [comment]
@dankohn fixed!

https://fz-114-cncf.pantheonsite.io/speakers/?cncf_expertise=CNI&_lc=cncf_expertise

**Comment by rodmeurer** [comment]
Fixed @dankohn , made several tests and I think it's all ok now.

**Comment by dankohn** [comment]
LGTM

**Comment by cjyabraham** [comment]
I'm happy to deploy this but I wonder if we could improve the language here.  

When the user first comes to [the page](https://fz-114-cncf.pantheonsite.io/speakers/), before they set the filters at all, the would see  "Displaying 27 speakers out of 93 matching".  Wouldn't it be better if it read "Displaying 27 out of 93 total speakers"?

Once filters have been set, then we could say "Displaying x out of y matching speakers".

If there is no pagination (i.e. if x==y), then it could say just "Displaying x matching speakers"

Any thoughts @dankohn?

**Comment by dankohn** [comment]
Those changes sound good.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
@rodmeurer can you implement please?

**Comment by rodmeurer** [comment]
@cjyabraham ok

**Comment by rodmeurer** [comment]
@cjyabraham up to date!

**Comment by cjyabraham** [comment]
deployed

**Comment by cjyabraham** [comment]
After discussions on Slack, it was decided to make this consistent with the Case Studies, Event's We're At and Webinars displaying messages:
- unfiltered view: "Displaying x speakers"
- filtered view: "Displaying y of x speakers"
