### ISSUE TITLE
2 column mobile landscape view

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#115]
Instead of 1 column now.

![image](https://user-images.githubusercontent.com/3083270/66074068-5b9c5200-e526-11e9-9de0-9fc40b43acba.png)

**Comment by rodmeurer** [comment]
@dankohn done with two column on landscape view

https://fz-115-cncf.pantheonsite.io/speakers/

**Comment by cjyabraham** [comment]
LGTM.  @dankohn ?

**Comment by dankohn** [comment]
LGTM

**Comment by cjyabraham** [comment]
deployed
