### ISSUE TITLE
Deactivate the old Events page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#116]
Can we archive, deactivate, or delete the old [Events](https://www.cncf.io/events/) page and re-direct to the [webinars](https://www.cncf.io/webinars/) page?

**Comment by KimMcMahon** [comment]
The redirect is important because a Google search has our old pages as the top results. :(
![image](https://user-images.githubusercontent.com/29307455/66132349-26d5dc80-e5b2-11e9-959a-cd7e843a1173.png)

**Comment by rodmeurer** [comment]
@cjyabraham we will do this configuration/redirect here, ok?

**Comment by KimMcMahon** [comment]
Can someone do these items too? To help with the Google search results?
Submit the updated sitemap to Google

Or do we have a plugin in wordpress that allows us to mark a page or section "search exclude"?

**Comment by dankohn** [comment]
Redirects are better than excluding from search because they preserve the link juice. I just manually added the sitemap to https://search.google.com/u/1/search-console/sitemaps?resource_id=https%3A%2F%2Fwww.cncf.io%2F&hl=en and it will now automatically re-fetch daily.

**Comment by rodmeurer** [comment]
@cjyabraham we did the redirect configuration from /events to /webinars.

**Comment by cjyabraham** [comment]
Looks good.  Thanks.
