### ISSUE TITLE
Menu bar doubles in size when scrolling on Speaker Bureau page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#117]
This occured on Safari. I did not test on Chrome.

When I scroll down my speakers bureau profile page and then come back to the top of the page, the menu gets larger. I can’t make it narrower again unless I reload the page.

<img width="1440" alt="Screen Shot 2019-10-03 at 7 31 17 AM" src="https://user-images.githubusercontent.com/29307455/66154583-0a01cf00-e5db-11e9-8035-14cdce0437e5.png">

**Comment by cjyabraham** [comment]
I am able to reproduce this in Safari but not Chrome.  It seems to happen on [any profile page](https://www.cncf.io/speaker/randy.abernethy/) when the browser is at a particular width (which is narrower than my screen).  This should probably be fixed but I don't see it as being high priority.

**Comment by KimMcMahon** [comment]
Thanks Chris and agree.

**Comment by deigolocco** [comment]
guys this was fixed during the issue 56 implementation https://fz-56-cncf.pantheonsite.io/speaker/janakiramm/

**Comment by cjyabraham** [comment]
I can no longer duplicate this issue so assume it is fixed.  @KimMcMahon feel free to reopen if it's still a problem for you.
