### ISSUE TITLE
Menu updates to cncf.io

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#120]
Rearranging and addition of new menu items.

Menus affected 
About
Projects
People
Community
Newsroom

For items that are moving from one high level menu to another, please put redirects in place for any links to the old location:
Trademark
End User Case Studies

The changes are outlined in the bullets. There is a table with the new menu in the [Menu Update document ](https://docs.google.com/document/d/1W5YH0fms_w_vycZH0toBbrKN8F_nya9O9nrXLIAy0mA/edit?usp=sharing)

Blocked pending creation of the new Telecom User Group & Cloud native Network Functions (CNFs) page

**Comment by alexcontini** [comment]
@KimMcMahon I have made all the updates: https://www.cncf.io/ besides the addition of the Telecom User Group & Cloud native Network Functions (CNFs) page, I can't seem to find the page or link, let me know when you have a chance and I will add!

**Comment by cjyabraham** [comment]
@KimMcMahon is this issue still active?  If not, please close.

**Comment by KimMcMahon** [comment]
@cjyabraham Yes. Until the new Telecom page is built. #145

**Comment by KimMcMahon** [comment]
Please move the TUF menu item to the location noted in the [Menu Update ](https://docs.google.com/document/d/1W5YH0fms_w_vycZH0toBbrKN8F_nya9O9nrXLIAy0mA/edit#heading=h.5jfz35magu6v)document.
