### ISSUE TITLE
Add Forum Bengaluru and Delhi to cncf.io

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#122]
Hi Alex, 
Can you create the graphic and add the two new K8s Forum's to https://www.cncf.io/community/kubecon-cloudnativecon-events/

Bengaluru
https://events19.linuxfoundation.org/events/kubernetes-forum-bengaluru-2019/

Delhi
https://events19.linuxfoundation.org/events/kubernetes-forum-delhi-2019/

**Comment by alexcontini** [comment]
@KimMcMahon this has been updated: https://www.cncf.io/community/kubecon-cloudnativecon-events/

**Comment by KimMcMahon** [comment]
Thanks @alexcontini!
