### ISSUE TITLE
Split "Areas of Expertise" field into two new fields "Project" and "Expertise"

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#125]
Split the current "Areas of Expertise" field into two new fields "Project" and "Expertise".

Steps:
- [x] provide a mapping of data to show how our current "Areas of Expertise" data should map to data in the two new fields (Kim) 
- [x] create the two fields (Chris) 
- [x] migrate the current "Areas of Expertise" data into these two new fields (Chris)
- [x] remove current expertise filter and add both of these new fields as filters on the speaker's bureau search (Diego)
- [x] update search results so that we use the new expertise field (Diego)

**Comment by KimMcMahon** [comment]
@deigolocco 

Instead of Projects and Expertise, can you show a view of "All areas of expertise" and use these items as a choice? I know we discussed this is long for a drop down (when we did webinars), but I would like to see how it looks.

Application & Development (includes Brigade, Helm & Telepresence)
Case studies
CI/CD
Community
Customizing & Extending Kubernetes
Machine Learning & Data
Networking (includes KubeEdge, NATS, CoreDNS, CNI, gRPC, & Network Service Mesh)
Observability (includes Prometheus, Jaeger, Fluentd, Cortex, OpenTelementry, Thanos, & OpenTracing)
Operations
Performance
Runtimes (includes containerd & CRI-O)
Security, Identity & Policy (includes Notary, OPA, SPIFFE/SPIRE, and TUF)
Serverless (includes CloudEvents)
Service Mesh (includes Envoy, & Linkerd)
Storage (includes Vitess, OpenEBS & Rook)

**Comment by KimMcMahon** [comment]
Mapping

<current category> --> Project category --> Expertise category

CNI --> CNI --> Networking
Cloud Events --> none --> Serverless
Community --> none --> Community
CoreDNS --> CoreDNS --> Networking
Envoy --> Envoy --> Service Mesh
Fluentd --> Fluentd --> Observability
Helm --> Helm --> Application and Development
Jaeger --> Jaeger --> Observability
Kubernetes --> Kubernetes --> none
Linkerd --> Linkerd --> Service Mesh
NATS --> NATS --> Networking
Networking --> none --> Networking
Open Policy Agent --> Open Policy Agent --> Security, Identity, and Policy
OpenTracing --> OpenTracing --> Observability
Orchestration --> Kubernetes --> none
Prometheus --> Prometheus --> Observability
Rook --> Rook --> Storage
Spiffe --> none --> Security, Identity, and Policy
Spire --> none --> Security, Identity, and Policy
Telepresence --> none --> Application and Development
Vitess --> Vitess --> Storage
Containerd --> containerd --> Runtimes
gRPC --> gRPC --> Networking
rkt --> none --> Application and Development


Cloud Platforms - remove and do not map.

**Comment by rodmeurer** [comment]
Ok @KimMcMahon , understood. We'll wait for Chris to create the two fields and export the current data, so we can implement the filters.

**Comment by cjyabraham** [comment]
@rodmeurer, @deigolocco  can you update the code to hide the current "Areas of expertise" filter from the search?

**Comment by cjyabraham** [comment]
Ok.  My part is done.  I've migrated all the data into two new fields.  I've also updated both the [registration form](https://www.cncf.io/speakers/register/) and the [profiles](https://www.cncf.io/speaker/raravena80/) to use these new fields.  Assigning over to Diego and team...

**Comment by deigolocco** [comment]
@KimMcMahon please lets us know, when you have a chance, what we need to put in place of the `Areas of Expertise` inside the card
![Captura de tela de 2019-10-15 11-31-39](https://user-images.githubusercontent.com/5631313/66871320-c6fc1000-ef79-11e9-951c-527c55217e01.png)

**Comment by KimMcMahon** [comment]
Sorry @deigolocco for the delay.
Remove Areas of Expertise from the profile tiles.

**Comment by deigolocco** [comment]
@KimMcMahon informations about "Project" and "Expertise" should be visible inside the card?

**Comment by KimMcMahon** [comment]
@deigolocco Project and Expertise is NOT visible from inside the card. The red area you marked in your image should be removed.

**Comment by deigolocco** [comment]
done https://fz-125-cncf.pantheonsite.io/speakers/

**Comment by cjyabraham** [comment]
This is deployed.
