### ISSUE TITLE
Provide HN jobs feeds

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#127]
https://support.jobboard.io/docs/setting-up-3rd-party-xml-job-imports#section-available-fields

Set up a parsing engine that provides XML to the CNCF jobs site in the format above based on parsing news.ycombinator.com. If remote jobs specify the headquarters location, include them and ensure Remote is in the header. If a job has 2 locations, just include the first one. If you can't successfully parse, just skip.

**Comment by jordinl83** [comment]
@dankohn What keywords should it match? Kubernetes, k8s, anything else?

**Comment by dankohn** [comment]
Just those two to start, please.
