### ISSUE TITLE
Change Speaker's Bureau filter text

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#128]
Change the text that says "All certifications" to say "All CNCF Affiliations" on the filter.

**Comment by deigolocco** [comment]
we did together issue 124 - https://fz-124-cncf.pantheonsite.io/speakers/

**Comment by cjyabraham** [comment]
Can you make "Affiliations" be lowercase "affiliations" so that it matches the format of the other filters.  Sorry to have given you the uppercase originally.

**Comment by deigolocco** [comment]
np @cjyabraham, it's adjusted

**Comment by cjyabraham** [comment]
looks like this was deployed when I deployed #125.
