### ISSUE TITLE
Create graphic for Kubernetes Forum Delhi and Bangaluru

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#129]
For Events we'll be at. Use the Kubernetes Forum branding.

**Comment by pablodelarocha** [comment]
![delhi](https://user-images.githubusercontent.com/54405572/66773739-1701a680-ee96-11e9-95cb-02a05d387c53.jpg)
![bengaluru](https://user-images.githubusercontent.com/54405572/66773740-179a3d00-ee96-11e9-94b5-a463a3e5c950.jpg)
![bengaluru_squared](https://user-images.githubusercontent.com/54405572/66773742-179a3d00-ee96-11e9-90d4-09c1da37b8fc.jpg)
![dehli_squared](https://user-images.githubusercontent.com/54405572/66773744-1832d380-ee96-11e9-8a6f-8d299fc31ebd.jpg)
Sure @KimMcMahon here's all 4 banners.

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha
