### ISSUE TITLE
Add Chinese language case studies to cncf.io

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#131]
- [x] Update the menu. Add an option for Chinese language case studies under the End User Case Study menu item.

- [x] Create a page for the Chinese case studies, exactly as the English case studies. Including tiles.

- [x] No filtering on the Chinese language case study page (at this time)

- [x] Kim: Translate the English case study page content to Chinese.

- [ ] Kim or Julie: Upload the case studies to the new Chinese language page. 

- [ ] Kim / Alex - are the graphical versions created? Or do we need to create them?

Folder for Google Doc of case studies
https://drive.google.com/drive/u/0/folders/1ycEKs3ThS4Cja7hzye8uQc6nC2dyTkj4

**Comment by KimMcMahon** [comment]
[Document](https://docs.google.com/document/d/1JpR4nVberj6Yq-Ce2H9admaFEOclwR8pACAGzSf52iY/edit) with the translated text

**Comment by cjyabraham** [comment]
@KimMcMahon, @deigolocco and I just discussed this.  We're trying to figure out the best way to build this so want to make sure we're understand the vision for this correctly.

Are we correct in assuming that this list of Chinese case studies will be separate from the English case studies?  They'll be on their own page, own url, and won't be related to the English case studies in any way now or in the future?

Or are the Chinese case studies ones in which we'll have both an English and Chinese version displayed on the same page (as you have in [those google docs](https://drive.google.com/drive/u/0/folders/1ycEKs3ThS4Cja7hzye8uQc6nC2dyTkj4)) so we'd want to expose the case studies on both an English and Chinese case studies directory?

**Comment by dankohn** [comment]
Yes, the plan is to have parallel pages for the Chinese. So, there's be a separate menu item saying "Case Studies" in Chinese, and each of the case studies there would be separate.

While theoretically, we may decide to post more parts of our site in Chinese, it's unlikely for the next year or two. This is the only thing we want to translate right now.

**Comment by KimMcMahon** [comment]
Adding: Case Study template for the China case studies. @cjyabraham please prioritize this. I can share a translated case study as part of a campaign without the web page complete.

**Comment by deigolocco** [comment]
@KimMcMahon created
https://fz-131-cncf.pantheonsite.io/newsroom/case-studies-cn/
You can add more cases [here](https://fz-131-cncf.pantheonsite.io/wp-admin/edit.php?post_type=case_study_cn)
<img width="161" alt="Captura de Tela 2019-10-25 às 16 04 53" src="https://user-images.githubusercontent.com/5631313/67597696-2f997880-f742-11e9-8eda-d61f82721f60.png">
I just cloned one from the english cases
Please review page/menu labels, and let me know if I need to do any adjustment

**Comment by cjyabraham** [comment]
@deigolocco I believe you can use the [same taxonomy of projects](https://fz-131-cncf.pantheonsite.io/wp-admin/edit-tags.php?taxonomy=cstudies_project&post_type=case_study) for the Chinese case studies that are used on the English case studies.  

@dankohn do Cloud Types (i.e. hybrid, private, public) and Product Type (i.e. distribution, hosted, installer) need translating or can we use the english words?  I assume Countries, Challenges (e.g. Automation, Availability, DevOps...), Industries (e.g. AdTech, AI, Automotive...) *should* be translated?

**Comment by KimMcMahon** [comment]
@cjyabraham @deigolocco

All I need (first three items in the issue description:

- Update the menu. Add an option for Chinese language case studies under the End User Case Study menu item.

- Create a page for the Chinese case studies, exactly as the English case studies. Including tiles.

- No filtering on the Chinese language case study page (at this time). **So - we don't need to do anything with the filtering or translating the filters. This is a future issue.**


Added is creating a template for the Chinese case studies. Alex Contini has some concern about using the english template (it seem like some type of backend issue).

**Comment by deigolocco** [comment]
@KimMcMahon they are done [here](https://fz-131-cncf.pantheonsite.io/newsroom/case-studies-cn/)

@alexcontini could you tell me which issues you have with case studies? Please feel free to ping at hangouts or slack.

@cjyabraham if some moment the taxonomies will be translate I don't recommend. Please confirm if should I use the same for all of them.

**Comment by KimMcMahon** [comment]
@deigolocco Please add the Chinese text to this page - above the English text. The translated text is in the Google Doc referenced above.

Can you tell me what "taxonomies" are. It sounds like filtering to me - and I don't want filtering at this time.

**Comment by cjyabraham** [comment]
@KimMcMahon  we know you don't want filtering, however we use taxonomies to describe the case studies and add some structure to the data.  The taxonomies populate the right column on [each case study page](https://www.cncf.io/case-study/adform_prometheus/).  That's why [I was asking @dankohn](https://github.com/cncf/wordpress-site/issues/131#issuecomment-546576771) whether we could use English words for these (and so can re-use the taxonomies used for English case studies) or should translate and create separate Chinese taxonomies.  Any thoughts on that?

**Comment by dankohn** [comment]
English is fine.

**Comment by deigolocco** [comment]
@KimMcMahon Chinese copy added
https://fz-131-cncf.pantheonsite.io/newsroom/case-studies-cn/
<img width="239" alt="Captura de Tela 2019-10-28 às 10 11 31" src="https://user-images.githubusercontent.com/5631313/67681154-82a24400-f96b-11e9-8fa9-2cc4eecf0be0.png">

@cjyabraham using same taxonomies from english case studies

**Comment by KimMcMahon** [comment]
@deigolocco Looks good. Thank you.

@cjyabraham If this is good for you, please deploy.

Thanks!

**Comment by cjyabraham** [comment]
@deigolocco there was a small problem but I made a quick fix so that I could deploy:

```
diff --git a/wp-content/themes/salient-child/search-filter/44394.php b/wp-content/themes/salient-child/search-filter/44394.php
index c5c8648..47c729f 100644
--- a/wp-content/themes/salient-child/search-filter/44394.php
+++ b/wp-content/themes/salient-child/search-filter/44394.php
@@ -115,7 +115,7 @@ if ( $query->have_posts() )
 			$i = 0;
 		}
 		$i++;
-		$value = get_post_meta( $post->ID, 'cstudies_type', true );
+		$value = get_post_meta( $post->ID, 'cstudies_type_cn', true );
 		?>
 		<div class="col-sm-3" style="background-image: url(<?php the_post_thumbnail_url(); ?>)">
 			<h2><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h2>
```

@KimMcMahon this is deployed so you can start adding Chinese case studies then we can link the directory in to the menu.

**Comment by deigolocco** [comment]
thank you @cjyabraham! 

@KimMcMahon I did the necessary adjustments after deploy, here is the page https://www.cncf.io/newsroom/case-studies-cn/

I cloned an english case study as chinese, so you'll have a template to use.
Please let me know if any adjustment is necessary.

**Comment by cjyabraham** [comment]
Assigning to Kim since the remaining items are for her to do.

**Comment by KimMcMahon** [comment]
Update:
Julie is translating Pinterest so we can use it for our planned China campaign.

I have asked Julie to work with Alex to get the existing translated case studies into the template.

Once we have them in the template, Donald has read them, we'll upload to the website and make the page live.

**Comment by alexcontini** [comment]
@KimMcMahon @deigolocco 
I have put together the Chinese version of Pinterest here - https://www.cncf.io/case-study-cn/pinterest/ - but I am seeing that it's not showing up on the landing page - https://www.cncf.io/newsroom/case-studies-cn/ - do you know why this might be happening?

**Comment by KimMcMahon** [comment]
@alexcontini LGTM. Do you have others to upload to the website? I'd like to make the menu item live with case studies. Can you let me know please?

Thank you!

**Comment by alexcontini** [comment]
@KimMcMahon sorry I didn't mean to close and reopen!

I see the links to the docs above. I will have those all done by the end of the week for sure

**Comment by alexcontini** [comment]
@KimMcMahon I have finished putting together all of the case studies that we have translated and they are all on this page - https://www.cncf.io/newsroom/case-studies-cn/ - Let me know if these look good to you and I will make the page live!

**Comment by dankohn** [comment]
We need to change `Read the Case Study` to Chinese

**Comment by cjyabraham** [comment]
There are quite a few words in English [here](https://www.cncf.io/case-study-cn/ant-financial/) as well.  Can we defer doing this until the new site launch or do you want it done now @dankohn ?

**Comment by dankohn** [comment]
Now, please 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by cjyabraham** [comment]
Can someone provide the translation?  And then I'll get the template updated.

**Comment by KimMcMahon** [comment]
@cjyabraham Please make the menu item for the Chinese language case studies and the individual case studies live. I'll have Julie get the translations and update the website.

Thank you!

**Comment by cjyabraham** [comment]
@alexcontini can you make the page live please?

@KimMcMahon translating the remaining English text will require a code change.  If Julie can provide those then I can update the code.

**Comment by jkld11** [comment]
@cjyabraham @deigolocco The translations of the words can be found here: https://docs.google.com/document/d/15Xt_OeNv7l_BEKZtrxzV1U1lffvrgOjr1GAP8XtKcvQ/edit?usp=sharing Please let me know if you have any questions. Thanks!

**Comment by donaldliu** [comment]
@jkld11 I made comments on your online doc.  Thanks.

**Comment by cjyabraham** [comment]
I've created #157 to have @deigolocco add the translations to the templates.

**Comment by cjyabraham** [comment]
@KimMcMahon is this issue complete now?

**Comment by KimMcMahon** [comment]
Yes @cjyabraham
