### ISSUE TITLE
Remove google fonts from cncf.io

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#132]
They don't work in China so we need to replace them with something else.

**Comment by dankohn** [comment]
We can use the Google Fonts but they need to be hosted on our site. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by deigolocco** [comment]
yes @dankohn. We mapped where these fonts are being requested.
Gravity Forms is calling the font josephine sans and Youtube roboto.
For GF was necessary disable the css and substitute the style directly at the theme(that's what I'm doing now, not done yet).
Youtube will be necessary to do the same as we did for events. I'll need your help for this. For each Youtube video we'll need to have a substitute at Youku and a new token for ipinfo API.

**Comment by deigolocco** [comment]
cool! @dankohn!
But Gutembergue is not being used at website yet. Anyway, I'll finish GF for now.
Thanks

**Comment by deigolocco** [comment]
Gravity Forms is finished, is not requesting google fonts anymore.
Now, only Youtube videos are calling google fonts.
There's another situation that I don't if is a problem or not, at this [page](https://www.cncf.io/about/members/) external fonts are being called
<img width="432" alt="Captura de Tela 2019-10-21 às 10 39 29" src="https://user-images.githubusercontent.com/5631313/67210484-8f64ec00-f3ef-11e9-823a-e177c3b90d70.png">
I don't think this is a problem, but if is, pease let me know

**Comment by dankohn** [comment]
No, calling fonts from landscape.cncf.io isn't a problem. We host them locally to avoid relying on Google, so things work in China.

We won't be able to offer qq videos for all of our webinars yet, but could you please create a new issue to have the video at the bottom of the homepage play on qq when the person is in China.

**Comment by cjyabraham** [comment]
#134 created for the video task

**Comment by deigolocco** [comment]
I did through manager, so it's live

**Comment by dankohn** [comment]
I did a hard reload and still see in view source:
```
<link rel='stylesheet' id='wp-editor-font-css'  href='https://fonts.googleapis.com/css?family=Noto+Serif%3A400%2C400i%2C700%2C700i&#038;ver=5.1.1.1571663439' type='text/css' media='all' />
 ```

**Comment by deigolocco** [comment]
Inspecting the page Network/Font, you can observe the font is not being requested
<img width="1329" alt="Captura de Tela 2019-10-21 às 15 17 01" src="https://user-images.githubusercontent.com/5631313/67231981-c3073c80-f416-11e9-94fd-ab040e106461.png">
But I'll work to remove this from the head

**Comment by cjyabraham** [comment]
deployed
