### ISSUE TITLE
Make video at bottom of homepage play the qq video for users in China

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#134]
Use the main concepts from [this block](https://github.com/cncf/china-video-block)

**Comment by deigolocco** [comment]
@dankohn the Gutemberg [plugin](https://github.com/cncf/china-video-block) uses the same logic and API that we used for events.
<img width="980" alt="Captura de Tela 2019-10-21 às 13 27 14" src="https://user-images.githubusercontent.com/5631313/67224173-078adc00-f407-11e9-9f53-4bd62b172967.png">
will be great to use it after CNCF rebuilt, having Gutemberg. 
For now we need implement manually for homepage.

Do we already have the qq video?

**Comment by deigolocco** [comment]
it's done https://fz-132-cncf.pantheonsite.io/

**Comment by dankohn** [comment]
Tally in Beijing confirms that the qq video plays correctly.

**Comment by deigolocco** [comment]
great!

**Comment by cjyabraham** [comment]
deployed, and I've asked Tally for confirmation it works on the live site.

**Comment by cjyabraham** [comment]
Tally has confirmed that it is working.
