### ISSUE TITLE
Replace 404 image

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#135]
You replaced the Phippy 404 SVG with a PNG to avoid it becoming distorted on small screens. The attached SVG should do the same because it includes a viewbox to keep the ratio constant. Please use as the 404 image and confirm it looks good on small screens.

[404-phippy.svg.zip](https://github.com/cncf/wordpress-site/files/3758689/404-phippy.svg.zip)

**Comment by deigolocco** [comment]
replaced https://fuerza-cncf.pantheonsite.io/qowiuhehuqwh

**Comment by dankohn** [comment]
LGTM, thanks.

**Comment by cjyabraham** [comment]
The iPhone X views seem problematic.  Can these be fixed:
- portrait view - too much white space so you have to scroll quite a lot
- landscape view - image too small and "back home" button overlaps with the footer

<img width="356" alt="Screen Shot 2019-10-24 at 11 25 42 AM" src="https://user-images.githubusercontent.com/463160/67453634-75c2df00-f651-11e9-9aab-c3ec4025a1a1.png">
<img width="742" alt="Screen Shot 2019-10-24 at 11 25 29 AM" src="https://user-images.githubusercontent.com/463160/67453635-765b7580-f651-11e9-8604-698730fc0863.png">

**Comment by deigolocco** [comment]
adjusted @cjyabraham

**Comment by cjyabraham** [comment]
deployed
