### ISSUE TITLE
Members can email filtered search results of speakers

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#138]
Add a button to [the Speaker's Directory](https://www.cncf.io/speakers/) below the filters that says "Email Matching Speakers".  This button only shows when someone is logged in and has the role member, ambassador or maintainer.  It is visible but greyed out unless 50 or fewer speakers are being displayed.  When it is greyed out there's a tooltip that shows on hover: "Bulk email only available for sets of 50 or fewer speakers".

When a member does click on the button, it takes them to a new page with a gravity form with these fields:
- Name (pre-populated with the member WordPress name)
- Email (pre-populated with the member WordPress email)
- Subject (required)
- Message (required)
- Event start date (with a date picker)
- Event end date (with a date picker, defaults to start date)
- We provide travel funding for speakers (dropdown: yes, no, case-by-case basis, not sure yet)
- Expected number of attendees (required)
- Main language of the conference (required; same dropdown as our language list)
- CAPTCHA

The form should be a regular gravity form with AJAX field validation etc.  When the member submits the form, an action is implemented to send an email to each of the speakers that meet the filter parameters on the previous page.  The entry will also be stored in Gravity forms archives and will send notifications to admins etc.  At no time should the emails of the speakers be discoverable by the member.

**Comment by cjyabraham** [comment]
FYI I investigated our email sending capacity with our current AWS mail server:
The limits are as follows:

"Max24HourSend": 50000.0,
"MaxSendRate": 14.0,  (that's 14/second)

"SentLast24Hours": 4469.0

So our current account should be sufficient for us to run this new feature.

**Comment by deigolocco** [comment]
thanks @cjyabraham, we finished https://fz-138-cncf.pantheonsite.io/speakers/
- The user only can see the button if is logged in
<img width="1327" alt="Captura de Tela 2019-10-30 às 17 20 01" src="https://user-images.githubusercontent.com/5631313/67895588-8e436580-fb39-11e9-8f29-38eacc5ed0ca.png">
- We are using A Gravity Form default, please let us know if you need something prettier
- For the Speakers field the user can remove or add speakers, at maximum of 50
<img width="1327" alt="Captura de Tela 2019-10-30 às 17 21 04" src="https://user-images.githubusercontent.com/5631313/67895872-09a51700-fb3a-11e9-973f-fab803d9672b.png">
- For the email template we are using the Gravity Forms one, please let us know if you need something prettier
- For now we are sending all emails for ourselves to test, everything working 
![Captura de tela de 2019-10-25 17-57-09](https://user-images.githubusercontent.com/5631313/67896092-6d2f4480-fb3a-11e9-94f7-ef836c72b9ad.png)

Please let us know the next steps

**Comment by cjyabraham** [comment]
Great.  It'll take some time to test this properly but I'll give you some feedback to start with:
- Can you make the greyed-out state of the button more greyed-out so that it's more obvious that the button is disabled?  Right now the button looks like just a normal button when disabled.
- Can you try putting the button over on the far-right and not have it push the "Displaying 79 matching speakers" down?
- Could you change the hover text on the disabled button to "Use the filters to reduce the number of matching speakers. You may email no more than 50 at a time. "
- Can you reduce the width of the "Expected number of attendees" field?

@dankohn do we want to allow for the list of speakers receiving the email to be edited and added to as Diego has it here?

**Comment by dankohn** [comment]
No need. We should just sent the email to the group selected.

**Comment by deigolocco** [comment]
@cjyabraham it's adjusted

**Comment by cjyabraham** [comment]
@deigolocco I think we need a title at the top of the form: "Email Speakers About Your Event"

Then you could use these field names to make them less ambiguous:
- Your Name
- Your Email
- Speakers to Email
- Email Subject
- Message
- Event Start Date
- Event End Date
- Will You Provide Travel Funding for Speakers
- Expected Number of Attendees at Event
- Main Language at Event
- CAPTCHA

@dankohn are you sure we don't want to allow the person to edit the list of speakers?  I'm concerned that the sender will want to send multiple emails to different sets of speakers and, likely, there will be speakers who will match more than once and receive multiple emails?  It could quickly become annoying for speakers.

**Comment by dankohn** [comment]
I'm OK with editing if you recommend it. I just don't want to expose email
addresses to the sender.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by deigolocco** [comment]
@cjyabraham we did the adjustments that we discussed on our call and I set the emails for you, so you can test the completed flow

**Comment by cjyabraham** [comment]
@deigolocco 
For the email form, can you change "Event start date" to "Event Start Date" and do the same for end date?

Once you send the message to the speakers, it gives this message: "Thanks for contacting us! We will get in touch with you shortly."  Can you change to: "Your message has been sent."  And show a link or button: "Back to Speakers Bureau"

Regarding the email that I got when sending this form:
- could you change the introductory text to be: "A CNCF Member has sent you a speaking request from the CNCF Speakers Bureau:"
- can you make the text in the email darker or black?
- could you make all the field names the same case as you have in the original form?  So change "Expected number of attendees" to "Expected Number of Attendees" etc.

**Comment by cjyabraham** [comment]
Additionally, we'd like to log each email to this email address for our admins to moderate: speakers-bureau-messages@lists.cncf.io
I don't think each individual email needs to be cc'd there, rather, it may make more sense to send one email for each group of speakers that receive an email.  In it you could list all speakers who received the email.

**Comment by dankohn** [comment]
No, we don't want to share speakers email with each other. So, if we can
send one email, they should be in the Bcc list. That implies that we want
to send one message to the archive where the speakers email (and the
archive address) are in the To line, and one where they're in the Bcc line.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
@dankohn , I'm not sure if I understand everything you say here but @deigolocco and I have already discussed that each speaker will receive their own email with just them in the to: line.  So there's no way that any speaker will know of any other speaker.

What I'm suggesting in my comment above is, as a log, have one final email going to the group archive list and, in the contents of that email, list out the speakers names that were sent emails.

Is that what you had in mind?

**Comment by dankohn** [comment]
Sounds good.

**Comment by rodmeurer** [comment]
@cjyabraham up to date! We set both emails for your gmail address, so you can test.

**Comment by cjyabraham** [comment]
Looking good.

Can you make it so that only users with the role Member or Administrator can see the button?

**Comment by rodmeurer** [comment]
Done @cjyabraham !

**Comment by cjyabraham** [comment]
@rodmeurer I created a test user and assigned him Member and Administrator roles but I can't get the button to show up for him at all.  See screenshot when he is currently an Administrator:

<img width="1315" alt="Screen Shot 2019-11-20 at 11 21 34 AM" src="https://user-images.githubusercontent.com/463160/69208942-fceb7000-0b87-11ea-93e7-2d36fdca24ef.png">

Also, if someone is not an Administrator but are logged in, can you make it so that the black bar at the top doesn't appear?

<img width="1436" alt="Screen Shot 2019-11-20 at 11 17 41 AM" src="https://user-images.githubusercontent.com/463160/69208961-11c80380-0b88-11ea-9731-1bd135e053c3.png">

**Comment by rodmeurer** [comment]
@cjyabraham fixed, it was a cache problem with the button. Removed the black bar also if the user is not Administrator.

**Comment by cjyabraham** [comment]
Ok @rodmeurer .  This is ready to deploy.  Can you set the email addresses to email the real speakers email and the archive email list?

**Comment by rodmeurer** [comment]
@cjyabraham we set up the emails and already configured the form in the live website. You must set a Google account for the CAPTCHA.

![image](https://user-images.githubusercontent.com/54405402/69724495-c7e89b80-10fa-11ea-9579-b4c779876b31.png)

![image](https://user-images.githubusercontent.com/54405402/69724522-d767e480-10fa-11ea-8ca0-e1d56595b9ec.png)

**Comment by cjyabraham** [comment]
Ok.  CAPTCHA is configured.  
Could you please fix merge conflicts and then I'll deploy?

**Comment by deigolocco** [comment]
fixed @cjyabraham

**Comment by cjyabraham** [comment]
deployed

**Comment by cjyabraham** [comment]
I have added a new speaker but it is not showing up in the "Speakers to Email" field on the form when I go to send an email.  This field needs to dynamically fill with new speakers as they get added.

**Comment by rodmeurer** [comment]
Fixed @cjyabraham, can you test it again at https://fz-138-cncf.pantheonsite.io/speakers please?

**Comment by cjyabraham** [comment]
thx
