### ISSUE TITLE
Add jobs site to cncf.io

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#14]
It would be nice to add a jobs site to cncf.io for employers to reach potential employees. As a member benefit, we could highlight CNCF members more prominently.

To populate the site during startup (and maybe forever) we can take the feed of Kubernetes jobs from Hacker News: https://hnrss.org/jobs?q=kubernetes+OR+K8s

There are multiple Wordpress plugins we could use or one of these white label services:

https://wpjobboard.net/
https://www.jobboard.io/features/
https://www.smartjobboard.com/pricing/

**Comment by KimMcMahon** [comment]
Host a job board on CNCF site.

Thoughts:
Populate with ads from HackerNews
Members can do ads
RSS feed

Kim and/or Chris Blum to work on this.

**Comment by cjyabraham** [comment]
I like jobboard.io though it looks like we'd need to go with their [enterprise](https://www.jobboard.io/pricing/) option if we want to import feeds from other job boards.  We'd save money in development but it would cost more to run per month.

If we want to integrate it with anything on cncf.io, like a member directory, we may need more flexibility in customizing.

Do you intend to monetize the board and make money off postings?  TechCrunch charges $249 to post a job for 30 days.  I remember we made quite a lot of money this way on [Streetsblog](http://jobs.streetsblog.org/) and Gothamschools (now [Chalkbeat](https://jobs.chalkbeat.org)).  I don't think the [Streetsblog board](http://jobs.streetsblog.org/) has changed since I set it up :P

**Comment by dankohn** [comment]
I don't want to directly monetize, but I'm looking for it to be an additional benefit of membership that members get a preferred listing (of some kind). That means that we need to track logins. Could you please get a quote to incorporate HN listings, and mention that we're a nonprofit.

**Comment by cjyabraham** [comment]
Actually, I was wrong, for jobboard.io it looks like the [Professional option](https://www.jobboard.io/pricing/) would be good enough as it allows up to 5 job feeds.  It's $349/month.  I don't think we'd need any of the Enterprise features initially.

**Comment by dankohn** [comment]
Great. Want to signup for a trial account? Big question is how we can administer users so as to show member listings as preferred. I’m fine with a manual process at first.

**Comment by dankohn** [comment]
Assigning to @christinevblum now that KCD is just about launched. You'll need to work closely with @cjyabraham to look at whether jobboard.io meets our needs, and to figure out the login options.

**Comment by dankohn** [comment]
It looks like we could just have employers set up accounts with Jobboards.io and then ping us via the MemberDesk to mark them as featured if they're a member. That's probably good enough to get started.

**Comment by christinevblum** [comment]
@cjyabraham how can I help? This sounds like a wonderful benefit for our members.

**Comment by cjyabraham** [comment]
I've setup a [test account here](https://cncf.jobboard.io).  And here is [the admin](https://cncf.jobboard.io/admin). 

@christinevblum I haven't had time to really do a thorough survey of all job board services.  If you have time, that might be worth doing before we get too far along with jobboard.io.

**Comment by cjyabraham** [comment]
I took a look at importing [HN jobs](https://hnrss.org/jobs?q=kubernetes+OR+K8s) but it seems that the RSS feed provided doesn't have a number of the [required fields](https://support.jobboard.io/docs/setting-up-3rd-party-xml-job-imports) such as company and location.  

In fact, the HN feed isn't really marked up with any job metadata.  It's just a generic RSS feed of content items and outbound links.  They link to job postings on the company sites that are hiring which are not standardized in any way.  This would even make scraping impossible.

Is there another site we could use to import jobs from?

**Comment by dankohn** [comment]
Can you get a parsed feed from https://whoishiring.io?

**Comment by cjyabraham** [comment]
I've started a [requirements doc](https://docs.google.com/document/d/1zfaajiOe5roDHHKL7goxroYpMpsVRkU9e7J5Li11Idc/edit?usp=sharing) for us all to edit in prep for our call with a jobboard.io representative.

**Comment by dankohn** [comment]
@jordinl83 can build a custom parser for us that converts Hacker News jobs into a feed. He had the following questions:

I think parsing location works reasonably well already…
But I see some issues with the format jobboard.io expects (https://support.jobboard.io/docs/setting-up-3rd-party-xml-job-imports#section-available-fields):
• Title: I might not be able to extract a job title from the post (see https://news.ycombinator.com/item?id=21151335) or there might be more than one (like https://news.ycombinator.com/item?id=21132453)
• Location: can it be remote? (like https://news.ycombinator.com/item?id=21128353) Does it allow multiple locations? (like https://news.ycombinator.com/item?id=21127421)
• Apply URL or Apply Email: I might not be able to get that like here https://news.ycombinator.com/item?id=21135442 or here https://news.ycombinator.com/item?id=21188095
On top of that, fetching posts that have Kubernetes in it might return some results that are not relevant, you can visit https://hnhiring.com/search?technologies=kubernetes.
There are different options around these issues, such as:
• Automatically try to guess all these fields and fill out any unknown information with some defaults.
• Automatically try to guess all these fields and discard jobs where we can’t guess all required info.
• Automatically try to guess all these fields but have an intermediate (manual) step where somebody reviews all the information, can add/remove details and can ignore jobs that don’t seem relevant. After reviewer approves jobs, these are visible in feed and jobboard.io can import them.
• Use a custom way to automatically embed jobs from news.ycombinator.com.
• Use a custom way to embed jobs from news.ycombinator.com, information will be automatically processed as much as possible, but somebody will have to review it before it’s posted to WP site.
Let me know which way you would like to go about this

**Comment by cjyabraham** [comment]
[I've requested LF setup our subdomain for this](https://jira.linuxfoundation.org/browse/WEB-392).

**Comment by cjyabraham** [comment]
Some things we need to do:
- [ ] setup analytics; we may want to link this with the cncf analytics account
- [ ] pick a theme
- [ ] write css to override with CNCF colors
- [ ] customize theme with images, logo, favicon etc.

**Comment by KimMcMahon** [comment]
@cjyabraham I'm getting caught up with this issue.

A couple of questions / comments:

- Why a different theme to 'override with CNCF colors'. I read this and assume this is to make it look different than the CNCF site? 

- Comment on the member posts and giving them a better location on the job site. Can we also add a badge or something to indicate a post from a member?

**Comment by cjyabraham** [comment]
@KimMcMahon 
The job board software has a number of different themes we can pick from.  Once we pick a theme, we can insert some CSS so that the theme uses CNCF colors.  I figure this would be good to brand it as close to CNCF as possible.

Members will be given a coupon code with which they can post a "featured" post which will be listed in prime locations on the board.  I don't think we can add a special badge but we can see.

**Comment by cjyabraham** [comment]
I'm starting a new clean issue focused on the launch.  Closing this ticket in favor of #133.
