### ISSUE TITLE
Change case studies path

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#140]
Please have the case studies live at https://www.cncf.io/newsroom/case-studies/ instead of https://www.cncf.io/projects/case-studies/ and have the old path redirect.

**Comment by cjyabraham** [comment]
done

**Comment by dankohn** [comment]
Please also update the link at the top of https://www.cncf.io/people/end-user-community/.

**Comment by cjyabraham** [comment]
done.
