### ISSUE TITLE
Develop process of designating members, ambassadors and maintainers in cncf.io

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#141]
This is needed for #138. 

from @dankohn :
"ambassadors and maintainers are intersecting but not a subset. I think we want to ask them to log in and then request via the new memberdesk to be upgraded to be able to send emails. It would be  a checkbox that Taylor could set. I'm open to more streamlined ideas but I don't think it's necessary."

**Comment by cjyabraham** [comment]
@dankohn someone has gone to some trouble to setup these roles within cncf.io:
_Editor + Gravity Forms (1) | Administrator (25) | Admin (15) | Member (13) | Editor (16) | Editor with Menu (4) | Editor with Salient (2) | Subscriber (154) | Speaker (256) | No role (1)_

As you can see, however, most aren't being used.  For the purposes of this email functionality, we could use the "Member" role that exists and could setup two new roles for Ambassadors and Maintainers.  Then Taylor would have to manually assign people to these roles as needed and remove those that no longer apply.  Does that work?

**Comment by dankohn** [comment]
@ccraigross Can you speak to how these rolls were set up?

I think just Member is fine, as some people are Member, Ambassador, and Maintainer, so what to select would be non-obvious, and their rights (to send emai) will be the same in all cases.

**Comment by ccraigross** [comment]
@dankohn - I can speak to the default roles but I am not sure who added the Member and Speaker roles - @cjyabraham? In any case, we can assign multiple roles to someone so perhaps we add an Send Email role along with Member?

**Comment by cjyabraham** [comment]
@ccraigross ok, I'll think about that.  I think "Send Email" is more of a capability that should be assigned to each of the roles: "Member", "Ambassador" and "Maintainer" but maybe I'm being too much of a purest here :)

**Comment by cjyabraham** [comment]
@dankohn any thoughts on this?

**Comment by dankohn** [comment]
I don't think we need to differentiate.

**Comment by cjyabraham** [comment]
Organizing thoughts around this [here](https://docs.google.com/document/d/1HUdcafXh-PX4CRG7dUKhbOhf9BaGsI5yGCE21BHOiyM/edit#).

**Comment by cjyabraham** [comment]
done
