### ISSUE TITLE
Mobile menu format broken

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#142]
Mobile menu is not filling the full width of the screen anymore.  Please fix.

<img width="314" alt="Screen Shot 2019-11-02 at 10 42 41 AM" src="https://user-images.githubusercontent.com/463160/68065551-8cf28280-fd5d-11e9-8b52-26017a2e97e5.png">

**Comment by cjyabraham** [comment]
It looks like this was the commit that broke things.  Any ideas @deigolocco:
```
commit b3fa34b2e7b9c68dcd1adfba1f9c769be66d984e
Merge: f76b4b059 fca4feeb2
Author: deigolocco <diego@fuerzastudio.com.br>
Date:   Wed Oct 30 08:38:00 2019 -0300

    merge conflict fix
```

**Comment by deigolocco** [comment]
adjusted @cjyabraham https://fz-142-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
This doesn't seem to work for me on mobile, both my physical Pixel 3a and [this Browserstack Samsung](https://drive.google.com/open?id=1kjwDW2hg3-SiPDhTphm0xnp1uZRbMPmP).  The menu expands when I click the hamburger but then immediately contracts to just a small bar.  Any ideas?

**Comment by rodmeurer** [comment]
@cjyabraham adjusted. We made tests for Pixel 3a, Pixel, Samsung S10, S7 and some more in Browser Stack. Can you test in your mobile please?

**Comment by cjyabraham** [comment]
Looks fine.  Can you resolve the merge conflicts please and then I'll deploy.

**Comment by deigolocco** [comment]
solved @cjyabraham

**Comment by cjyabraham** [comment]
The menu appears broken again.  Whatever you just did to resolve conflicts appears to be the original cause of this issue:
<img width="313" alt="Screen Shot 2019-11-08 at 1 33 03 PM" src="https://user-images.githubusercontent.com/463160/68454811-61bfd580-022c-11ea-9503-47f801836b08.png">

**Comment by cjyabraham** [comment]
@deigolocco, with respect to this issue and our work in general, would you please remind your team to both check that their branches can merge to master and thoroughly test their work before passing things to me to deploy?

**Comment by deigolocco** [comment]
you are right @cjyabraham, sorry for that. I did the merge, and was nothing at the code indicating possible problems, so I just did the merge and didn't double check. I'll do next time, my bad.

But the conflict is solved and the menu is tested, you can deploy this time.

**Comment by cjyabraham** [comment]
this is deployed
