### ISSUE TITLE
UTC time for the webinars is not correct for webinars in China

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#144]
I believe the UTC-X is static, not a calculation based on the time zone. We have 2 webinars in China that show UTC-8 when it should be UTC+8

**Comment by cjyabraham** [comment]
@KimMcMahon can you provide links to the webinars you want looking at?

**Comment by taylorwaggoner** [comment]
@cjyabraham 
https://www.cncf.io/webinars/gain-confidence-in-compliance-advanced-image-scanning-with-harbor-2/
https://www.cncf.io/webinars/network-traffic-management-in-cloud-native-application/

**Comment by deigolocco** [comment]
@KimMcMahon we did some adjustments
https://fz-144-cncf.pantheonsite.io/webinars/
https://fz-144-cncf.pantheonsite.io/webinars/gain-confidence-in-compliance-advanced-image-scanning-with-harbor-2/

if you add CST at time, will show UTC + 8
<img width="244" alt="Captura de Tela 2019-11-05 às 17 29 42" src="https://user-images.githubusercontent.com/5631313/68255026-dadfe280-000a-11ea-8269-3f7a94265d82.png">

**Comment by KimMcMahon** [comment]
Thank you @deigolocco. This looks good. Please implement and deploy.

**Comment by cjyabraham** [comment]
@deigolocco is this ready to deploy from your POV?  Let me know what you want me to do.

**Comment by deigolocco** [comment]
yes @cjyabraham, please deploy.

**Comment by cjyabraham** [comment]
this is deployed.
