### ISSUE TITLE
New page: Telecom User Group

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#145]
Page content in the [Google Doc](https://docs.google.com/document/d/1A_PVaDyQHFilM_RuW_XBmC-UDeLvXUtsGPwgwBLU8Cs/edit?usp=sharing)

- [ ] Page Design

- [ ] Populate with content

- [ ] Add to Community menu above Infrastructure Lab

**Comment by KimMcMahon** [comment]
@alexcontini Do you work have time to work on this page design (with KubeCon behind us!)?

**Comment by alexcontini** [comment]
@KimMcMahon sounds great! I can do this for sure. I have created some rough drafts for the page and they are below. Let me know any feedback when you have a chance!

![telecom-user-group-page-designs-04](https://user-images.githubusercontent.com/27962005/70072026-367a9d00-15c4-11ea-872c-335bea9e9eb6.jpg)
![telecom-user-group-page-designs-03](https://user-images.githubusercontent.com/27962005/70072027-37133380-15c4-11ea-8bc4-c7f7f55635a5.jpg)
![telecom-user-group-page-designs-02](https://user-images.githubusercontent.com/27962005/70072028-37133380-15c4-11ea-9d17-afac6ec6d109.jpg)
![telecom-user-group-page-designs-01](https://user-images.githubusercontent.com/27962005/70072029-37133380-15c4-11ea-8b99-2e43ee237729.jpg)

**Comment by KimMcMahon** [comment]
@alexcontini I like the second one for the top and the "learn more" from the 3rd one. Can you get that onto cncf.io and update the menu?

Thanks!

**Comment by alexcontini** [comment]
@KimMcMahon sounds good!

here is the page - https://www.cncf.io/community/telecom-user-group/ - it's not in the menu yet, just wanted to get your approval first

Let me know if it looks good and I will add to the menu

**Comment by dankohn** [comment]
Yes, please add to the menu.

**Comment by cjyabraham** [comment]
@alexcontini did this get added to the menu?  (I'm not sure where to look for it)

**Comment by alexcontini** [comment]
@cjyabraham added under community (community > Telecom User Group), so this should be good to close, thank you!
