### ISSUE TITLE
Video link not working on the job board

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#146]
I received an email from a member:
I just wanted to let you know that the youtube ID is not working on the company profile page (that the job board links to). Attached is the screenshot.
<img width="1281" alt="Screen Shot 2019-11-07 at 9 47 37 AM" src="https://user-images.githubusercontent.com/29307455/68412241-1bde1100-0149-11ea-98e6-a0894057a439.png">

**Comment by dankohn** [comment]
I submitted to jobboard and they said the URL is wrong.

**Comment by cjyabraham** [comment]
The particular ui for this on jobboard.io admin is not very clear.  If the particular video they want to feature is https://www.youtube.com/watch?v=ntLlHBTNOB0 then they should enter ntLlHBTNOB0 in the YouTube ID field.
