### ISSUE TITLE
Remove "older newsletters" from the newsletter page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#147]
Leave the link to the archive

https://www.cncf.io/newsroom/newsletter/

**Comment by cjyabraham** [comment]
Are you saying you want the title "Older Newsletters" removed and everything below it?  Or just the title?

**Comment by KimMcMahon** [comment]
Yes. Older newsletters and everything below it. Thank you!

**Comment by cjyabraham** [comment]
done.
