### ISSUE TITLE
Deployment of Speakers Bureau bulk email

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#148]
- [x] Prepare updated text for [Speakers Bureau page](https://www.cncf.io/speakers/) and [instruction page](https://www.cncf.io/cncf-member-instructions/) and get approvals (Chris)
- [x] Update code to send to live emails (Diego)
- [x] Get Nirav to install and test the LFID login on the live site (Chris)
- [x] Deploy updated code (Chris)
- [x] Update [login page](https://www.cncf.io/speakers/login/) with LFID button and instructions (Chris)
- [x] Test the process (Chris)
- [x] Get [this issue fixed](https://github.com/cncf/wordpress-site/issues/138#issuecomment-559345251)
- [x] Delete Chris Test user after testing (Chris)
- [x] Update [Speakers Bureau page](https://www.cncf.io/speakers/) with updated text and instructions page (Chris)
- [x] invite some cncf members to test (Chris)
- [x] Make sure Taylor knows how to upgrade a user to "Member" (Chris)

**Comment by cjyabraham** [comment]
@KimMcMahon @dankohn I still have not seen any use of this feature.  Is there any real user that we could ask to test it out yet?

**Comment by KimMcMahon** [comment]
I don't have anyone I want to ask. I am working with our PR firm to promote the speaker's bureau and the member feature. We'll have to give it time.

**Comment by dankohn** [comment]
This is a feature that will be mainly used by Kubernetes Community Days. Perhaps @KTan1226 or @oicheryl know of a KCD that wants to solicit for speakers.

**Comment by cjyabraham** [comment]
This has been successfully tested by a user.
