### ISSUE TITLE
Jobs section

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#149]
Please rename the section to "Training, Certification, and Jobs". Add a third column titled "Free CNCF Job Board" and that has several entries from https://jobs.cncf.io/jobs.rss and a link to https://cncf.jobboard.io/ from the title and at the bottom.

**Comment by cjyabraham** [comment]
The final link should be to https://jobs.cncf.io/ I believe, not https://cncf.jobboard.io/.

**Comment by deigolocco** [comment]
hi guys, it's done https://fz-149-cncf.pantheonsite.io/
please let me know if some adjustment is necessary.

**Comment by cjyabraham** [comment]
@dankohn do we want "job board" or "jobs board"?  Currently in the Community menu we have "Free Jobs Board".  Also, are you sure you want the word "free"?  I feel we don't need to emphasize this in a permanent way like in menu links etc.

@dankohn additionally, I think the section should be titled "Latest Jobs" and the button text  at the bottom "CNCF Job Board"

@deigolocco is it possible to style the listing a bit more like how it is on the job board, so styling the company and location on their own line with icons and including the date posted:
<img width="365" alt="Screen Shot 2019-11-23 at 12 17 50 PM" src="https://user-images.githubusercontent.com/463160/69473810-5f907600-0deb-11ea-9249-10d607e0f2c0.png">

**Comment by dankohn** [comment]
"job board" singular, please. I agree about "Latest jobs".
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
Thanks @dankohn.  I've updated the menu.  I assume you wanted to keep the word "free".

**Comment by dankohn** [comment]
WDYT?
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by cjyabraham** [comment]
I think we should drop "free".  It makes it sound cheap... which it is... but I don't think saying "free" will necessarily attract more people.  We do say "free" on the [home page of the board](https://jobs.cncf.io/) which I think is enough.

**Comment by dankohn** [comment]
OK.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by deigolocco** [comment]
Copy and front adjusted

**Comment by cjyabraham** [comment]
@deigolocco I didn't intend for you to copy the exact styles from the job board to use on the cncf homepage.  I was just suggesting you use some variety in font styles to distinguish between the job title, date, company etc rather than having them all look the same and be on the same line.

Could you use existing styles on the cncf homepage instead of copying new styles from the job board?  Maybe something closer to how you list things in the Newsroom section?

**Comment by rodmeurer** [comment]
@cjyabraham we adapted the styles from CNCF to this section, let us know it it's ok now.

**Comment by cjyabraham** [comment]
Thanks @rodmeurer .  Looking at it now, I'm thinking the date doesn't really add much and takes up a lot of space so don't include the date.

@dankohn any thoughts on [the design](https://fz-149-cncf.pantheonsite.io/) before we deploy?

**Comment by dankohn** [comment]
No view.

**Comment by deigolocco** [comment]
@cjyabraham date removed

**Comment by cjyabraham** [comment]
@deigolocco can you remove the background shading please?  Then I think we're good to deploy.

**Comment by deigolocco** [comment]
@cjyabraham  background shading removed

**Comment by cjyabraham** [comment]
deployed
