### ISSUE TITLE
Update News and Community Testimonials

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#15]
Let's update the News and Community Testimonials section on the homepage to just show the title and first dozen few characters of the latest 3 blog posts, 3 announcements, and 3 news articles, and their dates. We've tried to do fancier and more graphical stuff in the past, but it always gets outdated. The headings of the columns (blog, announcements, news) should be links to the three pages.

Then, we can kill the Newsroom: Overview page entirely (it should just redirect to the homepage).

**Comment by KimMcMahon** [comment]
@alexcontini Can you do a design for the three boxes on the Home page? When I say "design" I mean choose a color option for the box - white with a color line around them or the boxes are each a different color - whatever you think looks best on the page. 

The boxes clearly labeled "Blog" "Announcements" "News".

As Dan mentioned, the three latest of each with a few dozen characters.

**Comment by fuerzastudio** [comment]
sure @KimMcMahon

**Comment by deigolocco** [comment]
sure @KimMcMahon

**Comment by deigolocco** [comment]
hi @KimMcMahon here is our design proposal https://www.dropbox.com/s/6maf78sduuvn23k/01-home.jpg?dl=0

**Comment by dankohn** [comment]
Thanks. Could you please do a version where the three boxes are in the same row instead of stacked. Inside each the three items would be stacked. Also, please note that that section goes lower down on the page. 

--
Dan Kohn <dan@linuxfoundation.org>
Executive Director, Cloud Native Computing Foundation  https://www.cncf.io
+1-415-233-1000  https://www.dankohn.com

**Comment by deigolocco** [comment]
sure @dankohn

**Comment by deigolocco** [comment]
under which section should the boxes go?

**Comment by dankohn** [comment]
I was wrong. They should stay above Membership, where they are now.

**Comment by deigolocco** [comment]
ok, thanks

**Comment by deigolocco** [comment]
@dankohn here is the new proposal according last request https://www.dropbox.com/s/p7x8cyfno2nhbse/01-home_v2.jpg?dl=0
Do you think is necessary limitate the title length, to avoid height differences?

**Comment by KimMcMahon** [comment]
I'd like to see just the title and date. Often, the first couple of sentences is not adding any value to the text.

**Comment by deigolocco** [comment]
https://www.dropbox.com/s/jx1k0rtnyxb04il/01-home_v3.jpg?dl=0

**Comment by dankohn** [comment]
Diego, please remove " | Blog" and " | Announcement" everywhere since the category type is shown at the top.

Please also move the "View All Blogs" buttons into the white boxes rather having them below.

But, no need to do another design unless you want to. You can go ahead and implement.

**Comment by deigolocco** [comment]
Ok @dankhon, we'll proceed with the development

**Comment by KimMcMahon** [comment]
Adding Design
![News and Community](https://user-images.githubusercontent.com/29307455/62720062-78088c00-b9c6-11e9-96e9-410723a91645.jpeg)

**Comment by KimMcMahon** [comment]
@deigolocco From Dan:  I'm now thinking the new news section would be better with the headlines just being links rather than having 9 READ NOW buttons. It seems like it might even free up enough space to fit 4 headlines per section.

Please change so the headline is linked, remove the read now button, and include 4 headlines.

**Comment by KimMcMahon** [comment]
@deigolocco Please change the title of the section from "News and Community Testimonials" to "Newsroom"

**Comment by deigolocco** [comment]
ok @KimMcMahon, design adjusted https://www.dropbox.com/s/jyj19xuzdryzp1o/01-home_v4.jpg?dl=0

**Comment by KimMcMahon** [comment]
Thank you @deigolocco. Design added.  And you don't need to update the design - you can implement. :)
![Home Page Newsroom v2](https://user-images.githubusercontent.com/29307455/62724368-0fbea800-b9d0-11e9-8ca9-4d50f07c1c00.jpeg)

**Comment by deigolocco** [comment]
ok @KimMcMahon, thanks

**Comment by dankohn** [comment]
That looks really good. @deigolocco note that it is nicer to paste the images directly into GitHub, as @KimMcMahon has done, rather than link to Dropbox.

**Comment by deigolocco** [comment]
thank you @dankohn , I'll start pasting images now in front

**Comment by deigolocco** [comment]
@KimMcMahon @dankohn will be done tomorrow morning

**Comment by deigolocco** [comment]
@KimMcMahon @dankohn https://fuerza-cncf.pantheonsite.io/

**Comment by dankohn** [comment]
+1. @cjyabraham can deploy once he and @KimMcMahon sign off.

**Comment by KimMcMahon** [comment]
+1. @cjyabraham to you for deploy.

**Comment by cjyabraham** [comment]
This is now live.
