### ISSUE TITLE
No speakers contact form when logged in as a speaker

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#152]
When I am logged in as a user with role "speaker" and I go to a [speaker's profile](https://www.cncf.io/speaker/puja/) I see this:
<img width="901" alt="Screen Shot 2019-11-29 at 11 29 38 AM" src="https://user-images.githubusercontent.com/463160/69843822-b094e400-129b-11ea-87b0-7f58b08173e3.png">

Why isn't there a form there?  When I am a "member" or an "Administrator" the form is there.

**Comment by rodmeurer** [comment]
fixed @cjyabraham at https://fz-152-cncf.pantheonsite.io/speaker/puja/

**Comment by cjyabraham** [comment]
deployed
