### ISSUE TITLE
Event Schedule Email fallback value

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#153]
If "Event Schedule Email" field on the [events we're at](https://www.cncf.io/events-well-be-at/) isn't set, please make the button go to meeting@cncf.io.  Right there are many buttons that don't link anywhere.

**Comment by rodmeurer** [comment]
Done @cjyabraham 
https://fz-153-cncf.pantheonsite.io/events-well-be-at/

**Comment by cjyabraham** [comment]
thanks.  deployed.
