### ISSUE TITLE
Speakers Bureau upgrade investigation

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#154]
Hi @deigolocco , we are considering the best way to move Speakers Bureau into our cncf rebuild project.  Since your team has been working on it most recently, we'd like you to investigate and come up with a recommendation for what we should do.

1. First, there is a new release of [the Ultimate Member plugin](https://wordpress.org/plugins/ultimate-member/), however, if you upgrade, you'll find your directory filters no longer work.  Could you come up with an estimate for how long it would take to upgrade the plugin and get everything to work again?
2. Next, we're considering rebuilding Speakers Bureau without using the Ultimate Member plugin but instead, possibly, using CPTs for speakers and writing code to allow certain users to only be able to edit their own speaker CPT instance.  Could you consider the feasibility of this and whether you think we should go this route?
3. Finally, I've come up with a list of tasks required to move the speakers bureau into our new cncf rebuild project:
- get SB to work with the new ultimate member plugin (or consider writing it from scratch without the plugin)
- migrate all members over
- rewrite the directory and profile pages to leverage our new CSS framework and design patterns
- configure LFID plugin
- optional: I think the whole of SB could do with a UX overhaul to provider easier navigation once you’re logged in as a Member or a Speaker
Does that look right to you and is there anything else I'm forgetting?

**Comment by deigolocco** [comment]
@cjyabraham up to date as [#156 ](https://github.com/cncf/wordpress-site/issues/156)
