### ISSUE TITLE
Create export tool for UM Speakers to facilitate Kim's management of the Speakers Bureau

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#155]

**Comment by rodmeurer** [comment]
Done @cjyabraham . It exports a CSV file with all approved speakers.

https://fz-155-cncf.pantheonsite.io/wp-admin/tools.php?page=export-speakers

**Comment by cjyabraham** [comment]
Great.  @KimMcMahon does this function give you what you need?  If so, I'll deploy.

**Comment by KimMcMahon** [comment]
@cjyabraham @rodmeurer 
Works great! Please deploy.

**Comment by cjyabraham** [comment]
deployed.  [Go here to export](https://www.cncf.io/wp-admin/tools.php?page=export-speakers).
