### ISSUE TITLE
Upgrade the UM plugin and get Speakers Bureau to work

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#156]
[WIP](https://fz-154-cncf.pantheonsite.io/speakers/)

**Comment by deigolocco** [comment]
@cjyabraham up to date https://fz-154-cncf.pantheonsite.io/speakers/

**Comment by cjyabraham** [comment]
A few points:
- The [reCAPTCHA](https://wordpress.org/plugins/um-recaptcha/) needs upgrading in order to work with this version of UM
- I'm not seeing the "X"s anymore, on the live site either, for removing items:
<img width="386" alt="Screen Shot 2019-12-10 at 1 13 11 PM" src="https://user-images.githubusercontent.com/463160/70500826-06e10d00-1b4f-11ea-8a72-319b07d16c0e.png">

**Comment by rodmeurer** [comment]
@cjyabraham Both items have been fixed/updated.

**Comment by cjyabraham** [comment]
great!  deployed.
