### ISSUE TITLE
Add translations for Chinese case studies

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#157]
Add more translations to the Chinese case studies templates.  Translations are provided [here](https://docs.google.com/document/d/15Xt_OeNv7l_BEKZtrxzV1U1lffvrgOjr1GAP8XtKcvQ/edit).

**Comment by deigolocco** [comment]
Translations are done
https://fz-157-cncf.pantheonsite.io/newsroom/case-studies-cn/

@cjyabraham please let me know when it's deployed, because I need to do some adjustments at the dashboard after it.

**Comment by cjyabraham** [comment]
[translations are ready](https://docs.google.com/document/d/15Xt_OeNv7l_BEKZtrxzV1U1lffvrgOjr1GAP8XtKcvQ/edit?ts=5df31037)

**Comment by deigolocco** [comment]
Added @cjyabraham 
Please remember to add the case study type here
![Captura de Tela 2019-12-13 às 10 55 27](https://user-images.githubusercontent.com/5631313/70805812-9f1e0280-1d98-11ea-80b0-374f3125faf9.png)

**Comment by cjyabraham** [comment]
Deployed.  @deigolocco please do your adjustments.

**Comment by KimMcMahon** [comment]
@cjyabraham please make the menu item for the Chinese case studies visible.

**Comment by deigolocco** [comment]
@cjyabraham adjustments are done
@KimMcMahon menu item is visible now

**Comment by cjyabraham** [comment]
Great. Thanks.
