### ISSUE TITLE
Redirect pardot form to Contact Us page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#159]
When you go to this page https://www.cncf.io/people/end-user-community/, scroll to the bottom, and click “I have questions. Can someone contact me?” you get a pardot form which pops up.  Instead, we'd like this link go to the [contact page](https://www.cncf.io/about/contact/).

**Comment by deigolocco** [comment]
done @cjyabraham 
https://www.cncf.io/people/end-user-community/
