### ISSUE TITLE
Blog Page: Update Design

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#16]
For Blog page: https://www.cncf.io/newsroom/blog/
Instead of a listing of the blogs with title and first characters of the blog, use featured image associated with the blog. 
The goal - make the page more visually attractive.
Could also look at using the Snippet to provide a meta description and pull that into the description for each blog.

Using the Snippet meta description will also show up in a Google search.

**Comment by cjyabraham** [comment]
FYI, blog posts do not currently have featured images so they will need to be added.

**Comment by cjyabraham** [comment]
I've added this to the [requirements doc for redesign](https://docs.google.com/spreadsheets/d/1ufJUHCkt4cT_Ovdm3T7y8oRTvj69IEMI9cqJHDYSM6w/edit#gid=952198595)

**Comment by thetwopct** [comment]
We can set it so:
1. Uses featured image if present
2. Grabs first image in post if present
3. Else, uses default image

Should make it look a lot better with some images;  we can update the layout too as the super wide line length is not that attractive. Should also apply this to announcements and news pages (any post archive):
https://www.cncf.io/newsroom/in-the-news/
https://www.cncf.io/newsroom/announcements/ 

It may be an idea to start adding images to all posts as a "Featured image" from today so once the site redevelopment is done there is already a cache of images in the archives ready to display. The featured image is also inserted in to the singular post page underneath the title.

![20191122094020-Edit Post ‹ Cloud Native Computing Foundation — WordPress](https://user-images.githubusercontent.com/10615884/69393565-1caba100-0d0c-11ea-8679-76c18f5a7149.jpg)

**Comment by cjyabraham** [comment]
closing [in favor of this](https://github.com/cncf/cncf.io/issues/11).
