### ISSUE TITLE
Images for "Events we'll be at"

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#160]
Need both the home page featured image and the featured image for each of these events. I've shared the event page for the event for image inspiration.

https://events.linuxfoundation.org/lf-member-summit/
https://events.linuxfoundation.org/open-networking-edge-summit-north-america/
https://events.linuxfoundation.org/open-networking-edge-summit-europe/
https://cloud.withgoogle.com/next/sf/
https://events.linuxfoundation.org/open-source-summit-north-america/
https://www.vmworld.com/en/us/index.html
https://events.linuxfoundation.org/open-source-summit-europe/

**Comment by pablodelarocha** [comment]
@KimMcMahon sure thing! Here they are: 

![Open_Source_Summit_EU_square](https://user-images.githubusercontent.com/54405572/71259404-28908000-2317-11ea-9000-8dc48529507d.jpg)
![Open_Source_Summit_EU_wide](https://user-images.githubusercontent.com/54405572/71259405-28908000-2317-11ea-8632-107ba13e0d89.jpg)
![Next_square](https://user-images.githubusercontent.com/54405572/71259406-28908000-2317-11ea-8465-76db2032f278.jpg)
![Next_wide](https://user-images.githubusercontent.com/54405572/71259407-29291680-2317-11ea-8c02-89a8c793545a.jpg)
![LF_member_summit_square](https://user-images.githubusercontent.com/54405572/71259408-29291680-2317-11ea-9c8f-facaff25e368.jpg)
![LF_member_summit_wide](https://user-images.githubusercontent.com/54405572/71259409-29291680-2317-11ea-8705-612d236685ff.jpg)
![vmworld_square](https://user-images.githubusercontent.com/54405572/71259410-29291680-2317-11ea-9a73-369f0d47220f.jpg)
![vmworld_wide](https://user-images.githubusercontent.com/54405572/71259411-29c1ad00-2317-11ea-9b63-7aace79195cb.jpg)
![Open_Source_Summit_NA_wide](https://user-images.githubusercontent.com/54405572/71259412-29c1ad00-2317-11ea-907d-40efba5c755d.jpg)
![Open_Source_Summit_NA_square](https://user-images.githubusercontent.com/54405572/71259413-29c1ad00-2317-11ea-9ac8-9178d26ce53c.jpg)
![OpenNetwork_Edge_Summit_NA_square](https://user-images.githubusercontent.com/54405572/71259415-29c1ad00-2317-11ea-8568-74046fc0621f.jpg)
![OpenNetwork_Edge_Summit_NA_wide](https://user-images.githubusercontent.com/54405572/71259416-2a5a4380-2317-11ea-9639-2c78b83c8aaf.jpg)
![OpenNetwork_Edge_Summit_EU_square](https://user-images.githubusercontent.com/54405572/71259417-2a5a4380-2317-11ea-8ee2-72308af4ad14.jpg)
![OpenNetwork_Edge_Summit_EU_wide](https://user-images.githubusercontent.com/54405572/71259418-2a5a4380-2317-11ea-8dec-c5b9f72bb5a8.jpg)

**Comment by KimMcMahon** [comment]
Thank you! Awesome!
