### ISSUE TITLE
Add Kubernetes Days India 2019 transparency report to cncf.io

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#161]
Menu:
About
Conference Transparency Reports
Between Seattle and Shanghai

[Kubernetes Days India 2019 _ Transparency Report.pdf](https://github.com/cncf/wordpress-site/files/3995912/Kubernetes.Days.India.2019._.Transparency.Report.pdf)

**Comment by alexcontini** [comment]
@KimMcMahon I have added the pdf to the menu - https://www.cncf.io/ - let me know if this doesn't work!

**Comment by dankohn** [comment]
In the menu, please change "Kubernetes Day March 2019" to "Bengaluru March
2019"

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by alexcontini** [comment]
@dankohn  updated! https://www.cncf.io/
