### ISSUE TITLE
Images for 'Events we'll be at' page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#162]
Hello Pablo,
Can you create some more images for the Events we'll be at page? Square and rectangle.

https://www.socallinuxexpo.org/scale/18x
https://www.susecon.com/
https://www.isc-hpc.com/
https://events.linuxfoundation.org/open-source-summit-japan/

Thank you and Happy New Year!

**Comment by pablodelarocha** [comment]
Sure @KimMcMahon here's the banners for all 4 events:

![susecon](https://user-images.githubusercontent.com/54405572/71670242-21716500-2d4e-11ea-94af-a930695ee68d.jpg)
![ISC](https://user-images.githubusercontent.com/54405572/71670243-2209fb80-2d4e-11ea-887d-7badbb0f551b.jpg)
![ISC_square](https://user-images.githubusercontent.com/54405572/71670245-2209fb80-2d4e-11ea-8fe0-e91fefc23981.jpg)
![susecon_square](https://user-images.githubusercontent.com/54405572/71670246-2209fb80-2d4e-11ea-8b4e-58391519b50a.jpg)
![scale18x](https://user-images.githubusercontent.com/54405572/71670247-22a29200-2d4e-11ea-8c37-3f290e109402.jpg)
![scale18x_square](https://user-images.githubusercontent.com/54405572/71670248-22a29200-2d4e-11ea-8d27-aea1b80af14b.jpg)
![OSS_Japan_square](https://user-images.githubusercontent.com/54405572/71670250-22a29200-2d4e-11ea-854d-86167defc4db.jpg)
![OSS_Japan](https://user-images.githubusercontent.com/54405572/71670251-22a29200-2d4e-11ea-8df9-0e4d382b2be0.jpg)

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha!
