### ISSUE TITLE
Long job not displaying right

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#163]
![image](https://user-images.githubusercontent.com/3083270/72236323-62fedd00-35a4-11ea-9761-81885d297405.png)

https://jobs.cncf.io/jobs/27903066-cloud-devops-engineer-at-an-innovative-digital-partner-for-a-list-brands-that-aims-to-create-a-dent-in-the-digital-landscape

It looks like you need to truncate long company names so that the location will show.

**Comment by cjyabraham** [comment]
@dankohn what url did you go to to see that?  I can't reproduce.

**Comment by dankohn** [comment]
On cncf.io

**Comment by rodmeurer** [comment]
Hi @cjyabraham, it will truncate the company name like in this example
https://fz-163-cncf.pantheonsite.io/  (we put the name of the company in the code just for testing purposes by now). Is this what you intended?

The other possibility is to display all company's name in more then one line.

**Comment by cjyabraham** [comment]
LGTM

**Comment by rodmeurer** [comment]
@cjyabraham it's done.

https://fz-163-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
thanks.  deployed.
