### ISSUE TITLE
Lower hyphen by 3 pixels in date ranges that span months

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#167]
<img width="344" alt="Screen Shot 2020-02-06 at 11 30 57 PM" src="https://user-images.githubusercontent.com/463160/73957310-c298a000-4938-11ea-9717-eac6790e46a5.png">

For date ranges like this that span two months, could you make the hyphen exactly 3px lower, so it looks like this:
<img width="331" alt="Screen Shot 2020-02-06 at 11 26 55 PM" src="https://user-images.githubusercontent.com/463160/73957185-9846e280-4938-11ea-9a1c-dcfb17185a7c.png">

**Comment by rodmeurer** [comment]
Done @cjyabraham 
https://fuerza-cncf.pantheonsite.io/events-well-be-at/

**Comment by dankohn** [comment]
Looks great!

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
