### ISSUE TITLE
Work with VideoKen to integrate their product into the CNCF website

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#168]
When Kuldeep (kuldeepyadav) accepts the request to join this repo, he will be assigned this issue to work with Chris.

Kuldeep can explain the project and the technical need.

**Comment by kuldeepyadav** [comment]
Hi @cjyabraham, Please create a CNAME entry in your DNS dashboard mapping 'https://videos.cncf.io/' to 'https://lake.videoken.com/cncf'. 

Once the CNAME entry is created, please share the SSL certificate hosted by cncf.io with us and we will make configuration changes on our side.

**Comment by cjyabraham** [comment]
Thanks.  I've submitted this request upstream to LFIT.  [Ticket for my own reference](https://jira.linuxfoundation.org/servicedesk/customer/portal/2/IT-18936).

**Comment by cjyabraham** [comment]
@kuldeepyadav, regarding your request for SSL certificate, the IT guys said this: "Not sure what you mean by SSL certificate. We request that through our registrar and uses Let's Encrypt. There really isn't anything to provide"

What exactly do you need?

**Comment by cjyabraham** [comment]
@kuldeepyadav regarding the CNAME request, IT replied: 

> lake.videoken.com/cncf is not a valid domain content to use. It would need to be "lake.videoken.com" or some sort of link.  We can also set it up as a URL redirect.  videos.cncf.io goes to lake.videoken.com/cncf no CNAME masking.

Any thoughts?

**Comment by kuldeepyadav** [comment]
Regarding the SSL certificate, you need to provide us "fullchain.pem and privkey.pem" files, which you have generated for the ROOT domain (ie cncf.io) using LetsEncrypt. This is needed because we will be serving a sub-domain **videos.cncf.io** from our cloud.

**Comment by kuldeepyadav** [comment]
@cjyabraham, For CNAME, please make an entry from **videos.cncf.io** to **cncf.videoken.com**

**Comment by cjyabraham** [comment]
The CNAME has been setup.  I'll email you the SSL files.

**Comment by dankohn** [comment]
Will the SSL files stop working after 90 days? Note that with Netlify, we
just setup the CNAME and they configure Let's Encrypt.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by kuldeepyadav** [comment]
> The CNAME has been setup. I'll email you the SSL files.

@cjyabraham the CNAME seems to be redirecting to **videoken.com** instead of https://cncf.videoken.com/ . Can you please correct that.



> Will the SSL files stop working after 90 days?

Yes, that is a good point. We will generate it ourselves from LetsEncrypt so that updation can be done easily.

**Comment by cjyabraham** [comment]
@kuldeepyadav I don't think that redirect is happening on our side.  The LF IT guys have confirmed that the CNAME is setup correctly.  See below:
<img width="1050" alt="Screen Shot 2020-02-13 at 9 26 13 AM" src="https://user-images.githubusercontent.com/463160/74496822-73410980-4f0e-11ea-975f-6b9d2263e862.png">

**Comment by kuldeepyadav** [comment]
@cjyabraham thanks for your help. The website is up now, https://videos.cncf.io/

We will work with @KimMcMahon after this, may need your help again in putting this link somewhere on the CNCF website homepage for visibility as well as it will start getting indexed by search engines.

**Comment by cjyabraham** [comment]
Very nice!  Ok, keep me posted.  I'll close out this issue for now.
