### ISSUE TITLE
ACF js error preventing configuring social links for People

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#171]
@amye has reported this and said that it has only started happening in the last week:
If you go to the [live site](https://www.cncf.io/wp-admin/post-new.php?post_type=persons) and try and add/edit a person, in the Links section when you choose "Add Row", the dropdown that appears has no values.  Clicking "Add Row" triggers a js error: "Uncaught TypeError: r.select2 is not a function" and the admin is not able to add any social links. 

If you try it on the [dev site](https://dev-cncf.pantheonsite.io/wp-admin/post-new.php?post_type=persons), the full dropdown list populates correctly with options:
<img width="700" alt="Screen Shot 2020-02-15 at 2 33 46 PM" src="https://user-images.githubusercontent.com/463160/74584024-31908b80-5000-11ea-90a5-89b99a0a15da.png">

Figure out why it's not working on the live site and fix the problem.

**Comment by deigolocco** [comment]
fixed @cjyabraham https://fz-171-cncf.pantheonsite.io/wp-admin/post-new.php?post_type=persons

There was a function removing the select2 and some other scripts from everything related to Ultimate Member's plugin. But in this case didn't have the '_utm' prefix, so was removing the select2 from all places.
![screenshot_20200217-102158](https://user-images.githubusercontent.com/5631313/74658198-86531400-5170-11ea-8f7d-70d479e21611.png)

**Comment by cjyabraham** [comment]
deployed.  thanks!
