### ISSUE TITLE
Add filter by language to webinars

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#173]
Can we add a filter on recorded webinars so a user can select either English language or Chinese language webinars?
https://www.cncf.io/webinars/

**Comment by cjyabraham** [comment]
Yes, I'll add this as a requirement to our rebuild.

**Comment by KimMcMahon** [comment]
@cjyabraham Yes

**Comment by cjyabraham** [comment]
ok, closing here for now
