### ISSUE TITLE
Featured and home page image for 3rd party gRPC

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#174]
https://events.linuxfoundation.org/grpc-conf/

**Comment by cjyabraham** [comment]
@KimMcMahon what are you wanting to happen with this issue?

**Comment by KimMcMahon** [comment]
I need the images created that I add to the 3rd party event to go on this page: https://www.cncf.io/events-well-be-at/grpc-conf-2020/

**Comment by cjyabraham** [comment]
I see, ok.  Should we assign to Alex then?  Is she the one who normally does those?

**Comment by pablodelarocha** [comment]
@cjyabraham and @KimMcMahon it's been a while, but i think i was the one who did the last banners. Here's both versions for this event:

![gRPC_square](https://user-images.githubusercontent.com/54405572/76085799-85ecb280-5f91-11ea-8168-cbcc61f57f12.jpg)
![gRPC_wide](https://user-images.githubusercontent.com/54405572/76085804-871ddf80-5f91-11ea-87ac-27f982f1dc90.jpg)

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha 
Can you also create images for PromCon?

https://promcon.io/2020-vancouver/

**Comment by pablodelarocha** [comment]
Sure Kim, here they are:

![promcon2020_square](https://user-images.githubusercontent.com/54405572/76651858-23bd2000-6544-11ea-8a9a-8c62a250861a.jpg)
![promcon2020_wide](https://user-images.githubusercontent.com/54405572/76651861-2586e380-6544-11ea-90f7-6b1fb241ab9c.jpg)

**Comment by KimMcMahon** [comment]
Great! Thank you!
