### ISSUE TITLE
Speakers Bureau filter actions are timing out

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#175]
When I try and go [here](https://www.cncf.io/speakers/?sb_certifications=Ambassador&languages=Arabic&_lc=sb_certifications) the request times out.  If I try other filter combinations, they are timing out too.

Digging into this, there appear to be some slow queries occurring:
<img width="754" alt="Screen Shot 2020-03-08 at 7 47 46 PM" src="https://user-images.githubusercontent.com/463160/76162155-b55c1480-6175-11ea-8772-e22b80033004.png">

Digging in to one of those, it appears to be coming from this stack trace:
```
SELECT DISTINCT SQL_CALC_FOUND_ROWS wp_users.ID FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id ) WHERE ?=? AND ( 
  ( 
    ( 
      wp_usermeta.meta_key = ? 
      AND 
      ( 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value != ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value != ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
        )
      )
    ) 
    AND 
    ( 
      ( 
        ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
      )
    )
  )
) ORDER BY wp_usermeta.meta_value ASC 

…d at /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
wp-db.php (2030)
…d at /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
wp-db.php (1918)
…d at /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
wp-db.php (2611)
…ings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
class-wp-user-query.php (620)
…ings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
class-wp-user-query.php (78)
…789fb/code/wp-content/themes/salient-child/template-parts/speakers/
filters.php (14)
…2f9abc045789fb/code/wp-content/themes/salient-child/includes/helpers/
utils.php (102)
…abc045789fb/code/wp-content/themes/salient-child/includes/helpers/
speakers.php (166)
…7c6c687472a9b2f9abc045789fb/code/wp-includes/rest-api/
class-wp-rest-server.php (946)
…7c6c687472a9b2f9abc045789fb/code/wp-includes/rest-api/
class-wp-rest-server.php (329)
…t /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
rest-api.php (305)
…v/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
class-wp-hook.php (288)
…v/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/class-wp-hook.php (312)
… at /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
plugin.php (544)
…t /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/
class-wp.php (387)
…t /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/class-wp.php (729)
… /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-includes/functions.php (1255)
…lled at /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/wp-blog-header.php (16)
…equire called at /srv/bindings/d3ed47c6c687472a9b2f9abc045789fb/code/index.php (17)
```

Here's a similar but different stack trace from the same slow query:
```
SELECT DISTINCT SQL_CALC_FOUND_ROWS wp_users.ID FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id ) WHERE ?=? AND ( 
  ( 
    ( 
      wp_usermeta.meta_key = ? 
      AND 
      ( 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value != ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value != ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
        )
      )
    ) 
    AND 
    ( 
      ( 
        ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
      )
    )
  )
) ORDER BY wp_usermeta.meta_value ASC 


…d at /srv/bindings/e214d7805c904b4ab0e7eca3a36ee99b/code/wp-includes/
wp-db.php (2030)
…d at /srv/bindings/e214d7805c904b4ab0e7eca3a36ee99b/code/wp-includes/
wp-db.php (1918)
…d at /srv/bindings/e214d7805c904b4ab0e7eca3a36ee99b/code/wp-includes/
wp-db.php (2611)
…ings/e214d7805c904b4ab0e7eca3a36ee99b/code/wp-includes/
class-wp-user-query.php (620)
…ings/e214d7805c904b4ab0e7eca3a36ee99b/code/wp-includes/
class-wp-user-query.php (78)
…ca3a36ee99b/code/wp-content/themes/salient-child/includes/helpers/
speakers.php (475)
…ee99b/code/wp-content/themes/salient-child/template-parts/speakers/
filters.php (16)
…e7eca3a36ee99b/code/wp-content/themes/salient-child/includes/helpers/
utils.php (102)
…7eca3a36ee99b/code/wp-content/themes/salient-child/page-templates/
speakers.php (61)
…bindings/e214d7805c904b4ab0e7eca3a36ee99b/code/wp-includes/
template-loader.php (98)
…lled at /srv/bindings/e214d7805c904b4ab0e7eca3a36ee99b/code/
wp-blog-header.php (19)
…equire called at /srv/bindings/e214d7805c904b4ab0e7eca3a36ee99b/code/
index.php (17)
```

I don't know why this has just started happening.  There has not been a deployment on the site in the last 20 days.  It also appears to be an issue on [the dev site](https://dev-cncf.pantheonsite.io/speakers/?expertise=Community&_lc=expertise), so that would mean it's not related to any recent changes to the data.

I checked the php-slow.log and these particular slow queries seem to have just started today, 3/8/20.

**Comment by cjyabraham** [comment]
The issue is fixed for now.  I worked with the Pantheon support guys and after trying a number of things they suggested running [optimize table](https://www.thegeekstuff.com/2016/04/mysql-optimize-table/) in mysql, which I did on the `wp_users` and `wp_usermeta` tables.  This defragments and reclaims unused space on the tables.  The speakers bureau filters now work normally for me.  

I'll keep this issue open for a bit so we can consider whether there is something about our code that makes these tables particularly prone to fragmentation.  @deigolocco, no rush, but could you consider this issue and give your thoughts?

**Comment by cjyabraham** [comment]
Following the instructions [here](https://www.thegeekstuff.com/2016/04/mysql-optimize-table/), I thought I'd take the opportunity to optimize various other tables in the db as there are a number with quite a lot of free space and are misreporting the amount of used space.

`select table_name, round(data_length/1024/1024) as data_length_mb, round(data_free/1024/1024) as data_free_mb from information_schema.tables   where round(data_free/1024/1024) > 0 or round(data_length/1024/1024) > 0 order by data_free_mb;`
produces this result:
```
+----------------------+----------------+--------------+
| table_name           | data_length_mb | data_free_mb |
+----------------------+----------------+--------------+
| time_zone_transition |              2 |            0 |
| wp_usermeta          |              3 |            0 |
| wp_redirection_logs  |              1 |            4 |
| wp_redirection_404   |              3 |            4 |
| wp_stream_meta       |              2 |            4 |
| wp_postmeta          |             39 |            4 |
| wp_stream            |              0 |            4 |
| wp_options           |              4 |            4 |
| wp_yoast_seo_meta    |              0 |            4 |
| wp_yoast_seo_links   |              0 |            4 |
| wp_gf_entry_meta     |              3 |            4 |
| wp_relevanssi        |             20 |            6 |
| wp_posts             |            242 |            6 |
+----------------------+----------------+--------------+
13 rows in set (0.23 sec)
```

After optimizing each of those tables we get this result:
```
+----------------------+----------------+--------------+
| table_name           | data_length_mb | data_free_mb |
+----------------------+----------------+--------------+
| wp_yoast_seo_links   |              2 |            0 |
| wp_gf_entry_meta     |              3 |            0 |
| wp_usermeta          |              3 |            0 |
| wp_redirection_logs  |              2 |            0 |
| time_zone_transition |              2 |            0 |
| wp_posts             |            243 |            0 |
| wp_stream_meta       |              2 |            0 |
| wp_postmeta          |             39 |            0 |
| wp_yoast_seo_meta    |              2 |            0 |
| wp_relevanssi        |             20 |            1 |
| wp_redirection_404   |              4 |            4 |
| wp_options           |              4 |            4 |
+----------------------+----------------+--------------+
12 rows in set (0.30 sec)
```

That might speed up some of our queries throughout the site.

**Comment by cjyabraham** [comment]
The new version of Ultimate Member has an "Enable custom table for usermeta" option which might make our searches faster and more robust.  It may not be related to this issue but could be worth investigating.

**Comment by cjyabraham** [comment]
The original issue showed up again just now and I had to go in and `optimize table wp_usermeta;` which fixed the problem.

@deigolocco can you look back through code changes to see if there is anything we've done recently that may have caused this?

**Comment by cjyabraham** [comment]
A few updates:
- @deigolocco and team are looking into refactoring the search to use the "Enable custom table for usermeta" to see if that can be a more robust or performant solution
- I am waiting to see if the filters freeze up again, at which point I'll download the db locally to [experiment with](https://www.thegeekdiary.com/beginners-guide-to-implementing-table-maintenance-in-mysql/) before running the `optimize table` on the live instance
- @deigolocco 's team also noticed that the wp_stream tables sometimes balloon in size so this is something to check out if we hit the issue again

**Comment by cjyabraham** [comment]
The search filters are slow again this morning.  Some filter combinations seem to take about 45s to return results.  This isn't running into the 59s Pantheon limit on requests so results are being returned, however, it is taking a long time.

When I clear the cache, to load [this request](https://www.cncf.io/speakers/?sb_certifications=CKAD&expertise=Customizing+%26+Extending+Kubernetes&_project=Envoy&languages=English&country=United+States&_lc=country) consistently takes about 30s.  Once cached, it'll respond in less than 1s.

Here is the slow query that is causing it:
```
SELECT DISTINCT SQL_CALC_FOUND_ROWS wp_users.ID FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id )  INNER JOIN wp_usermeta AS mt? ON ( wp_users.ID = mt?.user_id ) WHERE ?=? AND ( 
  ( 
    ( 
      wp_usermeta.meta_key = ? 
      AND 
      ( 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value != ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value != ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
        ) 
        AND 
        ( 
          ( mt?.meta_key = ? AND mt?.meta_value = ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? ) 
          OR 
          ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
        )
      )
    ) 
    AND 
    ( 
      ( 
        ( mt?.meta_key = ? AND mt?.meta_value LIKE ? )
      )
    )
  )
) ORDER BY wp_usermeta.meta_value ASC 
```

I ran `optimize table wp_usermeta, wp_users, wp_options;` but that had no effect.  The page still takes about 30s to load after clearing the server cache.

**Comment by cjyabraham** [comment]
I pulled out a real query with real values:
```
SELECT DISTINCT SQL_CALC_FOUND_ROWS wp_users.ID FROM wp_users INNER JOIN wp_usermeta ON ( wp_users.ID = wp_usermeta.user_id )  INNER JOIN wp_usermeta AS mt1 ON ( wp_users.ID = mt1.user_id )  INNER JOIN wp_usermeta AS mt2 ON ( wp_users.ID = mt2.user_id )  INNER JOIN wp_usermeta AS mt3 ON ( wp_users.ID = mt3.user_id )  INNER JOIN wp_usermeta AS mt4 ON ( wp_users.ID = mt4.user_id )  INNER JOIN wp_usermeta AS mt5 ON ( wp_users.ID = mt5.user_id )  INNER JOIN wp_usermeta AS mt6 ON ( wp_users.ID = mt6.user_id )  INNER JOIN wp_usermeta AS mt7 ON ( wp_users.ID = mt7.user_id )  INNER JOIN wp_usermeta AS mt8 ON ( wp_users.ID = mt8.user_id )  INNER JOIN wp_usermeta AS mt9 ON ( wp_users.ID = mt9.user_id ) WHERE 1=1 AND (
--
  | (
  | (
  | wp_usermeta.meta_key = 'last_name'
  | AND
  | (
  | (
  | ( mt1.meta_key = 'synced_profile_photo' AND mt1.meta_value != '' )
  | OR
  | ( mt2.meta_key = 'profile_photo' AND mt2.meta_value != '' )
  | )
  | AND
  | (
  | ( mt3.meta_key = 'account_status' AND mt3.meta_value = 'approved' )
  | )
  | AND
  | (
  | ( mt4.meta_key = 'sb_certifications' AND mt4.meta_value = 'CKAD' )
  | OR
  | ( mt4.meta_key = 'sb_certifications' AND mt4.meta_value LIKE '%s:4:\"CKAD\";%' )
  | OR
  | ( mt4.meta_key = 'sb_certifications' AND mt4.meta_value LIKE '%\"CKAD\"%' )
  | )
  | AND
  | (
  | ( mt5.meta_key = 'expertise' AND mt5.meta_value = 'Customizing & Extending Kubernetes' )
  | OR
  | ( mt5.meta_key = 'expertise' AND mt5.meta_value LIKE '%s:34:\"Customizing & Extending Kubernetes\";%' )
  | OR
  | ( mt5.meta_key = 'expertise' AND mt5.meta_value LIKE '%\"Customizing & Extending Kubernetes\"%' )
  | )
  | AND
  | (
  | ( mt6.meta_key = 'project' AND mt6.meta_value = 'Envoy' )
  | OR
  | ( mt6.meta_key = 'project' AND mt6.meta_value LIKE '%s:5:\"Envoy\";%' )
  | OR
  | ( mt6.meta_key = 'project' AND mt6.meta_value LIKE '%\"Envoy\"%' )
  | )
  | AND
  | (
  | ( mt7.meta_key = 'languages' AND mt7.meta_value = 'English' )
  | OR
  | ( mt7.meta_key = 'languages' AND mt7.meta_value LIKE '%s:7:\"English\";%' )
  | OR
  | ( mt7.meta_key = 'languages' AND mt7.meta_value LIKE '%\"English\"%' )
  | )
  | AND
  | (
  | ( mt8.meta_key = 'country' AND mt8.meta_value = 'United States' )
  | OR
  | ( mt8.meta_key = 'country' AND mt8.meta_value LIKE '%s:13:\"United States\";%' )
  | OR
  | ( mt8.meta_key = 'country' AND mt8.meta_value LIKE '%\"United States\"%' )
  | )
  | )
  | )
  | AND
  | (
  | (
  | ( mt9.meta_key = 'wp_capabilities' AND mt9.meta_value LIKE '%\"um\\_speaker\"%' )
  | )
  | )
  | )
  | ) ORDER BY wp_usermeta.meta_value ASC
```

I ran this locally and it takes about 14s to run.  On prod it takes about 19s to run.

**Comment by cjyabraham** [comment]
One idea to speed up filtering is to create a new Speakers CPT with taxonomies that essentially mirrors the data behind each user.  We could write filter hooks on each add/edit/delete action to a user of role speaker to sync the data with the CPT.  We could then query the CPT directly using taxonomies which would be super fast, much like we do with webinars, case studies, etc...

**Comment by deigolocco** [comment]
@cjyabraham it's working now, you can check here https://fz-175-cncf.pantheonsite.io/speakers/. 

### 1 - The ultimate-member plugin cannot create the table in pantheon.

`WordPress database error Index column size too large. The maximum column size is 767 bytes. for query CREATE TABLE wp_um_metadata (
umeta_id bigint(20) unsigned NOT NULL auto_increment,
user_id bigint(20) unsigned NOT NULL default '0',
um_key varchar(255) default NULL,
um_value longtext default NULL,
PRIMARY KEY  (umeta_id),
KEY user_id_indx (user_id),
KEY meta_key_indx (um_key),
KEY meta_value_indx (um_value(191))`

* To solve this we created the table manually directly in the environment via command line.

### 2 - The plugin was not importing all the necessary user metas for the new table.

* To solve this we created a function (`fuerza_get_um_usermeta_fields`) that returns all the necessary usermetas. It is in the file `functions.php`

### 3 - The plugin was unable to insert all items in the new table, as by default the import is done every 500, and it is done in a single INSERT, it was too big, I believe that is the reason for not inserting some items.

* To resolve, decrease the amount to 100.
* Contents that contained emojis, were giving error at the time of insertion, we implemented a treatment for this through the function `wp_encode_emoji`.

### Files changed in the plugin:
* `wp-content / plugins / ultimate-member / includes / admin / core / class-admin-settings.php`
* `wp-content / plugins / ultimate-member / includes / core / class-member-directory-meta.php`
* `wp-content / plugins / ultimate-member / includes / admin / assets / js / um-admin-forms.js`

After your validation we need to roll back the plugin files to they initial statement.

But one thing is very important
![screenshot_20200311-163719](https://user-images.githubusercontent.com/5631313/76459604-4243df80-63bb-11ea-94f9-f01dae7f65b0.png)
Every time this option is activated and ran the routine, the metas from the table `wp_usermeta` are copied to the table `wp_um_metadata`. 
So if in one moment you judge necessary to run this process again, before it you must adjust those 3 files, so it will work on pantheon. After the process rollback the files.

Please feel free to ping me on slack for any clarification

**Comment by cjyabraham** [comment]
Thanks Diego.  I did some testing today with [these results](https://docs.google.com/spreadsheets/d/18ely7z_DUkUqeumaLT6uCXL4k-ee_1LUa0v_CY8alZo/edit?usp=sharing).  You'll see your new method in column C.  Additionally, I included tests from the live site before and after running `optimize table`.  It seems optimizing needs to be done almost every day now to keep the db in good health.

It's not clear at this point whether your new method solves this problem.  If we deploy it live, we don't know if the tables will also need optimizing each day.  We don't yet know the cause of the table fragmentation.  Do you agree?

At this point I see two options:
1. We could deploy your new method and see if it stands up over time.  First, however, we'd need to do some thorough testing and the deployment would need to happen in stages due to the code changes you mention above.
2. We could try creating a structured mirror of the speakers data using CPTs and taxonomies, [as I describe here](https://github.com/cncf/wordpress-site/issues/175#issuecomment-597489386).  We could then use the search/filter plugin, similar to case studies, for the search UI.

How does that sound?  Do you have any further insight into this that might be helpful?

**Comment by deigolocco** [comment]
hi @cjyabraham . I believe it's better we proceed with option 1, this can be implemented in just a few hours. Did you have a chance to test [here](https://fz-175-cncf.pantheonsite.io/speakers/.)?
Option 2 will demand a few days of implementation.
You are right about we don't yet the reason these things are happening. This suddenly started, and looks like this behavior exist only in prod, the [dev-site ](https://dev-cncf.pantheonsite.io/speakers/?expertise=Community&_lc=expertise) that you sent the url is working.
Did you check with Pantheon support what could be the cause? If necessary we can involve a DevOps to do a deeper investigation, but in prod, if possible.

**Comment by cjyabraham** [comment]
I have actually reproduced the issue on dev sites as well as prod.  

I agree, let's deploy option 1 and see how it goes for the next few days.  I have tested it out today and it seems solid.  It sounds like this deploy will need several stages:
1. Deploy the modified ultimate member plugin
2. Create the new table directly in MySQL
3. Run the migration steps in ultimate member
4. Roll back the ultimate member files and re-deploy

Does that cover it?  Let's connect on Slack to find a time to do this together.

**Comment by cjyabraham** [comment]
Option 1 has been deployed.  Let's keep an eye on this for the next week or so to see if there are any problems.

**Comment by cjyabraham** [comment]
The filters are [testing well today](https://docs.google.com/spreadsheets/d/18ely7z_DUkUqeumaLT6uCXL4k-ee_1LUa0v_CY8alZo/edit#gid=0).

**Comment by cjyabraham** [comment]
All looking good today.

**Comment by cjyabraham** [comment]
Looking good today.  I'll close for now.  Thanks for the help with this.
