### ISSUE TITLE
Change Newsletter signup to SFMC form

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#178]
Take the form code that is on the footer of the homepage and submits to SFMC and replace [this old Gravity Form](https://www.cncf.io/newsroom/newsletter/) with it.  You can keep the styles roughly the same.

**Comment by rodmeurer** [comment]
It's done @cjyabraham 
https://fz-178-cncf.pantheonsite.io/newsroom/newsletter/

**Comment by cjyabraham** [comment]
Thanks.  When I type in text it's almost impossible to read.  Can you make the text darker?

**Comment by rodmeurer** [comment]
Fixed @cjyabraham 
https://fz-178-cncf.pantheonsite.io/newsroom/newsletter/

**Comment by cjyabraham** [comment]
Thanks.  Deployed and tested live.
