### ISSUE TITLE
Add a classification of blogs based by offer

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#179]
On the CNCF blog, we have multiple classifications of authors:
CNCF Staff
Member
Ambassador
Project
SIG
Community Member

I would like each blog to have the author type listed at the top of the blog.

To make it easier for the person posting the blog and to ensure consistency with the author classification, I would like the blog to have a checkbox for each author type.

<img width="909" alt="Screen Shot 2020-03-13 at 7 30 34 AM" src="https://user-images.githubusercontent.com/29307455/76625667-64457b00-64fd-11ea-8bad-3ce95ca8d078.png">

**Comment by cjyabraham** [comment]
hi @KimMcMahon .  For the new site we're thinking of use the byline for our in-house authors (Dan, Chris An, Ihor, Amye) and use a Gutenberg block to feature guest author bios.  How do you suggest we use these categories?  Could we state who a person is within the guest author bio?

**Comment by KimMcMahon** [comment]
@cjyabraham FYI - in-house author, add me to that list.

Similar to how we list whether a webinar is a member webinar, project webinar, etc, we need to do the same with the blogs.

**Comment by cjyabraham** [comment]
I see.  We currently categorize all CNCF posts as either:
- Blog
- Announcement
- News

So you're wanting a separate categorization for Blog posts specifically with the following categories?
- CNCF Staff
- Member
- Ambassador
- Project
- SIG
- Community Member

Is that right?  If a blog post is categorized as "CNCF Staff", what does that mean?  If one is classified as "Project", what does that mean?  Is this a MECE set or can a blog post potentially be categorized as more than one?

**Comment by KimMcMahon** [comment]
Hello @cjyabraham, Correct - the 5 classifications.

A blog post can only be classified as one type of blog.

CNCF Staff blog is a blog written by one of the CNCF team members.
Project blog is a blog written about a CNCF graduated or incubating project.

Thank you!
Kim

**Comment by KimMcMahon** [comment]
More definition on blog posts:
Project: Any blog post on a graduated and incubating project. This is written by or on behalf of the project. If written by a member, this blog is still classified as a Project blog. Example is a Harbor blog written by the VMware team. The blog is classified as a project blog.

Member blog: Any blog post written by a member. The blog must comply with the blog guidelines. A member can write about any open source project, including a CNCF Sandbox project. If a CNCF member writes solely about a CNCF graduated or incubating project and on behalf of the project, it is classified as a project blog. If the blog contains information about a CNCF graduated or incubating project and includes information on how to do something with that project, it is classified as a member blog.

Special Interest Group (SIG): A blog written by a SIG team member(s) is classified as a SIG blog. If a CNCF member writes a blog on behalf of the SIG, it is classified as a SIG blog. If a member writes a blog about a SIG, it is classified as a member blog.

Ambassador blog: This is a blog written by one of the CNCF Ambassadors.

CNCF Staff: This is a blog written by a CNCF staff member. If the staff member is writing a blog on behalf of a project or a SIG, it is classified as a project or SIG project.

Community member: This is a blog written by a member of the community. CNCF accepts community member blogs on topics like event experiences or diversity topics. If a community member writes a blog on behalf of a project or SIG, it is classified as a project or SIG blog.

**Comment by cjyabraham** [comment]
Thanks Kim.  As we discussed, I've transposed this request into our functional spec for the new site.  I'll close out this issue for now and we can track it there.
