### ISSUE TITLE
Add our new Video Lake tool to cncf.io

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#180]
We have a new video tool for search and indexing. I would like this link and a short description on the home page, preferably above the fold, to advertise this new tool.

Also in the Newsroom drop down after the Video menu item.

Link: https://videos.cncf.io/

If you want to see more information on the tool, see the [draft blog post](https://docs.google.com/document/d/1YRzM6EmrDKMre5LFZWA4cTosvQPr8X4ole3MA-ypIjw/edit?usp=sharing) for details on the tool

**Comment by cjyabraham** [comment]
@deigolocco can your team design something for this please?  We'll get feedback on the design and, once approved, you can implement.

**Comment by rodmeurer** [comment]
Hi @KimMcMahon @cjyabraham we did three versions for it.

01 is a card fixed on scrolling
02 is a pop-up window 
03 is more discreet, just a bar below the hero image.

let us know if one of this works for you.

![Video-Lake-Add01](https://user-images.githubusercontent.com/54405402/76899234-e6bf9900-6875-11ea-929d-57373f822e88.jpg)
![Video-Lake-Add02](https://user-images.githubusercontent.com/54405402/76899437-47e76c80-6876-11ea-942b-4170db4d1ba5.jpg)
![Video-Lake-Add03](https://user-images.githubusercontent.com/54405402/76899554-8b41db00-6876-11ea-8211-ba5f61d67279.jpg)

**Comment by cjyabraham** [comment]
I think maybe option 3, except below the "Building Sustainable Ecosystems..." paragraph.  @KimMcMahon what do you think?

**Comment by dankohn** [comment]
Less is more. I also think we want to promote the service, not their brand name.

**Comment by KimMcMahon** [comment]
I agree with Dan and Chris. Option 3.

Remove "Video Lake" from the first sentence.

Change the remaining text to:
CNCF has added a powerful search and indexing tool for our KubeCon + CloudNativeCon Europe and North America 2019 videos.
Try it out and let us know what you think. (link info@cncf.io or my email address).

**Comment by pablodelarocha** [comment]
Ok! Here's the updated design. Also, i'm sending a variation with the bar below the "Building Sustainable Ecosystems..." paragraph as suggested by Chris, but in that case it would be below the fold.
![Video-Lake-Add_2](https://user-images.githubusercontent.com/54405572/76961114-8d01b200-68fb-11ea-9876-f8f9dfac52ec.jpg)

![Video-Lake-Add](https://user-images.githubusercontent.com/54405572/76960410-2760f600-68fa-11ea-8e69-dd05f7dc80f6.jpg)

**Comment by cjyabraham** [comment]
I think if it goes below it might benefit from having just a solid background color so it doesn't compete with the gradient of the numbers block below it...

**Comment by pablodelarocha** [comment]
@cjyabraham ok, here's some color variations for the bar below the fold. 

![04](https://user-images.githubusercontent.com/54405572/76966477-cee32600-6904-11ea-8bf5-f0f5b2452260.jpg)
![03](https://user-images.githubusercontent.com/54405572/76966649-1073d100-6905-11ea-9f11-438b4499c053.jpg)
![01](https://user-images.githubusercontent.com/54405572/76966842-5466d600-6905-11ea-89e3-b84a22444030.jpg)
![02](https://user-images.githubusercontent.com/54405572/76967115-b9223080-6905-11ea-8cc2-147dfdd5e2e8.jpg)

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha! I think the gray stands out the most.

**Comment by rodmeurer** [comment]
@KimMcMahon can we proceed to implement  the gray bar?

**Comment by KimMcMahon** [comment]
@cjyabraham Can @rodmeurer proceed with implementation?

**Comment by cjyabraham** [comment]
Sounds great!

**Comment by rodmeurer** [comment]
@cjyabraham @KimMcMahon here it is, let us know if it's ok.

https://fz-180-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
- Could you make the "let us know what you think" link and "Learn More" button open in new tabs?
- Can you decrease the vertical padding a bit between the "New Tool" badge and "Find your favorite..." text on mobile?
<img width="350" alt="Screen Shot 2020-03-25 at 12 12 00 PM" src="https://user-images.githubusercontent.com/463160/77501088-df117d00-6e91-11ea-868b-74f394585012.png">

**Comment by rodmeurer** [comment]
@cjyabraham updated.
https://fz-180-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
Looks good!  @KimMcMahon ok to launch?

**Comment by KimMcMahon** [comment]
Yes - please launch!

**Comment by cjyabraham** [comment]
This is deployed.

@KimMcMahon do you think "Explore Videos" might be a better label for the button instead of "Learn More"?

**Comment by KimMcMahon** [comment]
@cjyabraham I agree! "Explore Videos".

Thanks and it looks great!

**Comment by cjyabraham** [comment]
Ok, this has been updated.
