### ISSUE TITLE
Events We're At homepage images

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#181]
Can we get an image for the homepage for [Promcon](https://www.cncf.io/events-well-be-at/promcon-2020/)?  
<img width="594" alt="Screen Shot 2020-03-20 at 11 50 47 AM" src="https://user-images.githubusercontent.com/463160/77134260-261dfd80-6aa1-11ea-93bd-7a11c2a25d6c.png">

And also one for [Kubernetes Forum Tokyo 2020](https://www.cncf.io/events-well-be-at/kubernetes-forum-tokyo-2020/).

I think all upcoming events should be required to have a homepage image so that when they appear on the homepage they don't show up with a blank square.

cc @KimMcMahon as an FYI.

**Comment by pablodelarocha** [comment]
@cjyabraham Sure! I already had sent the banners for PromCon, but here they are again:
![promcon_square](https://user-images.githubusercontent.com/54405572/77164241-9b340780-6a8e-11ea-86c1-ee6280f1eb29.jpg)
![promcon_wide](https://user-images.githubusercontent.com/54405572/77164250-9ec78e80-6a8e-11ea-8c08-265e4f506fa0.jpg)

And here's the Kubernetes Forum Tokyo banners:

![kubernetes_tokyo_square](https://user-images.githubusercontent.com/54405572/77164313-b69f1280-6a8e-11ea-8d9d-96fb927399ef.jpg)
![kubernetes_tokyo_wide](https://user-images.githubusercontent.com/54405572/77164317-b7d03f80-6a8e-11ea-96de-094cd89f11a7.jpg)

**Comment by KimMcMahon** [comment]
Completed!
