### ISSUE TITLE
Images for Events We'll Be At Page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#183]
Hi @pablodelarocha 
Can I get these images today for our Events we'll be at page?

https://cloudnativesummit.online/
https://info.d2iq.com/20-04-01-d2iq-virtual-summit-registration.html

Thank you!

**Comment by pablodelarocha** [comment]
Sure @KimMcMahon here's both banners on two sizes:

![Cloud-Native-Summit-Online-wide](https://user-images.githubusercontent.com/54405572/77577686-f8c4bb80-6eb5-11ea-8cec-f8533fc5d166.jpg)
![Cloud Native Virtual Summit featuring Kubernetes Wide](https://user-images.githubusercontent.com/54405572/77577694-fc584280-6eb5-11ea-8696-63f12cafc31b.jpg)
![Cloud Native Virtual Summit featuring Kubernetes_square](https://user-images.githubusercontent.com/54405572/77577701-fe220600-6eb5-11ea-815f-922154722aba.jpg)
![Cloud-Native-Summit-Online_square](https://user-images.githubusercontent.com/54405572/77577704-feba9c80-6eb5-11ea-963d-791160bb3850.jpg)

**Comment by KimMcMahon** [comment]
Thank you!
