### ISSUE TITLE
Images for "Events we'll be at page"

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#185]
Hello @pablodelarocha!
Can you create the featured images (square and rectangle) for these events?
Thank you!!!

https://nats.io/nats_connect/ 
https://www.writethedocs.org/conf/portland/2020/news/init/
https://events.linuxfoundation.org/cloud-native-security-day/
https://www.allthetalks.org/
https://konghq.com/events/destination-decentralization/

**Comment by pablodelarocha** [comment]
Sure @KimMcMahon 
Here's the two banners for all 5 events:

![Destination_square](https://user-images.githubusercontent.com/54405572/79134701-83495e00-7d84-11ea-8449-59e517f31c41.jpg)
![AllTheTalks_square](https://user-images.githubusercontent.com/54405572/79134708-85132180-7d84-11ea-9fa7-3962119f5679.jpg)
![Destination_wide](https://user-images.githubusercontent.com/54405572/79134710-85abb800-7d84-11ea-852f-3bb718e99675.jpg)
![AllTheTalks_wide](https://user-images.githubusercontent.com/54405572/79134712-86444e80-7d84-11ea-9ca9-ce7d50234154.jpg)
![nats_square](https://user-images.githubusercontent.com/54405572/79134715-86dce500-7d84-11ea-88de-459fcb7bee1d.jpg)
![Nats_wide](https://user-images.githubusercontent.com/54405572/79134717-87757b80-7d84-11ea-80b0-b5afa660da01.jpg)
![CNSecurityDay_square](https://user-images.githubusercontent.com/54405572/79134719-87757b80-7d84-11ea-8be0-4897606715d6.jpg)
![CNSecurityDay_wide](https://user-images.githubusercontent.com/54405572/79134721-880e1200-7d84-11ea-8919-c3b38a6f7cf0.jpg)
![writethedocs_square](https://user-images.githubusercontent.com/54405572/79134723-88a6a880-7d84-11ea-8416-1c8c50162cd8.jpg)
![writethedocs_wide](https://user-images.githubusercontent.com/54405572/79134725-88a6a880-7d84-11ea-9679-e2871f1325dc.jpg)

**Comment by KimMcMahon** [comment]
Thanks @pablodelarocha !
