### ISSUE TITLE
Speakers Bureau email updates

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#187]
Write SB emails to support the following process:
For speakers currently in the speakers bureau that are missing info, I suggest we do this:
1. Deactivate the account with a message explaining why it has been deactivated and, if they would like to be in the speakers bureau, they should email and ask to be re-activated.
2. They would email you asking for re-activation.
3. You re-activate, which sends a message to them asking them to fill in key information.
4. After 30 days or so you repeat the review of speakers info to catch any remaining offenders.  Over time these should become very few.

For brand new speakers signing up, I suggest we require all the fields that we can on the registration form.  The only one that we can't is the photo, but they need to add a photo in order to be shown in the speakers bureau, so there's a clear incentive for them to do that.  The approval email can tell them this.

Drop this requirement "At least one of the social profiles: GitHub, Twitter, or LinkedIn" as it's hard to test for that in a form.

Copy all changes over to CNCFCI site.

**Comment by cjyabraham** [comment]
@KimMcMahon I have updated the following emails:
- [account approved email](https://www.cncf.io/wp-admin/admin.php?page=um_options&tab=email&email=approved_email)
- [account deactivated email](https://www.cncf.io/wp-admin/admin.php?page=um_options&tab=email&email=inactive_email)

I have also updated [the registration page](https://www.cncf.io/speakers/register/) to require all required fields from the outset.

Any comments?  Once approved, I'll copy over the changes I've made to our new rebuilt site.

**Comment by KimMcMahon** [comment]
Looks great! Thanks Chris!

**Comment by cjyabraham** [comment]
This has been copied over to the CNCFCI site.
