### ISSUE TITLE
Technology Spotlight on homepage

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#188]
We want a new section on the homepage for a Technology Spotlight.  See the mockup attached.  

We will always have three blocks up, titled MAINTAINER, AMBASSADOR, PROJECT.  The image and the description text need to be configureable in each.  The image and "READ MORE" button needs to be configurable to link to a blog post.  

Please implement this in whatever way is easiest and allows for the configurability that we need.
<img width="1113" alt="Screen Shot 2020-04-23 at 9 42 30 PM" src="https://user-images.githubusercontent.com/463160/80105573-5d556200-85ab-11ea-8ab4-8449ffd6a8c7.png">

**Comment by cjyabraham** [comment]
Please also add the following paragraph directly below the "Technology Spotlight" title:

> Every month we highlight the best of the cloud native open source community to give thanks to those involved as well as inspire and motivate.

**Comment by rodmeurer** [comment]
@cjyabraham it's done.

The custom fields on this page are created in WPAdmin, so when deployed they must be replicated for production environment. Let us know to create it.

https://fz-188-cncf.pantheonsite.io

**Comment by cjyabraham** [comment]
Thanks.  First, can we change the background color to grey so it looks like this:
<img width="1324" alt="Screen Shot 2020-04-28 at 10 19 25 PM" src="https://user-images.githubusercontent.com/463160/80498652-93755600-899e-11ea-9b72-1febab0fbc17.png">

And place the section in between the numbers countup section and the "What is CNCF?" section.

Finally, can you decrease the vertical height of the section somewhat so it take up less space and is more like the mockup?

**Comment by rodmeurer** [comment]
@cjyabraham must the title change to "Maintainer, Ambassador, and Project Spotlight" as on the image above?

**Comment by caniszczyk** [comment]
maybe "Community Spotlight" is better"

**Comment by cjyabraham** [comment]
@rodmeurer let's go with "Community Spotlight" then.  Thanks.

**Comment by rodmeurer** [comment]
Adjusted @cjyabraham can you check if it's better now?

https://fz-188-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
Looking good.

Can you make the "Text about project" text in the PROJECT section the same size as the description in the other sections?

Can you make it so that the section can be hidden?  As I'm not sure if all the content is ready yet.

What do we need to do to launch this?  Do you need to add the fields at the same time I deploy the code?

**Comment by cjyabraham** [comment]
One other thing: can you style the buttons the same as the other pink buttons on the page?  So same font, same color, etc?

**Comment by rodmeurer** [comment]
Fixed the text in Projects and button's style @cjyabraham 

We created a checkbox to hide the section and created the fields in production already, so you can deploy anytime.

**Comment by cjyabraham** [comment]
Almost there: Can you make the images a link as well as the button?

**Comment by cjyabraham** [comment]
Thanks.  Deployed.

**Comment by cjyabraham** [comment]
@rodmeurer I've deployed this to the live site but I'm not able to get the section to show.  You can try [editing it here](https://www.cncf.io/wp-admin/post.php?post=27434&action=edit) and unchecking "Hide this section".  Is there something else we need to do to make it work?

Note: if you do get it to work please don't leave it visible as it's just test data there right now.

**Comment by fuerzastudio** [comment]
@cjyabraham Sorry about that, there was a misspelling in the field name. We've fixed it and the section remains hidden.

**Comment by cjyabraham** [comment]
That works.  Thanks for the quick fix.
