### ISSUE TITLE
Add blurb to newsletter forms

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#189]
Add this blurb below both newsletter forms: [at the bottom of the homepage](https://www.cncf.io/) and [on this page](https://www.cncf.io/newsroom/newsletter/):

`By submitting this form, I acknowledge that my information is subject to <a href="https://www.linuxfoundation.org/privacy/">The Linux Foundation’s Privacy Policy.</a>`

**Comment by rodmeurer** [comment]
@cjyabraham updated. The second page (/newsletter), if you approve, must be updated in WP Admin also when deployed.. 

https://fz-189-cncf.pantheonsite.io/

https://fz-189-cncf.pantheonsite.io/newsroom/newsletter/

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
