### ISSUE TITLE
Improperly formatted webinar date and time breaks Add to Calendar function

### ISSUE THREAD

**Issue by thetwopct** [cncf/wordpress-site#190]
On upcoming webinars, the time of the webinar is being incorrectly parsed and converted to an invalid ISO format, and preventing the Add to Calendar button from properly displaying with JS console error of `RangeError: Invalid Date`.

![20200601180618-CNCF Member Webinar: 20,000 Upgrades Later, Lessons From a Year of Managed Kubernetes Upgrades - Cloud Native Computing Foundat…](https://user-images.githubusercontent.com/10615884/83434537-9991a300-a432-11ea-9501-16db702388f0.jpg)

Example: https://www.cncf.io/webinars/trivy-open-source-scanner-for-container-images-just-download-and-run/

Because of the way we collect the time (text field) this can lead to issues. For the new site, I've re-worked how we handle dealing with the field and adding in additional checks for validity, you can find the reworked function here https://github.com/cncf/cncf.io/blob/47f5185eb0a75c4d7d60855e8955495fb3e26627/web/wp-content/themes/cncf-theme/classes/class-cncf-utils.php#L77

**Comment by cjyabraham** [comment]
@deigolocco please find a quick fix for the current site.  As mentioned, we'll be doing things differently in the new site but just need something to fix this for the current site for the next couple of months.

**Comment by cjyabraham** [comment]
@deigolocco hold off for now fixing this.  I figured out that the editor just needs to include spaces around the hyphen for the times so this will be adequate for now.

**Comment by cjyabraham** [comment]
This is still broken in Safari at least.  Reopening...

**Comment by cjyabraham** [comment]
Thanks.  Deployed.
