### ISSUE TITLE
Description not accurate for Backstage incubating project

### ISSUE THREAD

**Issue by anthonydahanne** [cncf/wordpress-site#192]
Hello,
In the page visible at: https://www.cncf.io/projects/ , we can see under Backstage:

<img width="539" alt="Screenshot 2023-02-15 at 22 24 09" src="https://user-images.githubusercontent.com/60938/219260910-c0afb39a-adb5-4ed8-abff-38ac95292b31.png">

but the description is wrong; it's not  "Application Definition & Image Build" but rather "Backstage is an open platform for building developer portals" as properly indicated in its own page , https://www.cncf.io/projects/backstage/

<img width="956" alt="Screenshot 2023-02-15 at 22 24 49" src="https://user-images.githubusercontent.com/60938/219261083-33181f71-f62e-4baf-9a80-d56f3929c872.png">

**Comment by cjyabraham** [comment]
Thanks for the suggestion. Could you open an issue in [the CNCF Landscape repo](https://github.com/cncf/landscape)? All the project data shown on the CNCF site is pulled from there.
