### ISSUE TITLE
Possible issue with Google Analytics

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#21]
I've pulled blog stats for April, May, June, and July. Total blog views for April, May, and June are very low - approximately 300 for the month. Total blog views for July are nearly 4,000. 

I suspect an issue with Google Analytic page view counts.

Stats are [here](https://docs.google.com/spreadsheets/d/1doEHIIhlbLvVGySbgnzkWL15Di73LVrSMNyCa-Ruyz4/edit?usp=sharing), News and Blog Calendar tab.

**Comment by cjyabraham** [comment]
Where are you getting this data from?  My view of Google Analytics shows pageviews from 25000-40000 for all of those months:
<img width="1250" alt="Screen Shot 2019-08-06 at 10 28 30 AM" src="https://user-images.githubusercontent.com/463160/62509330-ffbe9100-b834-11e9-8afd-41faf3fc45d5.png">

**Comment by KimMcMahon** [comment]
The stats were for individual blogs. I just ran a quick report again and the numbers are at a more expected page view. I'll investigate more today.
