### ISSUE TITLE
Implement site-wide banner

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#22]
Make it configurable via the admin so that the text can easily be changed.  Mockups attached.
<img width="1208" alt="Screen Shot 2019-08-08 at 9 14 50 AM" src="https://user-images.githubusercontent.com/463160/62670352-24457500-b9bd-11e9-8f14-c1ddfb52423c.png">

**Comment by cjyabraham** [comment]
@deigolocco has work started on this and do you have an ETA for Lindsay on when it will be ready?

**Comment by deigolocco** [comment]
the bar is implemented https://fuerza-cncf.pantheonsite.io/
We created an option page to edit the bar, enable and disable it too.
![Captura de Tela 2019-08-15 às 19 49 44](https://user-images.githubusercontent.com/5631313/63133964-cfe25c80-bf9d-11e9-96e6-7d9c349f438f.png)
This option page can be used for more global features if necessary.

**Comment by deigolocco** [comment]
We used provisionally the textarea field because the wysiwyg editor was presenting a bug. We'll investigate and fix tomorrow, so we can replace.

**Comment by deigolocco** [comment]
Bug fixed, was conflict with the plugin Cool Timeline Pro. Good to go.
<img width="1378" alt="Captura de Tela 2019-08-16 às 15 59 24" src="https://user-images.githubusercontent.com/5631313/63191648-66b32580-c03f-11e9-9377-7b380262e2e5.png">

**Comment by dankohn** [comment]
Your bar has significantly more top and bottom margin than the mockup. Could you also try removing some of the black top and bottom margin from the menubar so that the two together take up the same amount of vertical space as just the menubar today?

Also, as a second step after we deploy this, can you add an `x` that makes the banner dismissable?

**Comment by dankohn** [comment]
Also, the link needs to go to https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/.

**Comment by lindsayshaw** [comment]
Hi Diego, 3 things from me: 

1. Confirm the "learn more" is white and turns purple when someone engages with the link? 

2. On mobile (iOS), there is a shaded area when the text breaks to 3 lines, and the link is not clickable in that shaded area. 
![Image from iOS-2](https://user-images.githubusercontent.com/54188398/63193349-1a0d2180-c022-11e9-8032-e93e08d2e506.jpg) 

3. > Also, the link needs to go to https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/.

I'd like to track how this link performs (site referral traffic/conversions) in google analytics. We could use the below custom url, or I'm open to suggestions. Maybe @cjyabraham has a better way to do this using Google Tag Manager? 

https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/?utm_source=cncf.io&utm_medium=nav&utm_campaign=kccncna19

**Comment by KimMcMahon** [comment]
@lindsayshaw Link updated to the tracking link.

**Comment by deigolocco** [comment]
@dankohn the user should be able to close the banner? If yes, would be good to save a cookie for the session to avoid the banner open in other pages, because it's global.

**Comment by dankohn** [comment]
I opened a new issue for that: https://github.com/cncf/wordpress-site/issues/40

**Comment by deigolocco** [comment]
@dankohn padding was reduced. The close button will be implemented on Monday, I'll reply on  issue #40.

@lindsayshaw 
1 - Yes, mobile has the same hover color but on click. We can change if necessary
2 - fixed
3 - Copy and link are editable http://cncf.fuerza/wp-admin/admin.php?page=acf-options

**Comment by cjyabraham** [comment]
@deigolocco the bar seems to make the drop-down menu too long now.  When I open `Projects | Incubating Projects`, I can no longer scroll to the bottom.

@lindsayshaw I think that custom url would work for tracking clicks from this banner.

**Comment by deigolocco** [comment]
@cjyabraham menu height adjusted

**Comment by cjyabraham** [comment]
The menu no longer looks flush with the bottom of the page.  Also, the purple follow color is hard to read against the pink background:

<img width="1028" alt="Screen Shot 2019-08-19 at 11 29 38 AM" src="https://user-images.githubusercontent.com/463160/63239279-b7f82a80-c274-11e9-85d4-5654a6f8c8b8.png">

**Comment by deigolocco** [comment]
adjusted @cjyabraham

**Comment by cjyabraham** [comment]
Thanks Diego.  I think it's almost there...

The text size varies depending on the page you're on.  [Here](https://fuerza-cncf.pantheonsite.io/services-for-projects/) it's larger than [here](https://fuerza-cncf.pantheonsite.io/about/contact/) for example.  Could you make it consistent.

**Comment by deigolocco** [comment]
adjusted @cjyabraham. We have duplications of css causing this inconsistence. I believe would be great we consolidate all common css in a single file.

**Comment by cjyabraham** [comment]
The presence of the banner removes some whitespace from the top of all page content.  It's [particularly problematic here](https://fuerza-cncf.pantheonsite.io/?s=test) as you can see the "Results for" actually touches the top menu when the page loads.  Can this be corrected across all pages?
<img width="523" alt="Screen Shot 2019-08-20 at 12 46 00 PM" src="https://user-images.githubusercontent.com/463160/63320607-8355a300-c348-11e9-8d1b-87b902c87b10.png">

**Comment by deigolocco** [comment]
@cjyabraham adjusted

**Comment by cjyabraham** [comment]
LGTM.  Is this ready to deploy?  I see you got rid of the close "X"?

**Comment by deigolocco** [comment]
adjusted @cjyabraham, we hide the 'x' now, we wanna to aprove the banner first.
After banner approved we'll activate the 'x' and respond at issue #40

**Comment by cjyabraham** [comment]
Mobile banner still seems to take up more vertical real-estate than it needs to but I'm curious what others think:
![Screenshot_20190824-190923](https://user-images.githubusercontent.com/463160/63637115-d27e3980-c6a2-11e9-8ea8-afe3aac92054.png)

@lindsayshaw, @dankohn, @KimMcMahon would you like any further tweaks or are we good to launch?

**Comment by dankohn** [comment]
Let's deploy, please and then try to make it shorter.

**Comment by cjyabraham** [comment]
@deigolocco can you resolve the merge conflicts by pulling in master to your branch, then I'll deploy.

**Comment by deigolocco** [comment]
@cjyabraham merge conflicts adjusted.
The banner demand height be determined, because of menu's position fixed. Tomorrow morning we'll make it shorter for some devices checking the number of characters and adding a new break point, to verify if will break in 2 or 3 lines.

**Comment by cjyabraham** [comment]
I've deployed this but the banner content needs setting.  @deigolocco where do you set this and can you do it for the live site?

**Comment by deigolocco** [comment]
@cjyabraham I added the intructions before, you can manage the bar here https://www.cncf.io/wp-admin/admin.php?page=acf-options. 
We just ajusted the visited color link, could you deploy this please?

**Comment by cjyabraham** [comment]
@deigolocco the banner appears to be pushing down the menu to cover titles again:
<img width="368" alt="Screen Shot 2019-08-27 at 1 00 00 PM" src="https://user-images.githubusercontent.com/463160/63744815-aa711f00-c8ca-11e9-8faf-b0102d1108cd.png">
<img width="375" alt="Screen Shot 2019-08-27 at 12 59 18 PM" src="https://user-images.githubusercontent.com/463160/63744817-aa711f00-c8ca-11e9-8213-76e29a4c4935.png">

**Comment by cjyabraham** [comment]
Could you fix this for the home page as well:
<img width="332" alt="Screen Shot 2019-08-27 at 11 35 07 PM" src="https://user-images.githubusercontent.com/463160/63790377-57778600-c923-11e9-8217-5ffdd859b7a0.png">

**Comment by cjyabraham** [comment]
Also, the menu is hiding "<< All Events" on [this page](https://www.cncf.io/events-well-be-at/gitlab-commit/) and "<< All Webinars" on [this page](https://www.cncf.io/webinars/how-to-choose-right-proxy-architecture-for-micro-services-based-application-delivery/).

**Comment by cjyabraham** [comment]
I'm still seeing the problem:
<img width="297" alt="Screen Shot 2019-08-28 at 12 30 43 PM" src="https://user-images.githubusercontent.com/463160/63828132-b5da4e00-c98f-11e9-8b40-847d9a834916.png">

**Comment by cjyabraham** [comment]
Thanks.  Can you fix the merge conflict and then I'll deploy?

**Comment by deigolocco** [comment]
merge conflicts adjusted @cjyabraham

**Comment by cjyabraham** [comment]
Ok.  Deployed.
