### ISSUE TITLE
Login for a speaker to Speakers Bureau is not easily found

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#24]
The login for Speakers Bureau is only on the [Register](https://www.cncf.io/speakers/register/) page. See image.

It is not intuitive to hit "Click here to learn more about this program." from the [Speakers Bureau page.](https://www.cncf.io/speakers/) 

Please add a login to the Speakers page.

Login button
<img width="1530" alt="Screen Shot 2019-08-08 at 3 16 24 PM" src="https://user-images.githubusercontent.com/29307455/62738592-e6157900-b9ef-11e9-9ce1-b4f5c512c992.png">

Speakers Page
<img width="1508" alt="Screen Shot 2019-08-08 at 3 15 23 PM" src="https://user-images.githubusercontent.com/29307455/62738621-f7f71c00-b9ef-11e9-9385-716d468855b6.png">

**Comment by cjyabraham** [comment]
Where do you want the login button to go?  Alternatively, we could just added a link at the end of the paragraph: "...or, if you've already registered, log in."

**Comment by KimMcMahon** [comment]
@cjyabraham Agree on the sentence. See below.

Update this paragraph
The CNCF Community Speaker’s Bureau helps connect event organizers with speakers with a variety of expertises within the cloud native ecosystem. Speakers consist of CNCF meetup organizers, ambassadors, and prominent community members who are willing to speak at local events on certain topics they are proficient in. Event organizers are welcome to reach out to speakers to invite them to participate in your event. | Learn more about this program.

To:

The CNCF Community Speaker’s Bureau helps connect event organizers with speakers with a variety of expertise within the cloud native ecosystem. Speakers consist of CNCF ambassadors, meetup organizers, and prominent community members who are willing to speak at events on the topics they are proficient in. Event organizers are welcome to reach out to speakers to invite them to participate in your event. | Learn more about this program. | If you are registered, log in.

**Comment by cjyabraham** [comment]
[Done.](https://www.cncf.io/speakers/)

**Comment by cjyabraham** [comment]
What do you think about changing the linked text to something more active:

...Learn more about this program and [sign up](https://www.cncf.io/speakers/register/). If you are registered, [log in](https://www.cncf.io/speakers/login/).

**Comment by KimMcMahon** [comment]
Good idea @cjyabraham. Updated. This issue is complete.
