### ISSUE TITLE
Update the order of fields for each Speaker

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#25]
Requirements documented in [Speakers Bureau Google Doc](https://docs.google.com/document/d/1IUA1O4Zr73cdtBSJQB9mcEdO0lisxWagNEaofICdty0/edit?usp=sharing)

Fields for a profile
Please put in this order:

Bio
Area of expertise
Job category
Job title
Company
Location (Country) (updated based on new Search)
Languages spoken
Github
Twitter
LinkedIn
Website
Twitter
Willing to present via Video Conference
Willing to Travel
Travel Range

NOTE: If the two fields are added, this order will be updated.

**Comment by KimMcMahon** [comment]
@cjyabraham Two additional fields added and fields updated in the Speakers Bureau document.

**Comment by cjyabraham** [comment]
[This is done](https://www.cncf.io/speaker/puja/).
