### ISSUE TITLE
Consider more contrast for text on the website

### ISSUE THREAD

**Issue by nilsmeyer** [cncf/wordpress-site#26]
Using grey text on white background can be very difficult to read, especially on mobile devices. For the benefit of accessibility you should consider using colors with more contrast. 

See also https://contrastrebellion.com/ for more info, including links to studies, on contrast.

**Comment by dankohn** [comment]
Yes, we're happy to make that change. Would you mind including a couple links for the pages that you think are the worst offenders?

**Comment by nilsmeyer** [comment]
Thank you for considering this. It immediately struck me once I opened [https://www.cncf.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/](https://www.cncf.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/), I think the grey on grey on the members page and on some of the community pages also isn't ideal.

**Comment by dankohn** [comment]
I also want to fix the contrast of the "projects" link (and mouseover color) at the top of https://www.cncf.io and the visited link color on https://www.cncf.io/phippy/. @deigolocco Could you please propose a new design for the default news pages that improves the contrast.

**Comment by deigolocco** [comment]
ok @dankohn

**Comment by deigolocco** [comment]
![Blog](https://user-images.githubusercontent.com/5631313/62941169-cabdbb80-bdab-11e9-9f20-5304275a9e1f.jpg)
![home](https://user-images.githubusercontent.com/5631313/62941174-cee9d900-bdab-11e9-8efc-248bc8f6abc8.jpg)
![Phippy](https://user-images.githubusercontent.com/5631313/62941176-d01b0600-bdab-11e9-85d5-956f9124c6d4.jpg)
![Speaker](https://user-images.githubusercontent.com/5631313/62941180-d1e4c980-bdab-11e9-9124-6c5f1a2ea5c5.jpg)

**Comment by deigolocco** [comment]
@dankohn there are some design proposals

**Comment by dankohn** [comment]
Those look great. Could you please implement on a staging server.

**Comment by deigolocco** [comment]
Thank you @dankohn, sure

**Comment by nilsmeyer** [comment]
I concur, and readability is also improved markedly.

**Comment by deigolocco** [comment]
https://fz-contrast-cncf.pantheonsite.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/
https://fz-contrast-cncf.pantheonsite.io/
https://fz-contrast-cncf.pantheonsite.io/phippy/
https://fz-contrast-cncf.pantheonsite.io/speakers/

**Comment by dankohn** [comment]
Please change the visited links on the regular posts to be visible (maybe purple?)

The visited links on the Phippy buttons are not good:

![image](https://user-images.githubusercontent.com/3083270/63060863-67be4880-bec1-11e9-8fd5-01feda73d09f.png)

Visited link on the homepage is also not distinguishable.

**Comment by deigolocco** [comment]
adjusted

**Comment by dankohn** [comment]
@deigolocco I'd like to have active *and* visited link colors set that are different from the default (I'm fine if they're active and visited are the same).

I'm not seeing visited links as a different color on https://fz-contrast-cncf.pantheonsite.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/.

As I said above, black on dark blue is not a good visited color:

![image](https://user-images.githubusercontent.com/3083270/63116461-b8887c80-bf67-11e9-8ead-dfd7e9821566.png)

There's no hover color on `projects` on https://fz-contrast-cncf.pantheonsite.io and no visited color on the newsroom links.

**Comment by deigolocco** [comment]
@dankohn, we did the adjustments and added the missing things

**Comment by dankohn** [comment]
Looks great. @cjyabraham please merge.

**Comment by cjyabraham** [comment]
Deployed.
