### ISSUE TITLE
Design refresh of speaker tiles

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#27]
from @dankohn : 

> Could we try a design refresh where we show "City, Country" and Areas of Expertise to the right of the picture and make every speaker box the same size? I don't see any reason to highlight Twitter and LinkedIn links from the scrolling page. Instead, it would allow a much denser list of speakers which would be faster to scroll through.

_Originally posted by @cjyabraham in https://github.com/cncf/wordpress-site/issues/9#issuecomment-520223484_

**Comment by cjyabraham** [comment]
closed in favor of #57
