### ISSUE TITLE
add Phippy image to cncf.io 404 page

### ISSUE THREAD

**Issue by alexcontini** [cncf/wordpress-site#31]
We would like to add an image of Phippy to the right of the 404 text (as in the screenshot attached). I have attached the png to use as the Phippy image as well.

<img width="884" alt="Screen Shot 2019-08-08 at 8 38 51 AM (1)" src="https://user-images.githubusercontent.com/27962005/62940346-63027300-bda1-11e9-883c-22ddfb18c2f7.png">

![phippy404](https://user-images.githubusercontent.com/27962005/62940373-6eee3500-bda1-11e9-8992-5d9f69bfe298.png)

**Comment by dankohn** [comment]
Also, please make the Phippy logo a link to https://www.cncf.io/phippy/.

**Comment by deigolocco** [comment]
ok @dankohn

**Comment by deigolocco** [comment]
new 404 page implemented https://fuerza-cncf.pantheonsite.io/345

**Comment by dankohn** [comment]
1. You've cut off the top and bottom of Phippy.
2. Can you please get in the habit of doing each feature on its own branch. Feel free to call it fuerza-31-phippy to make clear that it implements this issue.
3. You missed my comment about making Phippy a link.

**Comment by deigolocco** [comment]
1. fixed
2. sure, we'll do this way now in front
3. sorry, added

**Comment by dankohn** [comment]
You seem to have hardcoded the URL to "https://www.cncf.io/phippy/" but I believe it should be "/phippy/" so as to work correctly on these staging servers.

With that change, it's ready to merge @cjyabraham

**Comment by deigolocco** [comment]
fixed, relative url now

**Comment by cjyabraham** [comment]
@deigolocco what's the status of your fuerza branch and how would you like this deployed.  It seems there are unrelated commits (ab1e99f508).

**Comment by deigolocco** [comment]
@cjyabraham commits adjusted. You can deploy now

**Comment by cjyabraham** [comment]
This has been deployed.  Was it intentional to have Phippy link open in a new tab?

**Comment by dankohn** [comment]
No, I specifically asked that it not. It's supposed to be a relative URL.

**Comment by cjyabraham** [comment]
To be clear, it was a relative url, however it was set to open the link in a new tab.  I have made the change to open the link in the same browser tab.  This is deployed and I think closes this issue.
