### ISSUE TITLE
Add page that lists "Archived" projects

### ISSUE THREAD

**Issue by caniszczyk** [cncf/wordpress-site#33]
We need a new page that lists Archived projects.

It will feature rkt.

**Comment by caniszczyk** [comment]
ideally I'd love to get this up on friday!

cc: @cjyabraham

**Comment by cjyabraham** [comment]
Are you thinking a page [like this](https://www.cncf.io/projects/) which features only "rkt"?  Are there other archived projects?  And then we link it from the Projects drop-down menu, perhaps below "Sandbox Projects"?

As a lower-profile option, we could add an "Archived" band to [this page](https://www.cncf.io/projects/) and list them there?

CCing @alexcontini who will likely be the best one to whip up this page.

**Comment by caniszczyk** [comment]
@cjyabraham yes, I'd like a separate page cncf.io/archived-projects that lists them similar to the page you first linked. I'd keep it low profile, can you get something up for tomorrow?

We would also remove rkt from our incubating project page.

**Comment by alexcontini** [comment]
I created a private page - cncf.io/archived-projects - you just have to be
logged in to view.

Is that what you were thinking, I wasn't sure what else to include so not
sure if it looks too bare...

**Comment by dankohn** [comment]
Alex, please also create a PR with
https://github.com/cncf/artwork/blob/master/examples/archived.md that only
has rkt on it.
--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
<https://www.cncf.io/>
dankohn.com <https://www.dankohn.com/> or book on my calendar: dankohn.com/c
<https://www.dankohn.com/c>

**Comment by caniszczyk** [comment]
That works, thank you

**Comment by alexcontini** [comment]
Great, I created the PR and the https://www.cncf.io/archived-projects/ page
is now live, let me know if there are any issues!

**Comment by cjyabraham** [comment]
I see a few other tasks before this is complete:
- [ ] remove rkt from [the regular projects page](https://www.cncf.io/projects/)
- [ ] remove rkt from the Incubating Project drop-down menu
- [ ] add the new [archived projects page](https://www.cncf.io/archived-projects/) under "Sandbox Projects" in the Projects menu

Is that correct @caniszczyk ?  If so, @alexcontini do you mind implementing at least the first task (you seem the most confident with VC)?  I can do the last two if you'd prefer.

**Comment by dankohn** [comment]
Correct

**Comment by cjyabraham** [comment]
I have made the updates to the menu.  @alexcontini would you please remove rkt from [the regular projects page](https://www.cncf.io/projects/).

**Comment by alexcontini** [comment]
Sounds good. Projects page is updated now: https://www.cncf.io/projects/

**Comment by cjyabraham** [comment]
Sweet thanks.  I'll close out this ticket.  @caniszczyk feel free to reopen if there's anything we missed.
