### ISSUE TITLE
Display number of records being shown

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#35]
Is there a relatively easy way to get the faceted search to show how many records are being displayer? https://www.cncf.io/projects/case-studies/ would show 56 while https://www.cncf.io/projects/case-studies/?_sft_cstudies_project=cni would show 5.

**Comment by cjyabraham** [comment]
Yes, this should be easy.  Where would you like it to say this?  It would be easiest to insert below the filters (e.g. "Showing 12 of 56 case studies")?

**Comment by dankohn** [comment]
Sounds great. How about "Displaying 56 case studies" or "Displaying 12 of 56 case studies".

**Comment by cjyabraham** [comment]
[How's this?](https://chris-dev-cncf.pantheonsite.io/projects/case-studies/)

**Comment by dankohn** [comment]
Looks good, but when you select Hybrid, could it please change to say "Displaying 8 of 56 case studies".

**Comment by cjyabraham** [comment]
[How's this?](https://chris-dev-cncf.pantheonsite.io/projects/case-studies/?_sft_challenge=availability)

**Comment by dankohn** [comment]
Gorgeous. Please ship it. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by cjyabraham** [comment]
[Deployed.](https://www.cncf.io/projects/case-studies/?_sft_distribution=distribution)
