### ISSUE TITLE
Recorded Webinars: Add a button to attach the webinar presentation

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#37]
Example: On this [page](https://www.cncf.io/webinars/monitoring-kubernetes-workloads-the-sidecar-pattern/), add a button below the video with the text "Download Slides".

The button on the old page design is black with purple text. Please design the new button so the text "Download Slides" has more contrast and is easily readable.

**Comment by KimMcMahon** [comment]
Dependent on getting new Webinar page (combined Upcoming and Recorded) into one page.

**Comment by deigolocco** [comment]
It already exist @KimMcMahon
