### ISSUE TITLE
Redirect from old webinar URL to new webinar URL

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#38]
Redirect from the old URL
https://www.cncf.io/community/webinars/monitoring-k8s-workloads-sidecar-pattern/

to the new URL
https://www.cncf.io/webinars/monitoring-kubernetes-workloads-the-sidecar-pattern/

**Comment by KimMcMahon** [comment]
Dependent on getting new Webinar page (combined Upcoming and Recorded) into one page.

**Comment by deigolocco** [comment]
all redirects set at https://new-webinar-cncf.pantheonsite.io/, when @cjyabraham deploy will be working on production as well

**Comment by cjyabraham** [comment]
@deigolocco just so you know, we have the [Redirection plugin installed](https://www.cncf.io/wp-admin/tools.php?page=redirection.php) which might be easier than a code change for future redirects.

**Comment by cjyabraham** [comment]
I've added the redirect to the [Redirection plugin](https://www.cncf.io/wp-admin/tools.php?page=redirection.php).
