### ISSUE TITLE
Select hero image for cncf.io

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#41]
Andy, I'd like your help selecting a hero image for the top of cncf.io that we could also use on the first page of the Overview Deck: https://docs.google.com/presentation/d/1BoxFeENJcINgHbKfygXpXROchiRO2LBT-pzdaOFr4Zg/edit#slide=id.p4

Also, do you think we should apply any filters to it?

Here are some of the better shots from Barcelona:
https://www.flickr.com/photos/143247548@N03/46985432495/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/46985432955/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/47849409842/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/40941130583/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/40941249433/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/47855793892/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/48302055702/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/48302059237/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/48301943821/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/48302110141/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/48302285382/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/48302285062/in/album-72157707188120301/

**Comment by andycochran** [comment]
I'd suggest using [this one](https://www.flickr.com/photos/143247548@N03/47855793892/in/album-72157707188120301/) with the following styles…

```
.hero-banner-section {
  background-image: url(https://live.staticflickr.com/65535/47855793892_24e3ba75b2_b.jpg);
  background-color: rgba(15, 20, 51, 0.6);
  background-blend-mode: darken;
}

.hero-banner-section .text-wrap {
   text-shadow: 0px 4px 8px black;
}
```

![image](https://user-images.githubusercontent.com/409279/63217505-55d4e380-c115-11e9-89cd-940899d98871.png)

**Comment by dankohn** [comment]
Thanks. What's your #2 choice, as I'd rather not use one with me in it.

**Comment by dankohn** [comment]
Could you please mockup this one? https://www.flickr.com/photos/143247548@N03/48302285382/in/album-72157707188120301/

**Comment by cjyabraham** [comment]
One idea I had is to use this photo at the top of the homepage and, rather than having the text on top of the image, have it below the image:
<img width="1440" alt="Screen Shot 2019-08-18 at 9 48 58 AM" src="https://user-images.githubusercontent.com/463160/63219517-895b5080-c19d-11e9-87a8-6a2734d54100.png">

**Comment by KimMcMahon** [comment]
The image @cjyabraham suggested is used in a lot of places. I prefer the image Dan or Andy suggested. Dan I don't see in the image Andy selected with the text.

Other favorites to consider:
https://www.flickr.com/photos/143247548@N03/46985432495/in/album-72157707188120301/
https://www.flickr.com/photos/143247548@N03/48302059237/in/album-72157707188120301/

**Comment by andycochran** [comment]
Oh, I didn't even notice you were in that one, Dan. 

Here's the image you suggested: 

![image](https://user-images.githubusercontent.com/409279/63228575-f6cda800-c1c2-11e9-81c1-5280b76fb965.png)

It's very… "Ooh, look at that hat and scarf." Tho it does work well with the gradient that follows it. I still think the first one I mocked up looks best. But if you like this better, it uses slightly different effects: 

```
.hero-banner-section {
    background-image: url(https://live.staticflickr.com/65535/48302285382_99180a1df3_b.jpg);
    background-color: rgba(15, 20, 51, 0.5);
    background-blend-mode: saturation;
}

.hero-banner-section .text-wrap {
   text-shadow: 0px 4px 8px black;
}
```

**Comment by andycochran** [comment]
This one makes the text quite hard to read. Don't you think it focuses too much on behind-the-scenes AV tech of the event? The consoles are distracting and oddly almost symmetrical (but not). I like the photos where there's more going on towards the sides. 

![image](https://user-images.githubusercontent.com/409279/63228643-deaa5880-c1c3-11e9-9581-924d3e65fd7e.png)

**Comment by andycochran** [comment]
This one is also awkward how the text overlaps the screen. 

![image](https://user-images.githubusercontent.com/409279/63228696-93447a00-c1c4-11e9-810d-1c79a6eb2cf9.png)

**Comment by dankohn** [comment]
@andycochran Your favorite is the best out of those. Chris, could you please mockup your version.

**Comment by cjyabraham** [comment]
@andycochran will mockup my idea.

**Comment by cjyabraham** [comment]
@dankohn, @andycochran and I discussed smudging you out so you're not recognizable in the first one if you'd rather not be in it.  But really, we both had to look hard to find you in the first place so maybe it's not as much of an issue than you might think.

**Comment by andycochran** [comment]
Meh. 

![image](https://user-images.githubusercontent.com/409279/63311183-4eefd180-c2cb-11e9-88cb-7e119c89ae5e.png)

**Comment by andycochran** [comment]
![image](https://user-images.githubusercontent.com/409279/63311278-924a4000-c2cb-11e9-99e1-f712c9e0d2ef.png)

**Comment by dankohn** [comment]
I'd like to go with the final one, please. Could you please implement? 

Separately, could we use that image in place of the cover image on our standard slides: https://docs.google.com/presentation/d/1BoxFeENJcINgHbKfygXpXROchiRO2LBT-pzdaOFr4Zg/edit#slide=id.g39c264972c_182_212

**Comment by cjyabraham** [comment]
Implemented and [deployed](https://www.cncf.io) as discussed.
