### ISSUE TITLE
Remove "Click Here"

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#42]
Please remove "Click Here" and instead make the text "I have questions. Can someone contact me?" clickable.

![image](https://user-images.githubusercontent.com/3083270/63218016-f54aa400-c11e-11e9-80a5-f0f5c4b0e68f.png)

**Comment by KimMcMahon** [comment]
End User Community [page](https://www.cncf.io/people/end-user-community/)

**Comment by cjyabraham** [comment]
Done.
