### ISSUE TITLE
Broken icon

### ISSUE THREAD

**Issue by lucperkins** [cncf/wordpress-site#44]
The "Read More" icon on the blog is broken. Not a new problem but I figured I should register it here.

<img width="201" alt="Screen Shot 2019-08-19 at 11 20 43 AM" src="https://user-images.githubusercontent.com/1523104/63289249-83d03a00-c273-11e9-9303-600f698aa05a.png">

**Comment by dankohn** [comment]
On https://www.cncf.io/newsroom/blog/ and https://www.cncf.io/newsroom/in-the-news/ and https://www.cncf.io/newsroom/announcements/.

**Comment by deigolocco** [comment]
Fixed
https://fz-icons-cncf.pantheonsite.io/newsroom/blog/
https://fz-icons-cncf.pantheonsite.io/newsroom/in-the-news/
https://fz-icons-cncf.pantheonsite.io/newsroom/announcements/

**Comment by cjyabraham** [comment]
@lucperkins can you confirm this is fixed and then I'll deploy?

**Comment by KimMcMahon** [comment]
@cjyabraham I reviewed. This is fixed. Please deploy.

**Comment by cjyabraham** [comment]
@deigolocco there's a merge conflict when I try to merge with master.  Could you resolve this on your branch by merging master with it and then I'll deploy?

**Comment by rodmeurer** [comment]
@cjyabraham solved!

**Comment by cjyabraham** [comment]
Deployed.
