### ISSUE TITLE
Enable code snippets in blog posts

### ISSUE THREAD

**Issue by lucperkins** [cncf/wordpress-site#45]
As far as I know, there's currently no way to add code snippets to blog posts (or other pages on the site). For [this blog post](https://www.cncf.io/blog/2018/10/24/grpc-web-is-going-ga/), for example, I embedded GitHub Gist snippets but the styling is off. I'd strongly recommend using a WordPress plugin to allow content authors to add code snippets natively.

**Comment by cjyabraham** [comment]
Closing [in favor of this](https://github.com/cncf/cncf.io/issues/10).
