### ISSUE TITLE
contrast for low visibility users on the blog

### ISSUE THREAD

**Issue by parispittman** [cncf/wordpress-site#46]
https://www.cncf.io/blog/2019/08/06/open-sourcing-the-kubernetes-security-audit/
looks like specifically this page and possibly others doesn't have sufficient contrast for low visibility users. 

using https://webaim.org/resources/contrastchecker/ to check contrast.

**Comment by dankohn** [comment]
I believe we resolved last week: https://github.com/cncf/wordpress-site/issues/26

**Comment by parispittman** [comment]
even better - im filing on behalf of someone that had this issue. will follow up with them and respond if there is anything additional to add.

**Comment by cjyabraham** [comment]
I'll close this for now.  @parispittman feel free to re-open if you find there's something else that needs improving.
