### ISSUE TITLE
Add results counts for Events We're At and Webinars search

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#47]
See how the results are on the [case studies](https://www.cncf.io/projects/case-studies/) page.  It says "Displaying 56 case studies" and once you filter it says "Displaying _x_ of _y_ case studies".

Please implement the same functionality for the Events We're At search and the Webinars search.

**Comment by deigolocco** [comment]
added @cjyabraham 
https://new-webinar-cncf.pantheonsite.io/webinars/
https://new-webinar-cncf.pantheonsite.io/events-well-be-at/
