### ISSUE TITLE
Test Salesforce web-to-lead forms

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#48]
@ccraigross Could we please get your help testing whether web-to-lead forms will do what we need. They're limited to 500 forms per day, but I believe that's a per-form limitation, which would be per-project in our case.

Could you please create a form that asks for First, Last, and email and submits into a new test list (which we can later delete). 

These [directions](https://help.salesforce.com/articleView?id=setting_up_web-to-lead.htm&type=5) make it seem pretty easy.

And then this [page](https://www.formstack.com/blog/2019/salesforce-web-to-lead-limitations/) talking about limitations also doesn't seem bad, as it's just saying that you need to manually style the HTML form, which of course we're happy to do.

If this works, we could likely send people off to a different page to fill out this [form](https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/sponsor/) or consider it as an iframe or use the same web-to-form functionality.

**Comment by ccraigross** [comment]
Hi @dankohn. I will flag this request with Marijana on Monday. We have been exploring options for our forms and appear to have found a solution that is straight HTML, it just requires a bit more testing but it would enable us to not have to leverage iframe or Gravity Forms.

**Comment by cjyabraham** [comment]
We will be doing this kind of testing in [this issue](https://github.com/cncf/cncf.io/issues/20).
