### ISSUE TITLE
Social icons different colors

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#49]
Some of the social icons on the Staff page are blue, others are purple. Can all the colors be consistent?

https://www.cncf.io/people/staff/

**Comment by deigolocco** [comment]
@KimMcMahon this icons are links, and we have a general rule at the website to distinguish visited links(with purple) from the not visited ones. We can make the visited links keep blue, please let us know what do you prefer.

**Comment by KimMcMahon** [comment]
Thank you @deigolocco. No need to change. Closing.
