### ISSUE TITLE
CNCF Community Menu Updates

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#5]
Update the Community menu [as described here](https://docs.google.com/document/d/1W5YH0fms_w_vycZH0toBbrKN8F_nya9O9nrXLIAy0mA/edit?ts=5d3f6829#heading=h.5jfz35magu6v).

**Comment by cjyabraham** [comment]
Waiting on Kim for the go-ahead.

**Comment by KimMcMahon** [comment]
@cjyabraham This menu is approved. Please implement.
@alexcontini has a new design for the KubeCon + CloudNativeCon page. This should be implemented

**Comment by KimMcMahon** [comment]
Adding Google Doc documenting the project
https://docs.google.com/document/d/1W5YH0fms_w_vycZH0toBbrKN8F_nya9O9nrXLIAy0mA/edit?usp=sharing

**Comment by KimMcMahon** [comment]
@cjyabraham News KC + CNC + Summit page is up. Please work on implementing the menu.

**Comment by KimMcMahon** [comment]
Note: Alex updated the top menu item to KubeCon + CloudNativeCon & Other CNCF Events

Please make the other menu updates.

**Comment by KimMcMahon** [comment]
Wait for #6 and #8

**Comment by KimMcMahon** [comment]
Note: Changing one menu item. Changing the name of this page from "3rd party event page" to "Events We'll Be At".

**Comment by KimMcMahon** [comment]
@cjyabraham Please update the Community menu


KubeCon + CloudNativeCon & Other CNCF Events
Phippy & Friends
Events We'll Be At
Webinars
Speakers Bureau
Store
Calendar
Infrastructure Lab
Membership
Meetups
Slack
Mailing Lists

**Comment by cjyabraham** [comment]
Webinars is now live.  Waiting for the ok from @KimMcMahon before we can make Events We'll be at live.

**Comment by KimMcMahon** [comment]
@cjyabraham Please make "Event's we'll be at" live and the Community menu.

**Comment by cjyabraham** [comment]
This is now done.
