### ISSUE TITLE
Menus sometimes don't expand in portrait mode

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#50]
@KimMcMahon and I each separately experienced an intermittent bug on our iPhones where clicking the hamburger menu showed the top-level menus, but none of those will expand. The bug occurs in portrait mode while the menus expand when turning to landscape mode. Reloading the page fixed it for me.

**Comment by deigolocco** [comment]
we'll check here @dankohn

**Comment by cjyabraham** [comment]
The mobile menu items on subpages don't seem to work for me.  So if you [go here](https://menu-bug-cncf.pantheonsite.io/about/join/) and then try clicking on a menu item like Projects | Services for Projects, the item lights up pink but you don't go anywhere.  This isn't a problem on the live site.  I've tried this with a Pixel 3a and Galaxy S10.

**Comment by KimMcMahon** [comment]
@deigolocco The item @cjyabraham reported is fixed for me on an iPhone. The issue Dan reported, it still occurs for me. The menu will not expand, but reloading the page fixes the issue and the menu will expand.

**Comment by KimMcMahon** [comment]
I can't reproduce the bug we reported (menu not opening on the iPhone). @dankohn can you test on your iPhone this morning?
https://menu-bug-cncf.pantheonsite.io/

**Comment by dankohn** [comment]
OK, lets call it fixed.

**Comment by cjyabraham** [comment]
Wait, is this fixed on the live site or fixed on https://menu-bug-cncf.pantheonsite.io/ ?  The menu-bug branch has not yet been deployed live.

**Comment by dankohn** [comment]
I couldn't replicate on live.
