### ISSUE TITLE
Change hero image on Webinar page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#52]
We would like more pictures of people at our events in our hero images.

I found a couple for the Webinar page - choose one of these or recommend another image.
https://www.flickr.com/photos/143247548@N03/45581516234/in/album-72157704599428714/
https://www.flickr.com/photos/143247548@N03/45581520604/in/album-72157704599428714/
https://www.flickr.com/photos/143247548@N03/44541981960/in/album-72157704599428714/
https://www.flickr.com/photos/143247548@N03/45635639024/in/album-72157704599428714/
https://www.flickr.com/photos/143247548@N03/46307744522/in/album-72157704599428714/

**Comment by pablodelarocha** [comment]
@KimMcMahon please take a look at the attached banners and let us know if you like any of these so we can add it to the page? Thanks!

![01](https://user-images.githubusercontent.com/54405572/63541008-9c4e8780-c4f3-11e9-9a96-da57f4a8fc38.jpg)
![02](https://user-images.githubusercontent.com/54405572/63541009-9c4e8780-c4f3-11e9-8891-fb0eed2d7173.jpg)
![03](https://user-images.githubusercontent.com/54405572/63541010-9c4e8780-c4f3-11e9-8c3e-8221aa61175e.jpg)
![04](https://user-images.githubusercontent.com/54405572/63541011-9ce71e00-c4f3-11e9-939c-e55cddd85195.jpg)
![05](https://user-images.githubusercontent.com/54405572/63541012-9ce71e00-c4f3-11e9-851a-3ba463bb9744.jpg)

**Comment by dankohn** [comment]
Thanks, but @cjyabraham is going to take care of this one.

**Comment by cjyabraham** [comment]
@KimMcMahon I think for Webinars I like the second one @pablodelarocha has listed above, except to crop it slightly lower to get the woman's full face (see attached for crop).  What do you think?
![45581516234_642085bec9_o](https://user-images.githubusercontent.com/463160/63565843-e0459900-c594-11e9-88ec-c25083921559.jpeg)

**Comment by pablodelarocha** [comment]
![02](https://user-images.githubusercontent.com/54405572/63589076-89cd6000-c57e-11e9-9cdc-4e1b4af8f4ee.jpg)
@cjyabraham here's the fixed image

**Comment by KimMcMahon** [comment]
@cjyabraham Agree. Love the banner. Please replace this on the Webinar page.

**Comment by cjyabraham** [comment]
@pablodelarocha when I cropped it, I rotated it slightly counter-clockwise to get more of the man's face in the photo.  Can you create a new version for us that has this same slight rotation?

**Comment by pablodelarocha** [comment]
![hero_image](https://user-images.githubusercontent.com/54405572/63691819-99e77880-c7e6-11e9-94ac-45e8c8a4d203.jpg)
Sure thing @cjyabraham !

**Comment by cjyabraham** [comment]
LGTM.  @dankohn and @KimMcMahon ?

**Comment by cjyabraham** [comment]
[Deployed](https://www.cncf.io/webinars/).
