### ISSUE TITLE
show "X" on multi-select field chicklets

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#53]
There should be an "X" shown here to allow the user to remove the chicklet:
<img width="646" alt="Screen Shot 2019-09-09 at 8 16 19 PM" src="https://user-images.githubusercontent.com/463160/64533962-c353e880-d33e-11e9-978b-2f938bb82123.png">

**Comment by rodmeurer** [comment]
@cjyabraham up to date! 
 https://fuerza-cncf.pantheonsite.io/speaker/{username}/?um_action=edit
Branch: fz-53

**Comment by cjyabraham** [comment]
@rodmeurer that link doesn't go anywhere for me and I don't see an instance for fz-53?

**Comment by cjyabraham** [comment]
Looks fine.  I'll deploy this when I deploy the rest of fuerza.  If you could, it's often easier to develop individual issues on their own branch so they can be deployed as soon as ready and don't need to wait for any other work.

**Comment by deigolocco** [comment]
isolated in the new environment https://fz-53-cncf.pantheonsite.io/speaker/{username}/?um_action=edit
Pantheon has 10 environments limit, so we deleted the closed ones.

**Comment by cjyabraham** [comment]
Deployed.

**Comment by cjyabraham** [comment]
Can you do this as well on the [registration page](https://www.cncf.io/speakers/register/)?

**Comment by rodmeurer** [comment]
@cjyabraham done at the registraet.

https://fz-53-cncf.pantheonsite.io/speakers/register/

**Comment by cjyabraham** [comment]
deployed
