### ISSUE TITLE
Fix visited color link on button

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#54]
The visited link color on [this button](https://www.cncf.io/speakers/register/) looks bad:
<img width="677" alt="Screen Shot 2019-08-23 at 11 53 10 AM" src="https://user-images.githubusercontent.com/463160/63567646-a2e50980-c59c-11e9-9e7d-6e2a7b59e364.png">

**Comment by deigolocco** [comment]
we'll check @cjyabraham

**Comment by deigolocco** [comment]
adjusted https://fz-contrast-cncf.pantheonsite.io/speakers/register/.

**Comment by cjyabraham** [comment]
This is deployed.

**Comment by cjyabraham** [comment]
Could you do it for this button too on the home page:
<img width="543" alt="Screen Shot 2019-08-25 at 10 50 05 AM" src="https://user-images.githubusercontent.com/463160/63645337-372ea800-c726-11e9-9687-3d313929dfa4.png">

And can you scan through the site for other instances of these buttons?

**Comment by cjyabraham** [comment]
Deployed.

**Comment by cjyabraham** [comment]
Deployed.
