### ISSUE TITLE
Redesign Account page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#55]
Redesign the Speaker's Bureau [account page](https://www.cncf.io/speakers/account/).  

- [x] Figure out why our current page is so malformed. Figure out what the plugin intended as a default (Chris)
- [x] Restore page to its intended design (Diego)
- [ ] Test and refine (Kim and Diego)

**Comment by cjyabraham** [comment]
[Here is how the page is intended to look like](https://ps.w.org/ultimate-member/assets/screenshot-3.png?rev=2007982) however I think our theme is mangling it.  I suggest we restore it to its default state, experience how it's supposed to work, and then refine from there?

**Comment by deigolocco** [comment]
I'll work tomorrow to restore its default state

**Comment by deigolocco** [comment]
@KimMcMahon and @cjyabraham I enabled the main theme and the [page](https://fuerza-cncf.pantheonsite.io/speakers/account/) is apparently well.
So you can check it and make your considerations. I'll investigate why the page is not working with child's theme.
@KimMcMahon should I ask for @pablodelarocha a new design?

**Comment by deigolocco** [comment]
remember, you must be logged in at website to access this page

**Comment by KimMcMahon** [comment]
Thank you @deigolocco. I'm going to test and identify any changes we may need. Stay tuned! I plan on getting this to you by tomorrow morning.

**Comment by KimMcMahon** [comment]
From anywhere in the account profile, there is no option to log out. Can one be added? 
https://fuerza-cncf.pantheonsite.io/speakers/account/
<img width="1213" alt="Screen Shot 2019-09-09 at 1 28 00 PM" src="https://user-images.githubusercontent.com/29307455/64560428-b961c380-d305-11e9-86b7-cb8db293019d.png">

**Comment by KimMcMahon** [comment]
From the [account profile](https://fuerza-cncf.pantheonsite.io/speakers/account/), I should have an option to update my profile.

In our current process, updating my profile takes me to this [page](https://www.cncf.io/speaker/kmcmahon/?um_action=edit).

**Comment by deigolocco** [comment]
@KimMcMahon we can add the log out option.
I'll take at look about the update process

**Comment by deigolocco** [comment]
@KimMcMahon what is the purpose of this [page](https://www.cncf.io/speaker/kmcmahon/
Looks like a form to aprove an events, am I right?
![screencapture-fuerza-cncf-pantheonsite-io-speaker-diegofagundes-2019-09-10-11_33_58](https://user-images.githubusercontent.com/5631313/64623241-02c21980-d3bf-11e9-9f02-305830cda63a.png)
To edit your profile you should click at the gear button at right top
<img width="1440" alt="Captura de Tela 2019-09-10 às 11 23 14" src="https://user-images.githubusercontent.com/5631313/64623472-651b1a00-d3bf-11e9-90e0-0a1b14fe41b3.png">
Should we concentrate these options at account's profile page?

**Comment by KimMcMahon** [comment]
@deigolocco Remove the Contact Speaker from the account profile page. Please.
https://www.cncf.io/speaker/kmcmahon/

**Comment by KimMcMahon** [comment]
@deigolocco Is the gear part of the plug-in? Or does the plug-in allow us to replace the gear with buttons?
https://fuerza-cncf.pantheonsite.io/speaker/kim.mcmahon/
<img width="1193" alt="Screen Shot 2019-09-10 at 12 11 45 PM" src="https://user-images.githubusercontent.com/29307455/64639434-12dcf780-d3c5-11e9-97d9-8724f6b6a1e4.png">

**Comment by deigolocco** [comment]
@KimMcMahon we added the logout button and removed the Contact Speaker form.
The plugin uses Font Awesome, so we can replace the gear button for any other icon, [these are](https://faicons.com/) the possibilities, please let us know which one do you prefer.

**Comment by deigolocco** [comment]
@cjyabraham we fixed salient child theme to work with the plugin Ultimate Member

**Comment by cjyabraham** [comment]
@deigolocco, @KimMcMahon I think the Logout tab behavior is inconsistent with the other tabs in that it immediately performs an action.  Can you make the Logout tab not immediately log you out but rather bring you to a Logout link?  Alternatively, don't make the Logout action a tab but rather just include it as a link below the tabs?

Keep in mind that the user can also use logout link in the cog on the Speaker's profile page.

@KimMcMahon where do you see the Speaker contact form going instead of on the profile page?  Do you think there's a better place for it?

**Comment by dankohn** [comment]
@cjyabraham We want to support sending a single message to multiple speakers. That could be another mode after you've done some filtering where you select all or a subset and then send a message. Of course, we should also support sending a message to one.

**Comment by cjyabraham** [comment]
@dankohn that's fine.  We have that in #11.  For now, though, I think we should leave the contact form as is on the profile page as it will be some time before #11 is ready.

**Comment by cjyabraham** [comment]
I have deployed the [updated account page](https://www.cncf.io/speakers/account/).  There are a few issues I see:
- The Privacy tab doesn't seem to save changes to the data on it
- The password form doesn't have decent field validation messages.  If you don't enter anything in "Confirm password" it doesn't tell you to, for example.
- The password form doesn't seem to do anything.  It doesn't change your password.
- I continue to think we should do something different with the logout "tab", as [I mentioned above](https://github.com/cncf/wordpress-site/issues/55#issuecomment-530338150)

I will keep this as urgent until we get all parts of the Account page working.

**Comment by KimMcMahon** [comment]
@deigolocco On the gear - the gear icon is fine. I don't want to change it. I think it's unclear that you click on the gear to update your profile. Is there a solution so it's more clear that the gear is how you update your profile or go to your account page?

**Comment by KimMcMahon** [comment]
@deigolocco On the logout button as @cjyabraham noted, can you make the Logout tab not immediately log you out but rather bring you to a Logout link? 

As for this comment: Alternatively, don't make the Logout action a tab but rather just include it as a link below the tabs?
I'm fine where the logout is (as a tab). If it's not too much effort to change it as Chris A has requested, then please change.

**Comment by KimMcMahon** [comment]
@deigolocco as @cjyabraham mentioned, the privacy tab does not change your privacy choice.

**Comment by KimMcMahon** [comment]
@deigolocco This is urgent - the change your password does not actually change your password. Please let me know when this is working so I can test again.

**Comment by KimMcMahon** [comment]
@cjyabraham To answer this:
@KimMcMahon where do you see the Speaker contact form going instead of on the profile page? Do you think there's a better place for it?

The speaker contact form should be on the speaker's profile page. 

When I'm not logged in, the contact form should be on the speaker's profile page.

When I am logged in, it confused me that I would contact myself to speak. That being said, I don't think the plug-in allows a different behavior of the speaker contact form based on whether you are logged in or not. If this is true, then I remove the request to remove the speaker request form.

**Comment by deigolocco** [comment]
@KimMcMahon we'll work on these 3 itens initially:

- The Privacy tab doesn't seem to save changes to the data on it
- The password form doesn't have decent field validation messages. If you don't enter anything in "Confirm password" it doesn't tell you to, for example.
- The password form doesn't seem to do anything. It doesn't change your password.

After I'll check the logout possibilities and wait your decision about the rest

**Comment by deigolocco** [comment]
@KimMcMahon itens are fixed

**Comment by cjyabraham** [comment]
Looks ok except when you click the Logout tab it logs you out immediately, even though the text now appears: "Are you sure?".

**Comment by deigolocco** [comment]
@cjyabraham  copy changed https://fuerza-cncf.pantheonsite.io/speakers/account/

**Comment by cjyabraham** [comment]
Ok, can you fix the [immediate logout when you click the tab](https://github.com/cncf/wordpress-site/issues/55#issuecomment-531463717) problem?

**Comment by deigolocco** [comment]
fixed @cjyabraham 
https://fuerza-cncf.pantheonsite.io/speakers/account/

**Comment by cjyabraham** [comment]
Thanks.  I've deployed this.  

There are a problems with the mobile view, however.  I can change my name and email in desktop view but when I try on mobile view, it doesn't work.  The values stay the same on page refresh.  The same goes for values on the Privacy tab and, I assume, on the other tabs.

Can you fix these please?

**Comment by deigolocco** [comment]
fixed @cjyabraham

**Comment by cjyabraham** [comment]
Looks good now.  Thanks.
