### ISSUE TITLE
Add self-identification fields to profile

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#59]
To the [speakers profile page](https://www.cncf.io/speaker/prydonius/):

- Add a drop down for Gender with the following values: Male, Female, Non-binary, Prefer not to say
- Add additional check boxes for: LGBTQ, Black, Latinx, Indigenous Peoples, Disabled

**Comment by cjyabraham** [comment]
Right now these fields are publicly viewable.  Do we want to keep it that way or make the information private, so people would enter it but know that it won't be public?  We could still use it for filtering and other things if we want to.

How does this look:
<img width="757" alt="Screen Shot 2019-08-27 at 10 12 00 PM" src="https://user-images.githubusercontent.com/463160/63783766-bcc57a00-c917-11e9-9311-fd53f5bc7189.png">

**Comment by dankohn** [comment]
Yes, publicly viewable, please.

**Comment by cjyabraham** [comment]
Ok, I'll consider this closed then.
