### ISSUE TITLE
Add pagination for newsroom items

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#60]
https://www.cncf.io/newsroom/announcements/
https://www.cncf.io/newsroom/in-the-news/
https://www.cncf.io/newsroom/blog/

show all items back to the founding of CNCF. Please add pagination and show 20 per page.

**Comment by deigolocco** [comment]
Pagination working
https://newsroom-cncf.pantheonsite.io/newsroom/announcements/
https://newsroom-cncf.pantheonsite.io/newsroom/in-the-news/
https://newsroom-cncf.pantheonsite.io/newsroom/blog/

we created a new component for VC with this feature
![Captura de Tela 2019-08-28 às 17 08 38](https://user-images.githubusercontent.com/5631313/63894272-9a3c6b00-c9c2-11e9-8355-6e67fcb6a6cb.png)

And the number of itens per page can be set here
![Captura de Tela 2019-08-28 às 17 09 00](https://user-images.githubusercontent.com/5631313/63894302-ab857780-c9c2-11e9-9fe2-628b00c93351.png)

**Comment by KimMcMahon** [comment]
@deigolocco Looks great!

@cjyabraham please deploy.

**Comment by cjyabraham** [comment]
@deigolocco I have deployed the code.  Can you add the VC components?

**Comment by dankohn** [comment]
Sorry, this wasn't what I wanted. You switched https://www.cncf.io/category/blog/ from just having titles to having the full article. Could you please switch back to titles, but paginate them. Maybe 30 or 40 items per page would be better, but the idea is to be able to scroll this past blog posts but not have them all.

**Comment by deigolocco** [comment]
Sorry @dankohn , we didn't work at https://newsroom-cncf.pantheonsite.io/category/blog/, but https://newsroom-cncf.pantheonsite.io/newsroom/announcements/, https://newsroom-cncf.pantheonsite.io/newsroom/in-the-news/ and https://newsroom-cncf.pantheonsite.io/newsroom/blog/. 
Why do we have this content duplication? Same content in a Archive(/category/blog) and Page(/newsroom/blog).
I believe the best is to implement the requested adjusts for Archives and delete the duplicated Pages. 
Can you please confirm if I may proceed?

**Comment by dankohn** [comment]
@cjyabraham Please push these changes.

**Comment by cjyabraham** [comment]
The code changes are already deployed.  @deigolocco can you add the VC elements you need to show the pagination?

**Comment by deigolocco** [comment]
pagination activated
https://www.cncf.io/newsroom/announcements/
https://www.cncf.io/newsroom/in-the-news/
https://www.cncf.io/newsroom/blog/
--

**Comment by dankohn** [comment]
Looks good, thanks.
