### ISSUE TITLE
Figure out best way to force-clear browser cache of Hummingbird assets

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#61]
This is causing problems when we do a deployment and browsers continue to use out-dated hummingbird assets.

I have texted Marco to provide me with credentials so I can access Hummingbird support.

**Comment by dankohn** [comment]
We can also consider getting our own Hummingbird Pro and Smush Pro subscription.

**Comment by cjyabraham** [comment]
I got access to Hummingbird support and placed an issue with them.  We'll need to wait for a response.

**Comment by cjyabraham** [comment]
The Feedback from Hummingbird:

> There's been a been update of Hummingbird released just yesterday so that was the priority our developers were focusing on recently. They'll be looking into various improvements, changes and new features now for next minor and major releases so we'll see how it goes :slight_smile: I don't have any ETA's as it's something that I suggested just the day before yesterday but hopefully we'll find the way to improve that too 

my response:

> Ok, thanks Adam. I imagine this must be a pain that many (if not most) of your users have so it'd be great if this is prioritized. As it is, we will likely have to switch off of Hummingbird until it is fixed.

**Comment by dankohn** [comment]
https://www.codeinwp.com/blog/finding-top-wordpress-caching-plugin/

**Comment by cjyabraham** [comment]
Interestingly, Hummingbird has replied, advising us to just switch off browser cacheing for now:

> Yeah, browser cache "persistency" may somtimes be troublesome. It's quite a "stubborn" kind of cache :slight_smile:
> 
> However, switching off Hummingbird may but doesn't necessarily will help here and will also disable other options. If anything - try rather disabling Browser Cache alone in plugin configuration.
> 
> I'm saying this because browser caching is not something that Hummingbird actually performs (unlike Page Caching - which not only can be cleared "on demand" but now also on schedule). It's in fact a "server thing" and it's server that sends all the necessary headers to the browser. Hummingbird only helps control whether to send them or not and how long should expiry time be.
> 
> With browser cache disabled (if server allows that), Asset Optimization wouldn't be a big issue because all you'd need to do after making any changes to e.g. stylesheets would be to just clear HB cache (via "Hummingbird -> Dashboard") and it would re-generate all the assets. If they wouldn't be cached in browser, all visitors would receive up to date versions.

I don't love that idea as that means all assets would need re-downloading with every page view.  I could run a test to see what the effect might be?

Another option is to just leave things as they are.  People will get our updated assets eventually, but it's just we won't have control over when.

Final option, as @dankohn suggested, look for an [alternative to hummingbird](https://www.codeinwp.com/blog/finding-top-wordpress-caching-plugin/) that has this figured out.

**Comment by cjyabraham** [comment]
I could use [this plugin](https://wordpress.org/plugins/prevent-browser-caching/)

**Comment by cjyabraham** [comment]
I've installed [Prevent Browser cacheing](https://wordpress.org/plugins/prevent-browser-caching/) so that I can manually bust browser cache when I do a deployment.  I have re-activated hummingbird and its compiled assets are correctly being versioned by the Prevent Browser Cacheing plugin.  

On future deployments I will click update version number on assets then clear hummingbird cache then clear Pantheon cache.

This issue can be considered closed.
