### ISSUE TITLE
Update "Events and Webinars" section on home page

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#62]
Please update the CNCF home page "Events and Webinars" section to pull in our new Webinars CPT and Events We're At.  

CCing @dankohn and @KimMcMahon for their ideas on any improvements to this section.  Assign to @deigolocco when ready.

**Comment by deigolocco** [comment]
Can I ask to @pablodelarocha propose a design?

**Comment by KimMcMahon** [comment]
@deigolocco Yes, please have Pablo propose a design.

**Comment by cjyabraham** [comment]
@KimMcMahon does it still make sense to group these two things together: events we'll be at and webinars?  

@pablodelarocha I'm not sure I like how the dates are presented in different formats.  And then in the Newsroom section of the home page, the dates are in yet another format.  For someone browsing down the home page, this is a lot of different styles to take in.  Would it make sense to standardize these so it works for the home page?

**Comment by cjyabraham** [comment]
I've created a separate issue to fix all the dates across the site #68. @pablodelarocha wrt this issue, please make the dates comply on the home page.

**Comment by pablodelarocha** [comment]
@cjyabraham and @KimMcMahon now that we've solved the date formats issue, i'm sending some suggestions of how the "Events and Webinars" could look like on the homepage. Please let us know if you approve any of these variations.

![v1](https://user-images.githubusercontent.com/54405572/63952247-97d72100-ca55-11e9-896f-76f0708c9876.jpg)
![v2](https://user-images.githubusercontent.com/54405572/63952249-97d72100-ca55-11e9-9863-c44c3a559355.jpg)
![v3](https://user-images.githubusercontent.com/54405572/63952251-986fb780-ca55-11e9-9985-ebce36c3ac49.jpg)
![v4](https://user-images.githubusercontent.com/54405572/63952253-986fb780-ca55-11e9-8deb-1ed2c8762251.jpg)

**Comment by dankohn** [comment]
I like the second option, except I believe it would require creating a separate image for event. In which case, we may just want to do the first one, if we can reuse the image. We don't want to use the same color and italicized bold for time on one side and location on the other. Also, note that all times are `PT` not `PDT`.

**Comment by pablodelarocha** [comment]
@dankohn gotcha! Please let us know if we can proceed with the below (adjusted) designs. Thanks!
![01-home](https://user-images.githubusercontent.com/54405572/63969676-bac6fc80-ca78-11e9-91ca-736be5d7a4f2.jpg)

**Comment by KimMcMahon** [comment]
@pablodelarocha The second one, I believe, is this version (which I prefer as well). 
<img width="669" alt="Screen Shot 2019-08-29 at 1 22 09 PM" src="https://user-images.githubusercontent.com/29307455/63969910-2c468100-ca60-11e9-87fc-e0710a00ae6a.png">

@dankohn We do create an image for most 3rd party event.
@pablodelarocha Can you create a version with events that do not have an image? Cloud Native Security Day (November 18) does not have an image. Let's see how that looks.

@pablodelarocha Also, for each event, there should be a box for the user to click to go to that event. The webinar, or the page we created for the Event We'll Be At.

Please mock up another design and I'll take a look. Thanks!

**Comment by dankohn** [comment]
@KimMcMahon The issue in design 2 is that we'll need to upload 2 images for every event, rather than 1. That seems like a lot of trouble.

Are you sure we need a button to click? I presume with the current design that the whole rectangle is a link, which seems clear.

**Comment by pablodelarocha** [comment]
@dankohn we've been doing the banners for the "Events we'll be at" and it would take a couple of minutes to create a second image in a different format. Diego could easily create a field to upload the alternative image in wordpress. 
If you all like the design #2 better we can make it happen, for sure. Just need to be sure if we need to add buttons there, as i agree with you it's clear you can click on it.
Also, when an event doesn't have image or branding, we've been doing a standard banner with clouds + the event name on it, like this:
![image](https://user-images.githubusercontent.com/54405572/63975814-42673800-ca86-11e9-9366-5b8922c523c2.png)

**Comment by dankohn** [comment]
My hesitation is that we do about 50 events per year. But I'm fine with #2 if @KimMcMahon prefers.

**Comment by cjyabraham** [comment]
I strongly feel we should avoid designs that require ongoing support from a designer.  There is so much that needs keeping up-to-date on the site that having to coordinate efforts from an external team just to advertise an Event we'll be at seems a lot of trouble.  Couldn't this be configured to just require uploading an SVG (or PNG) logo and then choosing a background image from a set that are available in the Media Library?  The same logo/background could be used for the square on the home page.  That way no external help would be needed.

**Comment by KimMcMahon** [comment]
@pablodelarocha I agree with Chris - I want a design on the home page that will take the banner that is on the "Events We'll Be At" page and reuse it on the home page.

Can I see that design and with some events that do not have a banner.

Also - no button, but the boxes should be clickable.

Opening another issue to address needing a custom banner for our Event's We'll Be At.

**Comment by pablodelarocha** [comment]
@KimMcMahon ok, understood. So i suggest we do this design:
![image](https://user-images.githubusercontent.com/54405572/64051741-98a1ad00-cb52-11e9-8f22-81e4f46778cc.png)
And the events that don't have a logo, we can just select a background banner and, if you don't upload the logo, the name of the event will be placed over the background, just like the "LF Energy Summit" example.
Also, here's a scheme of how this would work:
![image](https://user-images.githubusercontent.com/54405572/64052053-84aa7b00-cb53-11e9-9158-a93ac66de7c0.png)

If we proceed with that, we will need fields in wordpress to select the event's banner and logo. But we will have to do this for all events live on the site today, i believe?

**Comment by cjyabraham** [comment]
Sounds good @pablodelarocha.  

We could have a set of banners that the author can choose from.  If we suffix all of them with "-ewa-banner", then they'll be easy to find in the Media Library each time someone adds a new event.

And yes, it sounds like you'll need an extra field to upload the event logo.

What do you have in mind for how you'll "generate two background banners"?  Alternatively, we could just use the one large one in both places?

**Comment by pablodelarocha** [comment]
@cjyabraham great, i will ask @deigolocco to start implementing this design while i create the banner templates.

As for the two background banners, in fact, only one banner is necessary. Once you upload, it will be cropped automatically, generating two different images, as shown in the diagram above.

**Comment by deigolocco** [comment]
We'll proceed with the development. @cjyabraham I'll use the add_image_size native function from wordpress to set the crops

**Comment by cjyabraham** [comment]
@deigolocco correct me if I'm wrong but won't add_image_size generate images at the size you specify for all uploads going forward?  Won't that be kind of a waste of space and energy since we actually only want to do this for the several images we use as background images?

**Comment by deigolocco** [comment]
@cjyabraham in part you are right.

But we need to decide what is the best option. I see 3 scenarios:

1 - To create 2 different images for each situation, one for homepage and another for events.
* Benefits:
- one optimized image per situation. Saves user and server resources
* Against:
- Even being made in a few minutes, needs a designer to create both
2 - To upload logo and background separately without background crop.
User will load 2 different images, and the background will not be optimized. Background image needs to have 1198x165, and it size adjustment will be with css for each situation.
*Benefits:
- Doesn't need a designer
*Against:
- Consumes user resources, background will be bigger than necessary
3 - To upload logo and background separately with background crop.
User will load 2 different images, and the background will be optimized. Background image will have the necessary size.
*Benefits:
- Doesn't need a designer
*Against:
-  Consumes user resources(still loading 2 images for each event, but less than case 2)
- The automated crop will save user resources but will consume server space, because 2 different sizes will be create for any new uploaded image.

Please let me know which is the best option for you and we'll implement here

**Comment by dankohn** [comment]
I think we should go for 1 for now, as I really want to get this work on the homepage, and then we can reconsider later. OK. @cjyabraham ?

**Comment by cjyabraham** [comment]
One other option: Don't use background images on the home page.  Just show the logo and use a white background.  However, I suppose some logos won't look good on a white background?

Ok, go with 1 for now.  I think going forward we should try to create designs which look good while requiring minimal administration and they shouldn't require ongoing design effort just to add new items.

**Comment by cjyabraham** [comment]
Actually, how about allowing the administrator to pick a background color that will work with the logo they upload?  This will be easier to administer, easier to develop and will be a faster experience for the user while, hopefully, looking almost as good.  What do you think @deigolocco ?

**Comment by deigolocco** [comment]
@cjyabraham the logo being a png with transparence in a solid background will be heavier than a jpg (logo + background in a single image) and not so nice. But you decide, what should we do?

**Comment by deigolocco** [comment]
Just to complement my last comment, as I mentioned before we take 5min to produce each image. We could produce a hundred per day if necessary, having the list previously this will not be a blocker.  But of course, the decision is yours

**Comment by KimMcMahon** [comment]
@cjyabraham please deploy 1 for now as Dan asked. 
@deigolocco @pablodelarocha if there is any work you need to finish so Chris can deploy tonight, please complete today.

A separate issue for the image for Events has been opened.

**Comment by deigolocco** [comment]
@cjyabraham could you deploy the branch **fz-image** pls?
https://fz-image-cncf.pantheonsite.io/wp-admin/post.php?post=42294&action=edit
We just added the extra field for the homepage section
<img width="350" alt="Captura de Tela 2019-09-03 às 14 35 24" src="https://user-images.githubusercontent.com/5631313/64195634-5a5d0400-ce58-11e9-984b-70a8fd918942.png">
After this deploy we can start to upload the images.
The front implementation is being made in a different branch.

**Comment by deigolocco** [comment]
implementation is done, please take at look
https://fz-events-cncf.pantheonsite.io/

@cjyabraham please deploy **fz-image** first so we can upload the new images
after this you can deploy **fz-events**

**Comment by KimMcMahon** [comment]
Looks great @deigolocco.
@cjyabraham please deploy.

**Comment by cjyabraham** [comment]
Ok, fz-image branch is deployed.

**Comment by deigolocco** [comment]
thank you @cjyabraham! I just finished the uploads, could you deploy fz-events pls?

**Comment by cjyabraham** [comment]
@deigolocco there's a merge conflict.  Can you resolve please?

**Comment by rodmeurer** [comment]
@cjyabraham conflict solved.

**Comment by cjyabraham** [comment]
Deployed.

**Comment by KimMcMahon** [comment]
@deigolocco @cjyabraham See image - Chrome and Safari. 
<img width="1920" alt="Screen Shot 2019-09-04 at 7 43 17 AM (2)" src="https://user-images.githubusercontent.com/29307455/64260579-5a0c4980-cee8-11e9-8811-52c281754ed6.png">

**Comment by KimMcMahon** [comment]
And on mobile. Changed the top banner - it's covered.
![IMG_2181](https://user-images.githubusercontent.com/29307455/64260760-b66f6900-cee8-11e9-8e8f-cbc673e0a71c.JPG)
![IMG_2182](https://user-images.githubusercontent.com/29307455/64260764-b8392c80-cee8-11e9-8cd8-06d49f50a3f6.JPG)
