### ISSUE TITLE
Make boxes on kubecon.io more dense

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#64]
Please make the boxes on https://www.cncf.io/community/kubecon-cloudnativecon-events/ the same size as the ones on https://events.linuxfoundation.org and avoid the space between rows:

![image](https://user-images.githubusercontent.com/3083270/63696889-bd5ff280-c7e9-11e9-99ba-1544d60cc52a.png)

**Comment by cjyabraham** [comment]
It looks like the space is fixed but the boxes could still be reduced in height to match [the others](https://events.linuxfoundation.org).

**Comment by alexcontini** [comment]
@cjyabraham I have updated the sizing of the boxes: https://www.cncf.io/community/kubecon-cloudnativecon-events/ - I tried to make them as small as possible, it's just tricky as some of the boxes need more space and I wanted to make sure the ones in the same row are the same height

**Comment by cjyabraham** [comment]
Looks good to me.  I'll close.  @dankohn feel free to reopen if not ok with you.
