### ISSUE TITLE
Update date formats across the site for consistency

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#68]
As per @dankohn :

> Let's try to be consistent everywhere with dates and spacing. You don't want to add th like 25th on dates because then you need to do 23rd and 22nd. Instead, let's please do dates as:
> 
> August 28, 2019
> October 1 - 3, 2019
> October 31 - November 1, 2019
> September 25, 2019 10:00am - 11:00am PT
> October 25, 2019, Amsterdam
> 
> Note that there are spaces on each side of the -. Dates always include the year and are separated from the city with a comma.

Please update the date format on the following instances:

- [x] The dates on the [events tiles](https://www.cncf.io/community/kubecon-cloudnativecon-events/)
- [x] [Events We'll be at search](https://www.cncf.io/events-well-be-at/)
- [x] [Events We'll be at individual page](https://www.cncf.io/events-well-be-at/pax-dev/)
- [x] [Webinars Search](https://www.cncf.io/webinars/)
- [x] [Webinars individual page](https://www.cncf.io/webinars/cloud-native-development-in-aws-with-container-and-serverless/)
- [x] [Announcements individual page ](https://www.cncf.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/)
- [x] [News individual page](https://www.cncf.io/news/2019/08/20/searchitoperations-test-your-knowledge-of-cncf-projects-and-tools/)
- [x] [Blog individual page](https://www.cncf.io/blog/2019/08/23/cncf-joins-google-summer-of-code-2019-with-17-interns-projects-for-containerd-coredns-kubernetes-opa-prometheus-rook-and-more/)
- [x] [Newsletter listing](https://www.cncf.io/newsroom/newsletter/)
- [x] Top banner "November 18-21"

**Comment by cjyabraham** [comment]
Ok.  removed from issue description.

**Comment by cjyabraham** [comment]
I think that works.  The one thing I don't love is when you have two of the big upcoming dates together:
<img width="190" alt="Screen Shot 2019-08-28 at 11 16 43 AM" src="https://user-images.githubusercontent.com/463160/63825534-63942f80-c985-11e9-96c7-e59d732b5fc6.png">

Could you try combining them into one rectangle to see how that looks so it would have just one "Aug" and one "2019"?

**Comment by cjyabraham** [comment]
Looks good!

**Comment by KimMcMahon** [comment]
Yes - Please move forward on deployment.

**Comment by deigolocco** [comment]
@KimMcMahon these are the design proposals, are not implemented yet. Can I proceed with the implementation?

**Comment by KimMcMahon** [comment]
@deigolocco Yes

**Comment by deigolocco** [comment]
date format consolidated
https://fz-date-cncf.pantheonsite.io/newsroom/announcements/
https://fz-date-cncf.pantheonsite.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/
https://fz-date-cncf.pantheonsite.io/newsroom/in-the-news/
https://fz-date-cncf.pantheonsite.io/news/2019/08/20/searchitoperations-test-your-knowledge-of-cncf-projects-and-tools/
https://fz-date-cncf.pantheonsite.io/newsroom/blog/
https://fz-date-cncf.pantheonsite.io/blog/2019/08/23/cncf-joins-google-summer-of-code-2019-with-17-interns-projects-for-containerd-coredns-kubernetes-opa-prometheus-rook-and-more/
https://fz-date-cncf.pantheonsite.io/webinars/
https://fz-date-cncf.pantheonsite.io/webinars/building-a-kubernetes-powered-central-modules-repository/
https://fz-date-cncf.pantheonsite.io/webinars/tales-of-the-kubernetes-ingress-networking-deployment-patterns-for-external-load-balancers/
https://fz-date-cncf.pantheonsite.io/events-well-be-at/
https://fz-date-cncf.pantheonsite.io/events-well-be-at/helm-summit/

**Comment by cjyabraham** [comment]
@deigolocco have you figured out why we have [two dates here](https://fz-date-cncf.pantheonsite.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/)?

I notice we have the date twice on the [individual webinar page](https://fz-date-cncf.pantheonsite.io/webinars/tales-of-the-kubernetes-ingress-networking-deployment-patterns-for-external-load-balancers/).  Could you update the one on the right to be the format with the year?

For this format, could you make sure the year is centered?  Also, I think this might be one case where we'd benefit from not having the space on either side of the "-", or at least have a smaller space.  What do you think @dankohn ?
<img width="182" alt="Screen Shot 2019-08-31 at 10 55 49 AM" src="https://user-images.githubusercontent.com/463160/64059032-edd6d080-cbdd-11e9-84cb-93fda69e67b5.png">

Can you also do the homepage Newsroom section?

**Comment by dankohn** [comment]
Agreed on removing the spaces around hypens for dates in a box. Note that the date in the box on the right is missing the year: https://fz-date-cncf.pantheonsite.io/webinars/tales-of-the-kubernetes-ingress-networking-deployment-patterns-for-external-load-balancers/

**Comment by deigolocco** [comment]
@cjyabraham about the [2 dates](https://fz-date-cncf.pantheonsite.io/webinars/tales-of-the-kubernetes-ingress-networking-deployment-patterns-for-external-load-balancers/), should we remove the date in "EVENT DETAILS" or just add the year as @dankohn's last comment?

**Comment by deigolocco** [comment]
@cjyabraham we already have 2 dates [here](https://www.cncf.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/), should we remove the second?

**Comment by dankohn** [comment]
@deigolocco your comment isn’t clear. Could you please paste in screenshots here to explain the question and also say what you recommend.

**Comment by deigolocco** [comment]
sorry @dankohn , I'll try to clarify my comment.
@cjyabraham reported a date duplication [here](https://fz-date-cncf.pantheonsite.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/)
![Captura de Tela 2019-09-02 às 10 23 20](https://user-images.githubusercontent.com/5631313/64117523-c3b31900-cd6b-11e9-8715-96144ff7fd47.png)
We found these 2 dates at the [original post](https://www.cncf.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/)
![Captura de Tela 2019-09-02 às 10 24 54](https://user-images.githubusercontent.com/5631313/64117595-f0ffc700-cd6b-11e9-9d15-c253d10552f6.png)
Should we remove the second date?
I recommend to keep as already is.

**Comment by cjyabraham** [comment]
@deigolocco can you figure out what each date represents?  Normally we show just the published date, as in [this listing](https://www.cncf.io/newsroom/blog/).

**Comment by deigolocco** [comment]
*@cjyabraham the second date was related to the last post update, removed
https://fz-date-cncf.pantheonsite.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/

*extra spaces removed and date year centralized
https://fz-date-cncf.pantheonsite.io/events-well-be-at/

*@dankohn year added
https://fz-date-cncf.pantheonsite.io/webinars/tales-of-the-kubernetes-ingress-networking-deployment-patterns-for-external-load-balancers/

**Comment by rodmeurer** [comment]
Homepage Newsroom section up to date.
https://fz-date-cncf.pantheonsite.io/

**Comment by dankohn** [comment]
LGTM

**Comment by cjyabraham** [comment]
I've deployed however there are a few fixes needed:

1. We need a way to deal with dates that cross a month or year boundary, like [this one](https://www.cncf.io/events-well-be-at/open-networking-summit-europe/).  What do you guys suggest?
2. Could you make the mobile view of the dates here more vertically centered:
<img width="301" alt="Screen Shot 2019-09-03 at 11 08 53 AM" src="https://user-images.githubusercontent.com/463160/64143676-5373c880-ce3b-11e9-819a-79a156bdaebe.png">
3. Could you make the spacing on the [post date byline](https://www.cncf.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/) the same as on the [other](https://www.cncf.io/webinars/) [pages](https://www.cncf.io) which seem to have a space after the calendar icon?

**Comment by dankohn** [comment]
I recommend `9/30 - 10/1/2020`.

**Comment by cjyabraham** [comment]
Right but I'm referring to this particular format that we need to find a solution for:
<img width="73" alt="Screen Shot 2019-09-03 at 6 42 15 PM" src="https://user-images.githubusercontent.com/463160/64170555-930dd500-ce7a-11e9-9a0d-98f6f424c848.png">

**Comment by dankohn** [comment]
Then I would suggest:

`SEP-OCT`
`30-1`
`2019`

**Comment by rodmeurer** [comment]
@cjyabraham fixed.

1. https://fz-date-cncf.pantheonsite.io/events-well-be-at/open-networking-summit-europe/

2. https://fz-date-cncf.pantheonsite.io/webinars/tales-of-the-kubernetes-ingress-networking-deployment-patterns-for-external-load-balancers/

3. https://fz-date-cncf.pantheonsite.io/announcement/2019/08/21/cloud-native-computing-foundation-welcomes-48-new-members-at-open-source-summit-north-america/

**Comment by dankohn** [comment]
You did what I asked but could you please instead have the date ranges look like:
```
SEP   OCT
    -
 30    1
```
That is, please do a single hyphen, and have the numbers centered below the month.

**Comment by rodmeurer** [comment]
@dankohn we designed two different possibilities so you can choose.

![test1](https://user-images.githubusercontent.com/54405402/64195414-cb4fec00-ce57-11e9-87ea-416bb5c89094.jpg)
![test2](https://user-images.githubusercontent.com/54405402/64195416-cdb24600-ce57-11e9-9ad8-ba36dcec6de1.jpg)

**Comment by dankohn** [comment]
Thanks. I like the first one, because it implies "through" not "or".

Going forward, please also say which one you recommend.

**Comment by rodmeurer** [comment]
@dankohn good point. Yes, we think the first one is better.

**Comment by KimMcMahon** [comment]
@deigolocco @cjyabraham Can this please be deployed tonight? The date formats on the live page are messed up and I'd like this updated before 11am ET Wednesday. Thank you.

**Comment by KimMcMahon** [comment]
@deigolocco Dates that go across a month do not show up correctly.
https://www.cncf.io/events-well-be-at/vmworld/
https://www.cncf.io/events-well-be-at/open-networking-summit-europe/
https://www.cncf.io/events-well-be-at/aws-reinvent-2/

**Comment by cjyabraham** [comment]
@deigolocco ping me when you've got the updates done and I'll deploy.

**Comment by deigolocco** [comment]
adjustments implemented https://fz-date-cncf.pantheonsite.io/events-well-be-at/

**Comment by dankohn** [comment]
This looks great:
![image](https://user-images.githubusercontent.com/3083270/64273216-db76d280-cf0e-11e9-8552-ba302bc7c8ba.png)

Could you please change to do `4-5` instead of `04-05`.

**Comment by rodmeurer** [comment]
@dankohn @cjyabraham adjusted.
https://fz-date-cncf.pantheonsite.io/events-well-be-at/
https://fz-date-cncf.pantheonsite.io/events-well-be-at/lf-energy-summit/

**Comment by dankohn** [comment]
LGTM

**Comment by cjyabraham** [comment]
I have deployed this yet there is still an issue which I have changed data to demonstrate on the dev site:

See the [Gitlab Commit event on the home page](https://dev-cncf.pantheonsite.io), it shows the date as Sep 17-30.

I've actually set the date to Sep 17 - Oct 30 as you can see on [the individual page](https://dev-cncf.pantheonsite.io/events-well-be-at/gitlab-commit/).

So the home page does not show 2 months when it spans them.  Can you fix please?

Also, we don't accommodate events that span a year boundary but I assume we don't have any that will actually do that so we can probably ignore.

**Comment by rodmeurer** [comment]
@cjyabraham fixed.
https://fz-date-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
This is fine but now the [date ranges that don't span months are too wide](https://fz-date-cncf.pantheonsite.io/events-well-be-at/huawei-connect-2019/) and are causing the title to appear below them.

**Comment by deigolocco** [comment]
adjusted @cjyabraham

**Comment by cjyabraham** [comment]
The mobile view doesn't look right [here](https://www.cncf.io/events-well-be-at/).  The date boxes are too tall:
<img width="459" alt="Screen Shot 2019-09-06 at 11 14 07 PM" src="https://user-images.githubusercontent.com/463160/64443444-1722bf80-d0fc-11e9-99a5-f69d108f9a36.png">

**Comment by cjyabraham** [comment]
The date on the [single webinar page](https://fz-date-cncf.pantheonsite.io/webinars/kubevirt-beyond-containers-coming-full-circle-back-to-vms/) seems to have slipped down:
<img width="440" alt="Screen Shot 2019-09-07 at 10 01 06 AM" src="https://user-images.githubusercontent.com/463160/64469075-7e6d5d80-d156-11e9-9653-cf5fd1d953cd.png">

**Comment by deigolocco** [comment]
adjusted @cjyabraham

**Comment by cjyabraham** [comment]
Deployed.
