### ISSUE TITLE
Newsletter Archives

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#7]
Latest newsletters need to be exposed in an archive.  [See doc](https://docs.google.com/document/d/1KKgxPby92EYWjygNRtARcHlCqnJLT0vO504DFeQmhPE/edit?ts=5d2d464e#).

**Comment by KimMcMahon** [comment]
@cjyabraham I am going to email the past newsletters to the email list. Currently, there is a Salesforce Marketing Cloud issue that the Linux Foundation team is working to fix. Once this is fixed, I will email the newsletters.

We then need to remove the archive from the Newsletter page and replace it with a statement and link to the email list.  newsletter@lists.cncf.io

**Comment by KimMcMahon** [comment]
Adding Google Doc with project requirements. https://docs.google.com/document/d/1KKgxPby92EYWjygNRtARcHlCqnJLT0vO504DFeQmhPE/edit?usp=sharing

**Comment by KimMcMahon** [comment]
Update: An issue has been opened with Salesforce to allow mailing to newsletter@lists.cncf.io. When this is resolved, I will unblock the issue, execute, and note other needed updates.

**Comment by KimMcMahon** [comment]
Newsletter archives are on the newsletter mail list.
