### ISSUE TITLE
Update banner on Events We'll Be At page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#70]
https://www.cncf.io/events-well-be-at/

Update the banner to this image. Preferably with no filter. If you need other sizes of this image, check the CNCF Flicker account. And please crop out the people on the left and the chair on the right.
![45446325655_4fffa6001b_o](https://user-images.githubusercontent.com/29307455/63777500-6ff28c80-c8a0-11e9-90be-1e552ad45cce.jpg)

**Comment by KimMcMahon** [comment]
@pablodelarocha Please update the banner with the picture with the filter. Thanks!

**Comment by dankohn** [comment]
LGTM with the filter.

**Comment by deigolocco** [comment]
banner up to date
