### ISSUE TITLE
Add multiple companies to be listed for an upcoming webinar.

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#73]
Currently set up for one company.

Change to list all companies that are checked for any given webinar.
<img width="1920" alt="Screen Shot 2019-08-28 at 3 01 18 PM (2)" src="https://user-images.githubusercontent.com/29307455/63894309-8df7e400-c9a9-11e9-8545-ec27865fb29e.png">
<img width="1920" alt="Screen Shot 2019-08-28 at 3 01 30 PM (2)" src="https://user-images.githubusercontent.com/29307455/63894310-8df7e400-c9a9-11e9-8e74-c6a4d7494dd8.png">

**Comment by deigolocco** [comment]
added @KimMcMahon 
https://company-cncf.pantheonsite.io/webinars/challenges-in-deploying-kubernetes-on-hyperconverged-infrastructure-hci/
https://company-cncf.pantheonsite.io/webinars/how-cilium-uses-bpf-to-supercharge-kubernetes-networking-security/

**Comment by KimMcMahon** [comment]
Looks good @deigolocco. Please implement.

Then @cjyabraham please deploy.

**Comment by cjyabraham** [comment]
Deployed.
