### ISSUE TITLE
Fix z-index of "Add to Calendar" button

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#74]
The ["Add to Calendar" button](https://www.cncf.io/webinars/how-cilium-uses-bpf-to-supercharge-kubernetes-networking-security/) is showing over the topnav.  It should be behind the topnav.
<img width="889" alt="Screen Shot 2019-08-29 at 11 21 27 AM" src="https://user-images.githubusercontent.com/463160/63910054-5e9bb280-ca4f-11e9-9982-62a067038eca.png">

**Comment by deigolocco** [comment]
fixed @cjyabraham 
https://fuerza-cncf.pantheonsite.io/webinars/how-cilium-uses-bpf-to-supercharge-kubernetes-networking-security/

**Comment by KimMcMahon** [comment]
LGTM. @cjyabraham please deploy

**Comment by cjyabraham** [comment]
Deployed
