### ISSUE TITLE
Update Author post listing format

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#76]
The [author post listing](https://www.cncf.io/author/kevans/) should only list headlines and not the full post, in a format similar to [the blog listing](https://www.cncf.io/newsroom/blog/).

**Comment by deigolocco** [comment]
up to date @cjyabraham 
https://fz-authors-cncf.pantheonsite.io/author/kevans/

**Comment by cjyabraham** [comment]
Looks good but it is in a different format than the [blog listing](https://www.cncf.io/newsroom/blog/), however I like it better.  @dankohn what do you think about us using [this new format](https://fz-authors-cncf.pantheonsite.io/author/kevans/) in place of what we have for [blog](https://www.cncf.io/newsroom/blog/), [in the news](https://www.cncf.io/newsroom/in-the-news/), [announcements](https://www.cncf.io/newsroom/announcements/), etc.

**Comment by dankohn** [comment]
LGTM

**Comment by cjyabraham** [comment]
What do you think @deigolocco ? Would it be easy to make all the listings consistent with this new format?

**Comment by deigolocco** [comment]
sure @cjyabraham , we'll adjust the rest for the new format

**Comment by deigolocco** [comment]
formats consolidated @cjyabraham 
https://fz-authors-cncf.pantheonsite.io/author/kevans/
https://fz-authors-cncf.pantheonsite.io/newsroom/announcements/
https://fz-authors-cncf.pantheonsite.io/newsroom/blog/
https://fz-authors-cncf.pantheonsite.io/newsroom/in-the-news/

**Comment by cjyabraham** [comment]
LGTM.  Can you resolve the merge conflict please?

**Comment by deigolocco** [comment]
conflict solved @cjyabraham

**Comment by cjyabraham** [comment]
Could you fix again please?  I just merged fz-date into master.

**Comment by deigolocco** [comment]
sure @cjyabraham , solved

**Comment by cjyabraham** [comment]
The format of that page is causing the padding to reduce on the mobile menu.  Here's before and after:
<img width="884" alt="Screen Shot 2019-09-07 at 10 10 17 AM" src="https://user-images.githubusercontent.com/463160/64469172-c9d43b80-d157-11e9-9993-bcce75587c71.png">

**Comment by deigolocco** [comment]
adjusted @cjyabraham

**Comment by cjyabraham** [comment]
Looks fine.  Please resolve merge conflicts and I'll deploy.

**Comment by deigolocco** [comment]
solved @cjyabraham

**Comment by cjyabraham** [comment]
Deployed.
