### ISSUE TITLE
Add boxes for Training & Certification

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#77]
Please replace the text in the Training & Certification with two boxes showing the same text as this slide: https://docs.google.com/presentation/d/1BoxFeENJcINgHbKfygXpXROchiRO2LBT-pzdaOFr4Zg/edit#slide=id.g5d31aa9a3e_27_43

Images should be SVGs.

**Comment by deigolocco** [comment]
@dankohn it's done https://fuerza-cncf.pantheonsite.io/

**Comment by KimMcMahon** [comment]
@deigolocco Can you fix the bullets so the second and third lines of text are aligned with the text on the first line next to the bullet?

**Comment by deigolocco** [comment]
adjusted @KimMcMahon https://fuerza-cncf.pantheonsite.io/

**Comment by dankohn** [comment]
I think it looks great. Please change the link text from `course` and `test` to `Introduction to Kubernetes`, `Kubernetes Fundamentals`, `Certified Kubernetes Administrator (CKA) `, and `Certified Kubernetes Application Developer (CKAD)`. Then, let's deploy.

**Comment by deigolocco** [comment]
Adjusted @dankohn, it's editable

**Comment by dankohn** [comment]
Great. @cjyabraham could you please push.

**Comment by cjyabraham** [comment]
Deployed.
