### ISSUE TITLE
Google Search Console

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#78]
Please register cncf.io for Google Search Console and give access to dan@linuxfoundation.org and kmcmahon@cncf.io.

**Comment by KimMcMahon** [comment]
Change - give access to kmcmahon@linuxfoundation.org

**Comment by cjyabraham** [comment]
You should now both have access to [the search console](https://search.google.com/search-console?resource_id=https%3A%2F%2Fwww.cncf.io%2F).
