### ISSUE TITLE
Kill the social media palette

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#79]
We've gotten feedback that the floating social media palette takes up too much room (especially on mobile) and is not best practice. People looking for our social media links can always find them in the footer, which is where they're expected.

Could you please remove it.

Also, at the bottom of the Newsroom menu, please add two new entries:
Videos (YouTube)
Pictures (Flickr)

**Comment by deigolocco** [comment]
sure @dankohn , it's done https://fuerza-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
Deployed.
