### ISSUE TITLE
Webinar faceted search and page design

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#8]
[New webinar infrastructure and search](https://docs.google.com/document/d/1-5lGjs6fusNa2OniI0SRFu1rmlTFw_mY1FEkDsstdnQ/edit#heading=h.5jfz35magu6v).

- [x] Create a new webinar Custom Post Type (Chris)
- [x] Design and implement new webinar single post page for both upcoming and recorded webinars (Diego)
- [x] Create faceted search for webinar CPT; list new CPT in order of start date metadata in a format similar to on the new Events site (Chris)
- [x] Improve design of result listing of webinars in faceted search (Diego)
- [x] Migrate upcoming webinars to new CPT; assign taxonomies, metadata etc. (Kim)
- [x] Migrate recorded webinars to new CPT; assign taxonomies, metadata etc. (Kim)
- [ ] Update the home page to pull the Webinars CPT (Chris)
- [ ] Update CNCF menus to deploy all of the above (Kim)
- [ ] Deactivate Tribe Event plugin, that is no longer needed, to improve performance (Chris)

**Comment by cjyabraham** [comment]
Diego currently implementing designs

**Comment by KimMcMahon** [comment]
Adding designs
![Picture1](https://user-images.githubusercontent.com/29307455/62781795-f839fa80-ba75-11e9-8d2b-e58f07e91693.png)
![Picture2](https://user-images.githubusercontent.com/29307455/62781796-f839fa80-ba75-11e9-9096-43dcd0d1bc6a.png)
![Picture3](https://user-images.githubusercontent.com/29307455/62781797-f839fa80-ba75-11e9-8083-05e2ae24108e.png)
![Picture4](https://user-images.githubusercontent.com/29307455/62781798-f839fa80-ba75-11e9-835e-38046c52aec6.png)

**Comment by deigolocco** [comment]
@KimMcMahon @cjyabraham https://new-webinar-cncf.pantheonsite.io/webinars/

**Comment by dankohn** [comment]
LGTM. Please just change "RESET" to "Reset".

**Comment by deigolocco** [comment]
ok @dankohn

**Comment by KimMcMahon** [comment]
@deigolocco 
Please change the time for the upcoming webinars from "PST" to "PT" (Pacific time). 
We are actually on "PDT", so the "PST" is incorrect.

**Comment by KimMcMahon** [comment]
On the individual webinar pages such as this [one](https://new-webinar-cncf.pantheonsite.io/webinars/cncf-webinar-series-tools-and-techniques-securing-apis-in-kubernetes-environment/), we can remove "Event Category: Webinars" from the blue box on the right. 

If this is difficult or time consuming, disregard this request.

**Comment by KimMcMahon** [comment]
@deigolocco On the individual webinar pages such as this [one](https://new-webinar-cncf.pantheonsite.io/webinars/cncf-webinar-series-tools-and-techniques-securing-apis-in-kubernetes-environment/), the "Register Now" button is not functional and there is no link to the Website to register in the blue box. 

Is this because it's a test site with older webinars that have already occured?

**Comment by KimMcMahon** [comment]
@deigolocco  On the [page](https://new-webinar-cncf.pantheonsite.io/webinars/security-and-day-2-operations-with-harbor/) for a specific recorded webinar, there is a date and time for the webinar "June 13th, 2019 2:00-5:00PM PST". 

I'd like to keep the date of the webinar. Can the time be removed? And the time for this webinar is incorrect, so I'm not sure where the data is getting pulled from.

**Comment by deigolocco** [comment]
ok @KimMcMahon 

> @deigolocco On the individual webinar pages such as this [one](https://new-webinar-cncf.pantheonsite.io/webinars/cncf-webinar-series-tools-and-techniques-securing-apis-in-kubernetes-environment/), we can remove "Event Category: Webinars" from the blue box on the right.
> 
> If this is difficult or time consuming, disregard this request.

is easy to remove

**Comment by cjyabraham** [comment]
@deigolocco where are the filters?

**Comment by deigolocco** [comment]
@KimMcMahon @dankohn all adjustments were done. We registered all webinars too. The filtering is not visible because the webinars are not tagged with "Companies" and "Topics" yet, we don't have this information.

**Comment by cjyabraham** [comment]
Just looking at [this page](https://www.cncf.io/webinars/) for the first time.  A few points:
1. Can you make the topics filter wider so the text doesn't get truncated as often
2. Should we have the [titles of the webinars clickable](https://www.cncf.io/webinars/?_project=envoy&_topic=service-mesh)?  I keep going to click them but can't.
3. The ["Let Us Know" button](https://www.cncf.io/webinars/application-modernization-portability-across-clouds/#) in the footer links to the same page.  Where should it link to @KimMcMahon ?
4. Why is there such a big gap here?  I assume it's missing some info?
<img width="563" alt="Screen Shot 2019-08-21 at 12 05 07 PM" src="https://user-images.githubusercontent.com/463160/63404086-0db30b00-c40c-11e9-83fb-e1e8f1809555.png">

**Comment by deigolocco** [comment]
1. Done
2. Done
3. According with @KimMcMahon we added the same link of the old recorde webinars (mailto:webinars@cncf.io)
4. There's no event missing time, so no gap
<img width="589" alt="Captura de Tela 2019-08-21 às 10 27 54" src="https://user-images.githubusercontent.com/5631313/63437216-857b3880-c400-11e9-934b-052c4f1bc17d.png">

**Comment by cjyabraham** [comment]
This is deployed.

**Comment by cjyabraham** [comment]
1. The ["Let Us Know" button is still not set here](https://www.cncf.io/webinars/securing-cloud-native-communication/). 
2. Could you make the [title clickable on the slider](https://www.cncf.io/webinars/kubernetes-ingress-simplify-cluster-management/) so it's consistent behavior with all other webinar listings?
3. When I hover over [the webinar listing on the main page](https://www.cncf.io/webinars/?_project=envoy) the mouse pointer turns into a grabbing hand.  Why does it do that there as there's nothing I can grab?
4. After filtering on mobile view, the listing of webinars seems malformed, missing the count circles, and the slider no longer works.
5. On mobile view, the count on the slider seems to overlap underlying content on some screens:

<img width="500" alt="Screen Shot 2019-08-22 at 12 05 06 PM" src="https://user-images.githubusercontent.com/463160/63487386-29361880-c4d5-11e9-8652-971a6bb10a14.png">
<img width="493" alt="Screen Shot 2019-08-22 at 12 07 01 PM" src="https://user-images.githubusercontent.com/463160/63487429-61d5f200-c4d5-11e9-97be-c036785da3e6.png">

**Comment by deigolocco** [comment]
@cjyabraham, everything adjusted

**Comment by cjyabraham** [comment]
@KimMcMahon the few minor issues below I don't think need to block linking in to the menu and making live.

@deigolocco :
1. Could you lower the ["Webinars"](https://www.cncf.io/webinars/) title to be at the same height as ["Events We'll Be At"](https://www.cncf.io/events-well-be-at/) in the headers.
2. I think you don't need to repeat the "6" in the [mobile pagination here](https://www.cncf.io/webinars/?_project=envoy):
<img width="356" alt="Screen Shot 2019-08-23 at 2 54 02 PM" src="https://user-images.githubusercontent.com/463160/63576175-dda76b80-c5b5-11e9-9fec-391b4f0f84fb.png">

3. Can you put the [dates](https://www.cncf.io/webinars/?_project=envoy) on their own line:
<img width="867" alt="Screen Shot 2019-08-23 at 2 47 36 PM" src="https://user-images.githubusercontent.com/463160/63575749-0844f480-c5b5-11e9-87b8-5fc24e2dacec.png">

**Comment by deigolocco** [comment]
Itens 1 and 3 fixed, working on item 2

**Comment by deigolocco** [comment]
Item 2 ajdusted, everything working now @cjyabraham

**Comment by cjyabraham** [comment]
1 and 3 look fixed but [2 still seems a problem for me](https://new-webinar-cncf.pantheonsite.io/webinars/?_project=envoy).  Can you double check?

**Comment by deigolocco** [comment]
Hi @cjyabraham, I did, looks like you are with some cache at your device
![screen](https://user-images.githubusercontent.com/5631313/63635940-d8423380-c63e-11e9-9405-44a94ee878e4.png)
working as expected

**Comment by cjyabraham** [comment]
It seems to be an issue for me at the most narrow width of desktop chrome or safari.  I get it consistently when logged in or not, incognito or not, hummingbird active or not.  Since you can't reproduce the issue, I guess it's an edge-case and we can skip it for now.

**Comment by deigolocco** [comment]
Ok @cjyabraham, as we chat on slack we couldn't reproduce this bug in any device or browser, no matter if we are on incognito mode, logged in or not.

**Comment by cjyabraham** [comment]
This is deployed.

**Comment by KimMcMahon** [comment]
@cjyabraham Webinar page is working perfectly. Are there tasks remaining before we close this issue?

**Comment by cjyabraham** [comment]
Yes, there are 3 remaining tasks.  See the top of this issue.

**Comment by KimMcMahon** [comment]
@cjyabraham Is this task "Update CNCF menus to deploy all of the above (Kim)" the Community menu?

**Comment by cjyabraham** [comment]
Yes, it's #5.

**Comment by cjyabraham** [comment]
In addition to #5, I've created #62 and #63 to account for the outstanding tasks.  We can consider this issue closed.
