### ISSUE TITLE
Update banner for individual Events We'll Be At

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#80]
Update the banner we use for the individual "[Events We'll Be At](https://www.cncf.io/events-well-be-at/)" (example https://www.cncf.io/events-well-be-at/helm-summit/) so any Wordpress user can create a banner that fits a template for the pages.

From @cjyabraham I strongly feel we should avoid designs that require ongoing support from a designer. There is so much that needs keeping up-to-date on the site that having to coordinate efforts from an external team just to advertise an Event we'll be at seems a lot of trouble. Couldn't this be configured to just require uploading an SVG (or PNG) logo and then choosing a background image from a set that are available in the Media Library? The same logo/background could be used for the square on the home page. That way no external help would be needed.

**Comment by pablodelarocha** [comment]
@KimMcMahon i'm sending attached several banner templates for you to take a look. We selected a few images and generated the banner in several different color schemes, so you can pick the one that matches better with the event's logo which will be applied over it. 
Please let us know what you think of these.

![City-1a99b9](https://user-images.githubusercontent.com/54405572/64168673-72b22c00-ce22-11e9-85a0-02ee58483a04.jpg)
![City-5fdfa1](https://user-images.githubusercontent.com/54405572/64168674-72b22c00-ce22-11e9-9c5f-118613b60c9a.jpg)
![City-5fdfce](https://user-images.githubusercontent.com/54405572/64168675-72b22c00-ce22-11e9-906f-ef51654711d7.jpg)
![City-b04848](https://user-images.githubusercontent.com/54405572/64168676-72b22c00-ce22-11e9-85be-2b6587a9baef.jpg)
![City-cd4172](https://user-images.githubusercontent.com/54405572/64168678-72b22c00-ce22-11e9-9869-f52e16bb256f.jpg)
![City-d4df5f](https://user-images.githubusercontent.com/54405572/64168680-734ac280-ce22-11e9-9f44-5c84f9a19667.jpg)
![City-df8f5f](https://user-images.githubusercontent.com/54405572/64168681-734ac280-ce22-11e9-99ee-51dcea43e774.jpg)
![Congressman-1a99b9](https://user-images.githubusercontent.com/54405572/64168683-734ac280-ce22-11e9-9090-8aab47edca51.jpg)
![Congressman-5fdfa1](https://user-images.githubusercontent.com/54405572/64168684-734ac280-ce22-11e9-981b-d28c4a1dfb01.jpg)
![Congressman-5fdfce](https://user-images.githubusercontent.com/54405572/64168685-73e35900-ce22-11e9-9927-8b04c02cefca.jpg)
![Congressman-b04848](https://user-images.githubusercontent.com/54405572/64168686-73e35900-ce22-11e9-90d1-222a9a766c39.jpg)
![Congressman-cd4172](https://user-images.githubusercontent.com/54405572/64168687-73e35900-ce22-11e9-94c8-360030e36518.jpg)
![Congressman-d4df5f](https://user-images.githubusercontent.com/54405572/64168688-73e35900-ce22-11e9-8ab2-92ce47e3d3ee.jpg)
![Congressman-df8f5f](https://user-images.githubusercontent.com/54405572/64168689-747bef80-ce22-11e9-85d7-7e9717237241.jpg)
![Laptop-1a99b9](https://user-images.githubusercontent.com/54405572/64168690-747bef80-ce22-11e9-894c-7d84e63d5e5e.jpg)
![Laptop-5fdfa1](https://user-images.githubusercontent.com/54405572/64168691-747bef80-ce22-11e9-9baa-076dde13fa12.jpg)
![Laptop-5fdfce](https://user-images.githubusercontent.com/54405572/64168692-747bef80-ce22-11e9-9335-e1fce31bd0a9.jpg)
![Laptop-b04848](https://user-images.githubusercontent.com/54405572/64168693-75148600-ce22-11e9-9ab7-c124a2b0d693.jpg)
![Laptop-cd4172](https://user-images.githubusercontent.com/54405572/64168694-75148600-ce22-11e9-8645-f9dd880dff4b.jpg)
![Laptop-d4df5f](https://user-images.githubusercontent.com/54405572/64168695-75148600-ce22-11e9-9482-badf881d0610.jpg)
![Laptop-df8f5f](https://user-images.githubusercontent.com/54405572/64168697-75148600-ce22-11e9-9e06-7876b58dfc4f.jpg)
![Sky-1a99b9](https://user-images.githubusercontent.com/54405572/64168698-75ad1c80-ce22-11e9-88a1-be791189bcbc.jpg)
![Sky-5fdfa1](https://user-images.githubusercontent.com/54405572/64168699-75ad1c80-ce22-11e9-86e5-ab4283826f08.jpg)
![Sky-5fdfce](https://user-images.githubusercontent.com/54405572/64168700-75ad1c80-ce22-11e9-8046-af4e46f805da.jpg)
![Sky-b04848](https://user-images.githubusercontent.com/54405572/64168701-75ad1c80-ce22-11e9-81ed-769da7a2a762.jpg)
![Sky-cd4172](https://user-images.githubusercontent.com/54405572/64168702-75ad1c80-ce22-11e9-87c7-b1a557020aa8.jpg)
![Sky-d4df5f](https://user-images.githubusercontent.com/54405572/64168703-7645b300-ce22-11e9-8572-e4896bc91270.jpg)
![Sky-df8f5f](https://user-images.githubusercontent.com/54405572/64168704-7645b300-ce22-11e9-958d-fa41604f2127.jpg)
![Speaker-1a99b9](https://user-images.githubusercontent.com/54405572/64168705-76de4980-ce22-11e9-94b9-d487d050f10c.jpg)
![Speaker-5fdfa1](https://user-images.githubusercontent.com/54405572/64168706-76de4980-ce22-11e9-93c7-ce8a5135ccfb.jpg)
![Speaker-5fdfce](https://user-images.githubusercontent.com/54405572/64168707-76de4980-ce22-11e9-94dc-da22da218ff9.jpg)
![Speaker-b04848](https://user-images.githubusercontent.com/54405572/64168708-76de4980-ce22-11e9-9658-3c2fea6c96fc.jpg)
![Speaker-cd4172](https://user-images.githubusercontent.com/54405572/64168709-7776e000-ce22-11e9-8599-987e0bd0c729.jpg)
![Speaker-d4df5f](https://user-images.githubusercontent.com/54405572/64168710-7776e000-ce22-11e9-82e2-25eb7be09b23.jpg)
![Speaker-df8f5f](https://user-images.githubusercontent.com/54405572/64168711-7776e000-ce22-11e9-905a-b080f5f34009.jpg)
![Writter-1a99b9](https://user-images.githubusercontent.com/54405572/64168712-780f7680-ce22-11e9-853a-67de700dae1f.jpg)
![Writter-5fdfa1](https://user-images.githubusercontent.com/54405572/64168713-780f7680-ce22-11e9-8323-62d9c55f72d3.jpg)
![Writter-5fdfce](https://user-images.githubusercontent.com/54405572/64168715-780f7680-ce22-11e9-940d-88dc5fecdf5b.jpg)
![Writter-b04848](https://user-images.githubusercontent.com/54405572/64168716-780f7680-ce22-11e9-8df5-bf7a5ed9a9b7.jpg)
![Writter-cd4172](https://user-images.githubusercontent.com/54405572/64168718-780f7680-ce22-11e9-9206-4bbc1530037a.jpg)
![Writter-d4df5f](https://user-images.githubusercontent.com/54405572/64168719-78a80d00-ce22-11e9-9ebd-d838bdb53734.jpg)
![Writter-df8f5f](https://user-images.githubusercontent.com/54405572/64168720-78a80d00-ce22-11e9-92c9-790260eac0a1.jpg)

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha. I like them. Can you pull 2 images from the CNCF Flickr account to use for these banners? Please make sure both images have at least one women in the image. 

Then - how do I use these? Can you write up a short process on how to use these on the Events page and the Home page?

**Comment by pablodelarocha** [comment]
@KimMcMahon as discussed in issue #62 i believe we're not going to use these for now, since it was decided we were going to create a specific banner for homepage and another for the "Events We'll Be At" page on each event.
I can do the banners as you requested, but there's no use for them, since you can't upload separately the banner and the event's logo.

**Comment by cjyabraham** [comment]
@KimMcMahon do you still want to pursue this idea or should we cancel this issue?

**Comment by KimMcMahon** [comment]
@cjyabraham I still want to come up with a solution so I can 'create' the two image sizes when I set up an event.

For some events, I may still want a custom banner. For most events, I just need an image I can add a logo to.

**Comment by KimMcMahon** [comment]
Closing - covering with another issue.
