### ISSUE TITLE
Create banners for Event's We'll Be At and update Events page and Home page

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#83]
EnvoyCon
![envoycon-stacked-color](https://user-images.githubusercontent.com/29307455/64219094-44b00480-ce81-11e9-91dc-dce0311df031.png)

ServiceMeshCon
Grab the logo from this page: https://events.linuxfoundation.org/events/servicemeshcon-2019/

Observability Practitioners Summit
Grab the logo from this page: https://observabilitysummit.com

FoundationDB Summit
Grab the logo from this page: https://events.linuxfoundation.org/events/foundationdb-summit-2019/

MWC Barcelona
Grab the logo from this page: https://www.mwcbarcelona.com/

Red Hat Summit
Grab the logo from this page: https://www.redhat.com/en/summit

Microsoft Build
Grab the logo from this page: https://www.microsoft.com/en-us/build

**Comment by pablodelarocha** [comment]
@KimMcMahon sure! Here's the banners in two versions (for homepage and for the EWBA page:
![envoycon](https://user-images.githubusercontent.com/54405572/64261156-71f0c700-cf02-11e9-9700-efd4f25e810c.jpg)
![squared_envoycon](https://user-images.githubusercontent.com/54405572/64261200-88971e00-cf02-11e9-91ac-61791276b406.jpg)
![servicemeshcon](https://user-images.githubusercontent.com/54405572/64261269-a1073880-cf02-11e9-8761-5de9a1019c29.jpg)
![squared_servicemeshcon](https://user-images.githubusercontent.com/54405572/64261390-d6138b00-cf02-11e9-9ec7-622fd312ddb0.jpg)
![Observability-Practitioners-Summit](https://user-images.githubusercontent.com/54405572/64261523-0a874700-cf03-11e9-81f2-347b15cd4106.png)
![squared_observability](https://user-images.githubusercontent.com/54405572/64261683-43272080-cf03-11e9-8fad-8faa76784ca9.jpg)
![FoundationDB_Summit](https://user-images.githubusercontent.com/54405572/64261794-779adc80-cf03-11e9-9549-448b3297e70d.jpg)
![squared_FoundationDB_Summit](https://user-images.githubusercontent.com/54405572/64261894-a3b65d80-cf03-11e9-8e61-cd8cd7121587.jpg)
![MWC_Barcelona](https://user-images.githubusercontent.com/54405572/64262411-70280300-cf04-11e9-8faf-8012826cd7c0.jpg)
![squared_MWC_Barcelona](https://user-images.githubusercontent.com/54405572/64262429-75854d80-cf04-11e9-9fc2-f2880cf68a3e.jpg)
![redhat_summit](https://user-images.githubusercontent.com/54405572/64263069-74085500-cf05-11e9-9ee4-ea9fc79ac7af.jpg)
![squared_Redhat_Summit](https://user-images.githubusercontent.com/54405572/64263090-7a96cc80-cf05-11e9-8780-d8d3e631bcd2.jpg)
![Microsoft_Build](https://user-images.githubusercontent.com/54405572/64263956-ec234a80-cf06-11e9-823a-61dcafbe89f1.jpg)
![squared_Microsoft_Build](https://user-images.githubusercontent.com/54405572/64263979-f7767600-cf06-11e9-9e84-b8d684021c1c.jpg)
