### ISSUE TITLE
Standardize homepage sub-heading styles

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#85]
With these various updates to the homepage, we seem to be introducing too many sub-heading styles:
<img width="1253" alt="Screen Shot 2019-09-04 at 1 01 02 PM" src="https://user-images.githubusercontent.com/463160/64229499-221afb80-cf14-11e9-89ca-8ffd556f84c0.png">
<img width="1247" alt="Screen Shot 2019-09-04 at 1 00 02 PM" src="https://user-images.githubusercontent.com/463160/64229500-22b39200-cf14-11e9-814b-c43b47ee624b.png">
<img width="1251" alt="Screen Shot 2019-09-04 at 1 00 11 PM" src="https://user-images.githubusercontent.com/463160/64229501-22b39200-cf14-11e9-87df-98fef3d01569.png">

Instead of having all 3 different sub-heading styles, could we have 2 or even just 1.  I think I like the Newsroom sub-headings the best (Block, Announcements, News) with the icons but am interested in others opinions.  Could we pick one style to use in all 3 places?

**Comment by pablodelarocha** [comment]
Hi @cjyabraham 
please take a look at the design suggestion attached. I've tried your suggestion, but it turns out that the exact same style didn't work on all places, so i made a hybrid. Let us know what you think.
![01-home](https://user-images.githubusercontent.com/54405572/64269110-b6cf2a80-cf0f-11e9-8957-1a6325dbe29b.jpg)

**Comment by KimMcMahon** [comment]
@cjyabraham @pablodelarocha Dan asked for a specific design to match the Google slide. I like the look. Can we leave it for now?

**Comment by dankohn** [comment]
Actually, I don't feel strongly. I was more focused on the content of the slide. I see the argument for consistency.

**Comment by KimMcMahon** [comment]
Ok @pablodelarocha let's update the design! I like what you proposed.

**Comment by pablodelarocha** [comment]
@KimMcMahon great! The dev team is already working on it. Thanks!

**Comment by cjyabraham** [comment]
Looks great @pablodelarocha!

**Comment by rodmeurer** [comment]
@KimMcMahon @cjyabraham up to date!
https://fz-85-cncf.pantheonsite.io/

**Comment by dankohn** [comment]
LGTM

**Comment by KimMcMahon** [comment]
@cjyabraham please deploy

**Comment by cjyabraham** [comment]
Deployed.
