### ISSUE TITLE
Rectangle and square banner for Events We'll Be At

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#87]
Can I get a banner for each of our KubeCon events? You can use the images and logos as they are on this page:
https://www.cncf.io/community/kubecon-cloudnativecon-events/

KubeCon + CloudNativeCon North America 2019 (San Diego)
KubeCon + CloudNativeCon Europe 2020 (Amsterdam)
KubeCon + CloudNativeCon China 2020 (Shanghai)
KubeCon + CloudNativeCon North America 2020 (Boston)

**Comment by pablodelarocha** [comment]
@KimMcMahon Ok! Here's the banners:
![squared_Kubecon-Europe-Amsterdam](https://user-images.githubusercontent.com/54405572/64378487-312ca700-d003-11e9-85a5-bc309c9804c7.jpg)
![Kubecon-Europe-Amsterdam](https://user-images.githubusercontent.com/54405572/64378489-32f66a80-d003-11e9-8801-7d29558bf218.jpg)
![squared_Kubecon-Shanghai](https://user-images.githubusercontent.com/54405572/64378492-3558c480-d003-11e9-8e2b-50f27d38cf71.jpg)
![kubecon-Shanghai](https://user-images.githubusercontent.com/54405572/64378495-37bb1e80-d003-11e9-9adc-8140d9457427.jpg)
![squared_Kubecon-North-America_SanDiego](https://user-images.githubusercontent.com/54405572/64378498-3984e200-d003-11e9-92b3-d881e9a2d46c.jpg)
![Kubecon-North-America_SanDiego](https://user-images.githubusercontent.com/54405572/64378504-3be73c00-d003-11e9-80a5-87cbddda5389.jpg)
![squared_Kubecon-North-America-Boston](https://user-images.githubusercontent.com/54405572/64378509-3db0ff80-d003-11e9-8130-b92c9a69574a.jpg)
![Kubecon-North-America-Boston](https://user-images.githubusercontent.com/54405572/64378515-40abf000-d003-11e9-811b-8bbe8202d5c1.jpg)
Please, let me know if these are all ok to go and if you need anything else!

**Comment by pablodelarocha** [comment]
@KimMcMahon  here's the adjusted Shanghai and San Diego banners as requested.
![squared_Kubecon-Shanghai](https://user-images.githubusercontent.com/54405572/64379778-03952d00-d006-11e9-9f8e-13cae0fafaa4.jpg)
![kubecon-Shanghai](https://user-images.githubusercontent.com/54405572/64379780-042dc380-d006-11e9-8302-40369e5dbea8.jpg)
![Kubecon-North-America_SanDiego](https://user-images.githubusercontent.com/54405572/64379781-042dc380-d006-11e9-8dda-bda0554e2fe5.jpg)
![squared_Kubecon-North-America_SanDiego](https://user-images.githubusercontent.com/54405572/64379782-042dc380-d006-11e9-8cba-7f2e0c790205.jpg)

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha! Perfect!
