### ISSUE TITLE
Events We'll Be At: List city and country

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#88]
Each event is tagged with a city and a country. Please have this information displayed on the individual event page an the Events We'll Be At page.
<img width="1352" alt="Screen Shot 2019-09-05 at 1 28 20 PM" src="https://user-images.githubusercontent.com/29307455/64376109-bc4a7480-cfe4-11e9-9f94-026b8b275d82.png">
<img width="843" alt="Screen Shot 2019-09-05 at 1 54 21 PM" src="https://user-images.githubusercontent.com/29307455/64376110-bc4a7480-cfe4-11e9-8e3f-ba1863609ba3.png">

**Comment by rodmeurer** [comment]
@KimMcMahon @cjyabraham up to date.
https://fz-88-cncf.pantheonsite.io/events-well-be-at/open-networking-summit-eu/
https://fz-88-cncf.pantheonsite.io/events-well-be-at/huawei-connect-2019/

**Comment by KimMcMahon** [comment]
Looks great @rodmeurer! 

@cjyabraham please deploy.

**Comment by cjyabraham** [comment]
This is deployed.  Would we also want this on the home page @KimMcMahon ?

<img width="602" alt="Screen Shot 2019-09-06 at 10 44 57 AM" src="https://user-images.githubusercontent.com/463160/64399633-6385e500-d093-11e9-82cc-eff2ce46d51d.png">

**Comment by deigolocco** [comment]
@cjyabraham added on homepage https://fz-88-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
Something is going funny with the mobile view on this one:
<img width="298" alt="Screen Shot 2019-09-06 at 11 08 52 PM" src="https://user-images.githubusercontent.com/463160/64443102-6caa9c80-d0fb-11e9-93e3-761fcbb1e44e.png">

**Comment by rodmeurer** [comment]
adjusted @cjyabraham 
https://fz-88-cncf.pantheonsite.io/

**Comment by KimMcMahon** [comment]
WDYT @dankohn and @cjyabraham 
With city and country on the home page, the country gets cut off. Just the city on the home . page ok with you?

**Comment by dankohn** [comment]
I like what they have with the country going to ellipses.

**Comment by cjyabraham** [comment]
The ellipses seem to cut off too early on mobile.  Is there a way to have them adapt to the amount of space available?
<img width="250" alt="Screen Shot 2019-09-07 at 9 54 27 AM" src="https://user-images.githubusercontent.com/463160/64469004-8d074500-d155-11e9-88aa-f9ff7d6f109c.png">

**Comment by deigolocco** [comment]
@cjyabraham we did the excerpt with php initially, but changed to js, so we can check the screen size to adjust the excerpt length. 
Please take at look again https://fz-88-cncf.pantheonsite.io/

**Comment by dankohn** [comment]
LGTM

**Comment by cjyabraham** [comment]
Looks good.  Can you resolve the merge conflicts and I'll deploy?

**Comment by deigolocco** [comment]
solved @cjyabraham

**Comment by cjyabraham** [comment]
Deployed.
