### ISSUE TITLE
Speakers Bureau faceted search

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#9]
Implemented a faceted search in the same way we are doing for webinars and case studies

**Comment by KimMcMahon** [comment]
Can we add a more granular search? Not just country (i.e. United States), but state. 

Need to figure out what to do outside the US.

**Comment by dankohn** [comment]
I'm not sure if it's feasible and worth the trouble. If it is, you probably want to emulate the Headquarters Locations options in the filter bar: https://landscape.cncf.io/format=card-mode&grouping=headquarters

**Comment by KimMcMahon** [comment]
See [document](https://docs.google.com/document/d/1IUA1O4Zr73cdtBSJQB9mcEdO0lisxWagNEaofICdty0/edit?usp=sharing) on Speakers Bureau updates.

For this requirement:
Implement a faceted search similar to Webinars and Case Studies.

Fields:
Name
Certifications in profile
Industry (as in the Case Studies)
Area of Expertise (all projects - current list for Speakers Bureau)
All challenges (as in Case Studies). Rename: Technology Focus
All countries (as in Case Studies)

NOTE: if we add a field for self-identification and underrepresented minority, this will be added to the faceted search fields.

**Comment by KimMcMahon** [comment]
@dankohn There is an open question in the document on two potential fields for a speaker. 

The decision is needed so Chris can update the backend for a speaker to update their profile.
I need the updated backend to send a note to speakers to update their profile.

There is a comment in the document, assigned to you.

**Comment by KimMcMahon** [comment]
@cjyabraham Faceted search items are updated and ready for you!

**Comment by cjyabraham** [comment]
from @dankohn : 

> Could we try a design refresh where we show "City, Country" and Areas of Expertise to the right of the picture and make every speaker box the same size? I don't see any reason to highlight Twitter and LinkedIn links from the scrolling page. Instead, it would allow a much denser list of speakers which would be faster to scroll through.

**Comment by cjyabraham** [comment]
closed in favor of #57
