### ISSUE TITLE
Add @cloudnativefdn Twitter feed next to News

### ISSUE THREAD

**Issue by dankohn** [cncf/wordpress-site#92]
Please add a 4th column of Newsroom updates to the right of news that embeds our latest tweets.

Use the embed feature on https://publish.twitter.com/?query=https%3A%2F%2Ftwitter.com%2Fcloudnativefdn&widget=Timeline and update to set height, width, and color appropriately.

**Comment by deigolocco** [comment]
ok @dankohn and @cjyabraham

**Comment by deigolocco** [comment]
@dankohn 4 tweets without header, footer and scrollbar
![twitter](https://user-images.githubusercontent.com/5631313/64863494-56c13e00-d60b-11e9-84ba-09fd6f3737ab.jpg)
looks like too long compared with the other columns, should I reduce the number of tweets?

**Comment by dankohn** [comment]
The issue is that the length is dynamic based on the number of pictures. I believe there is a height parameter that you can add that would add a scrollbar. Please recommend some alternatives.

**Comment by deigolocco** [comment]
@dankohn I limited the height and added a scrollbar. I also reduced for 2 tweets(to avoid a long scroll) and added the pink button at bottom(View all Tweets).
Please let me know if this works for you. 
I'll improve a little bit more the responsive according with @cjyabraham recommendations

**Comment by dankohn** [comment]
I think that looks great. Please resolve the mobile view and we’re good to go.

**Comment by deigolocco** [comment]
solved @dankohn

**Comment by dankohn** [comment]
Almost there, but part is cropped in this view. 

![49D86358-5DF2-4ACC-8D9A-B740207E1051](https://user-images.githubusercontent.com/3083270/64888318-011c7e00-d66b-11e9-8d73-e2f4ecc6c620.png)

**Comment by deigolocco** [comment]
@dankohn I couldn't reproduce this issue. I believe is cache, I just forced to clean again.
If this issue persists for you, could you share more information please? Like the device, browser, etc...

**Comment by dankohn** [comment]
It’s iPhone XS Max on latest iOS after doing a hard reload. 

--
Dan Kohn <dan@linuxfoundation.org> +1-415-233-1000
Executive Director, Cloud Native Computing Foundation cncf.io
dankohn.com or book on my calendar: dankohn.com/c

**Comment by deigolocco** [comment]
thanks @dankohn , with your direction I could reproduce the bug and fix it. Could you test again please?

**Comment by dankohn** [comment]
I'm still seeing the issue after multiple refreshes.

Cc @jordinl83 who is working on a similar Twitter embed bug on l.cncf.io and might have some suggestions.

Screenshots:

![image](https://user-images.githubusercontent.com/3083270/64901414-e7793780-d666-11e9-935d-4d39ce387d91.png)

![image](https://user-images.githubusercontent.com/3083270/64901788-4476ec80-d66b-11e9-9cd9-e2d091e6bf71.png)

**Comment by cjyabraham** [comment]
LGTM.  @dankohn, I just cleared all the caches.  Is it still not right for you?

**Comment by KimMcMahon** [comment]
From my iPhone X, it looks fine. Tested on an iPhone XS and looks fine. 
![Image-1](https://user-images.githubusercontent.com/29307455/64910902-ad487e00-d6d8-11e9-9a45-edb538b74039.jpeg)

**Comment by dankohn** [comment]
LGTM

**Comment by cjyabraham** [comment]
This is deployed.
