### ISSUE TITLE
Create a banner for Events We'll Be At

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#95]
[Grace Hopper](https://ghc.anitab.org/2019-anitab-org-pitcher/)
<img width="317" alt="Screen Shot 2019-09-09 at 4 46 51 PM" src="https://user-images.githubusercontent.com/29307455/64571552-7ada0200-d321-11e9-81fc-3264a70589b7.png">

**Comment by pablodelarocha** [comment]
![grace_hopper_banner](https://user-images.githubusercontent.com/54405572/64609721-f086b200-d3a3-11e9-9be1-250cdf2861c0.jpg)
![squared_grace_hopper](https://user-images.githubusercontent.com/54405572/64609722-f086b200-d3a3-11e9-83aa-cf9bbbf72148.jpg)
@KimMcMahon here's the banner on both versions as requested.

**Comment by KimMcMahon** [comment]
Thank you @pablodelarocha!
