### ISSUE TITLE
Date is overflowing its box

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#97]
See screenshot:
<img width="548" alt="Screen Shot 2019-09-15 at 9 26 10 AM" src="https://user-images.githubusercontent.com/463160/64915855-f6f99d00-d79a-11e9-8b6c-4ad3e65f461f.png">

**Comment by KimMcMahon** [comment]
Same behavior, landscape view iPhone X
![IMG_2258](https://user-images.githubusercontent.com/29307455/64923888-b4849000-d79b-11e9-9fa9-a5d75a64a760.JPG)

**Comment by deigolocco** [comment]
@cjyabraham and @KimMcMahon It's adjusted

**Comment by cjyabraham** [comment]
It seems to have pushed "Shanghai, China" outside of the box edge:
<img width="296" alt="Screen Shot 2019-09-18 at 3 06 07 PM" src="https://user-images.githubusercontent.com/463160/65129639-ec9f0380-da25-11e9-93f2-7c2bf6f8aad3.png">

**Comment by deigolocco** [comment]
fixed @cjyabraham https://fz-97-cncf.pantheonsite.io/

**Comment by cjyabraham** [comment]
Looks good.  Can you fix the merge conflicts and I'll deploy?

**Comment by deigolocco** [comment]
Solved @cjyabraham

**Comment by cjyabraham** [comment]
Deployed.
