### ISSUE TITLE
Home page Twitter on iPhone

### ISSUE THREAD

**Issue by KimMcMahon** [cncf/wordpress-site#98]
Twitter broken on home page on iPhone X.
![IMG_2257](https://user-images.githubusercontent.com/29307455/64923841-463fcd80-d79b-11e9-8ed1-bb7aaf7d91d2.JPG)

**Comment by deigolocco** [comment]
@KimMcMahon I'm using browserstack.com to validate different devices
first time that Dan reported, I found the bug and fixed
now I can't reproduce this bug anymore. Is this bug still persisting for you?

**Comment by KimMcMahon** [comment]
@deigolocco looks now. Thank you!
