### ISSUE TITLE
Pagination buttons are too close

### ISSUE THREAD

**Issue by cjyabraham** [cncf/wordpress-site#99]
Google is reporting that the clickable elements are "too close together" on the mobile view of [this page](https://www.cncf.io/author/cncf/page/11/).  I assume it's referring to the pagination numbers.  Could you separate them slightly for mobile view across the various pages that use them?

**Comment by deigolocco** [comment]
adjusted @cjyabraham 
https://fz-99-cncf.pantheonsite.io/newsroom/in-the-news/page/3/

**Comment by cjyabraham** [comment]
The "Next" and "Previous" seem to have fallen out of place:

<img width="338" alt="Screen Shot 2019-09-18 at 2 59 28 PM" src="https://user-images.githubusercontent.com/463160/65129253-1c014080-da25-11e9-9b2c-2e26e2cf77f0.png">

**Comment by deigolocco** [comment]
@cjyabraham looks like you did a screen resize, could you refresh your browser please?
this supposed to be the appearance for a screen smaller than 1024px width
![Captura de Tela 2019-09-18 às 08 00 33](https://user-images.githubusercontent.com/5631313/65143213-c9a32e00-d9ea-11e9-99bd-6682441e2a1f.png)

**Comment by cjyabraham** [comment]
Ok.  I've deployed what you have so far but can you take a closer look at which numbers are being shown.  For example, when I go [here](https://www.cncf.io/newsroom/announcements/) I see:

<img width="349" alt="Screen Shot 2019-09-18 at 9 22 52 PM" src="https://user-images.githubusercontent.com/463160/65157277-b16af780-da5a-11e9-9cac-ddaaf0168737.png">


and then on [page 2](https://www.cncf.io/newsroom/announcements/page/2/), I see:

<img width="346" alt="Screen Shot 2019-09-18 at 9 23 02 PM" src="https://user-images.githubusercontent.com/463160/65157260-ad3eda00-da5a-11e9-8e6a-44830be38351.png">


and on [page 3](https://www.cncf.io/newsroom/announcements/page/3/), I see:

<img width="360" alt="Screen Shot 2019-09-18 at 9 23 11 PM" src="https://user-images.githubusercontent.com/463160/65157241-a57f3580-da5a-11e9-9d78-d56a0b0afcbc.png">

Shouldn't we see all 5 numbers (and no "...") on all pages?

**Comment by deigolocco** [comment]
@cjyabraham we are using the [default wordpress pagination](https://codex.wordpress.org/Function_Reference/paginate_links).
We set the rule to show one page before and one after of the current one. Depending of the position and the number of pages we'll have ellipses to indicate the first and the last page.
<img width="359" alt="Captura de Tela 2019-09-18 às 12 02 08" src="https://user-images.githubusercontent.com/5631313/65160753-b1dca180-da0c-11e9-8a9e-e2414951ae70.png">
This [case](https://fz-99-cncf.pantheonsite.io/newsroom/blog/page/4/) illustrate a little bit better a situation with all elements.
Do you suggest a different configuration?
We can create a custom pagination if you fell necessary.

**Comment by cjyabraham** [comment]
I see.  Ok.  Let's leave it as is for now.  Thanks.
